/* This file is automatically generated by aarch64-gen.  Do not edit!  */
/* Copyright (C) 2012-2020 Free Software Foundation, Inc.
   Contributed by ARM Ltd.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; see the file COPYING3. If not,
   see <http://www.gnu.org/licenses/>.  */

#include "sysdep.h"
#include "aarch64-asm.h"


const aarch64_opcode *
aarch64_find_real_opcode (const aarch64_opcode *opcode)
{
  /* Use the index as the key to locate the real opcode.  */
  int key = opcode - aarch64_opcode_table;
  int value;
  switch (key)
    {
    case 3:	/* ngc */
    case 2:	/* sbc */
      value = 2;	/* --> sbc.  */
      break;
    case 5:	/* ngcs */
    case 4:	/* sbcs */
      value = 4;	/* --> sbcs.  */
      break;
    case 8:	/* cmn */
    case 7:	/* adds */
      value = 7;	/* --> adds.  */
      break;
    case 11:	/* cmp */
    case 10:	/* subs */
      value = 10;	/* --> subs.  */
      break;
    case 13:	/* mov */
    case 12:	/* add */
      value = 12;	/* --> add.  */
      break;
    case 15:	/* cmn */
    case 14:	/* adds */
      value = 14;	/* --> adds.  */
      break;
    case 18:	/* cmp */
    case 17:	/* subs */
      value = 17;	/* --> subs.  */
      break;
    case 23:	/* cmn */
    case 22:	/* adds */
      value = 22;	/* --> adds.  */
      break;
    case 25:	/* neg */
    case 24:	/* sub */
      value = 24;	/* --> sub.  */
      break;
    case 27:	/* cmp */
    case 28:	/* negs */
    case 26:	/* subs */
      value = 26;	/* --> subs.  */
      break;
    case 153:	/* mov */
    case 152:	/* umov */
      value = 152;	/* --> umov.  */
      break;
    case 155:	/* mov */
    case 154:	/* ins */
      value = 154;	/* --> ins.  */
      break;
    case 157:	/* mov */
    case 156:	/* ins */
      value = 156;	/* --> ins.  */
      break;
    case 243:	/* mvn */
    case 242:	/* not */
      value = 242;	/* --> not.  */
      break;
    case 318:	/* mov */
    case 317:	/* orr */
      value = 317;	/* --> orr.  */
      break;
    case 389:	/* sxtl */
    case 388:	/* sshll */
      value = 388;	/* --> sshll.  */
      break;
    case 391:	/* sxtl2 */
    case 390:	/* sshll2 */
      value = 390;	/* --> sshll2.  */
      break;
    case 413:	/* uxtl */
    case 412:	/* ushll */
      value = 412;	/* --> ushll.  */
      break;
    case 415:	/* uxtl2 */
    case 414:	/* ushll2 */
      value = 414;	/* --> ushll2.  */
      break;
    case 536:	/* mov */
    case 535:	/* dup */
      value = 535;	/* --> dup.  */
      break;
    case 623:	/* sxtw */
    case 622:	/* sxth */
    case 621:	/* sxtb */
    case 624:	/* asr */
    case 620:	/* sbfx */
    case 619:	/* sbfiz */
    case 618:	/* sbfm */
      value = 618;	/* --> sbfm.  */
      break;
    case 627:	/* bfc */
    case 628:	/* bfxil */
    case 626:	/* bfi */
    case 625:	/* bfm */
      value = 625;	/* --> bfm.  */
      break;
    case 633:	/* uxth */
    case 632:	/* uxtb */
    case 635:	/* lsr */
    case 634:	/* lsl */
    case 631:	/* ubfx */
    case 630:	/* ubfiz */
    case 629:	/* ubfm */
      value = 629;	/* --> ubfm.  */
      break;
    case 665:	/* cset */
    case 664:	/* cinc */
    case 663:	/* csinc */
      value = 663;	/* --> csinc.  */
      break;
    case 668:	/* csetm */
    case 667:	/* cinv */
    case 666:	/* csinv */
      value = 666;	/* --> csinv.  */
      break;
    case 670:	/* cneg */
    case 669:	/* csneg */
      value = 669;	/* --> csneg.  */
      break;
    case 688:	/* rev */
    case 689:	/* rev64 */
      value = 688;	/* --> rev.  */
      break;
    case 714:	/* lsl */
    case 713:	/* lslv */
      value = 713;	/* --> lslv.  */
      break;
    case 716:	/* lsr */
    case 715:	/* lsrv */
      value = 715;	/* --> lsrv.  */
      break;
    case 718:	/* asr */
    case 717:	/* asrv */
      value = 717;	/* --> asrv.  */
      break;
    case 720:	/* ror */
    case 719:	/* rorv */
      value = 719;	/* --> rorv.  */
      break;
    case 723:	/* cmpp */
    case 722:	/* subps */
      value = 722;	/* --> subps.  */
      break;
    case 736:	/* mul */
    case 735:	/* madd */
      value = 735;	/* --> madd.  */
      break;
    case 738:	/* mneg */
    case 737:	/* msub */
      value = 737;	/* --> msub.  */
      break;
    case 740:	/* smull */
    case 739:	/* smaddl */
      value = 739;	/* --> smaddl.  */
      break;
    case 742:	/* smnegl */
    case 741:	/* smsubl */
      value = 741;	/* --> smsubl.  */
      break;
    case 745:	/* umull */
    case 744:	/* umaddl */
      value = 744;	/* --> umaddl.  */
      break;
    case 747:	/* umnegl */
    case 746:	/* umsubl */
      value = 746;	/* --> umsubl.  */
      break;
    case 759:	/* ror */
    case 758:	/* extr */
      value = 758;	/* --> extr.  */
      break;
    case 992:	/* bic */
    case 991:	/* and */
      value = 991;	/* --> and.  */
      break;
    case 994:	/* mov */
    case 993:	/* orr */
      value = 993;	/* --> orr.  */
      break;
    case 997:	/* tst */
    case 996:	/* ands */
      value = 996;	/* --> ands.  */
      break;
    case 1001:	/* mov */
    case 1194:	/* mov */
    case 1002:	/* uxtw */
    case 1000:	/* orr */
      value = 1000;	/* --> orr.  */
      break;
    case 1004:	/* mvn */
    case 1003:	/* orn */
      value = 1003;	/* --> orn.  */
      break;
    case 1008:	/* tst */
    case 1007:	/* ands */
      value = 1007;	/* --> ands.  */
      break;
    case 1134:	/* staddb */
    case 1038:	/* ldaddb */
      value = 1038;	/* --> ldaddb.  */
      break;
    case 1135:	/* staddh */
    case 1039:	/* ldaddh */
      value = 1039;	/* --> ldaddh.  */
      break;
    case 1136:	/* stadd */
    case 1040:	/* ldadd */
      value = 1040;	/* --> ldadd.  */
      break;
    case 1137:	/* staddlb */
    case 1042:	/* ldaddlb */
      value = 1042;	/* --> ldaddlb.  */
      break;
    case 1138:	/* staddlh */
    case 1045:	/* ldaddlh */
      value = 1045;	/* --> ldaddlh.  */
      break;
    case 1139:	/* staddl */
    case 1048:	/* ldaddl */
      value = 1048;	/* --> ldaddl.  */
      break;
    case 1140:	/* stclrb */
    case 1050:	/* ldclrb */
      value = 1050;	/* --> ldclrb.  */
      break;
    case 1141:	/* stclrh */
    case 1051:	/* ldclrh */
      value = 1051;	/* --> ldclrh.  */
      break;
    case 1142:	/* stclr */
    case 1052:	/* ldclr */
      value = 1052;	/* --> ldclr.  */
      break;
    case 1143:	/* stclrlb */
    case 1054:	/* ldclrlb */
      value = 1054;	/* --> ldclrlb.  */
      break;
    case 1144:	/* stclrlh */
    case 1057:	/* ldclrlh */
      value = 1057;	/* --> ldclrlh.  */
      break;
    case 1145:	/* stclrl */
    case 1060:	/* ldclrl */
      value = 1060;	/* --> ldclrl.  */
      break;
    case 1146:	/* steorb */
    case 1062:	/* ldeorb */
      value = 1062;	/* --> ldeorb.  */
      break;
    case 1147:	/* steorh */
    case 1063:	/* ldeorh */
      value = 1063;	/* --> ldeorh.  */
      break;
    case 1148:	/* steor */
    case 1064:	/* ldeor */
      value = 1064;	/* --> ldeor.  */
      break;
    case 1149:	/* steorlb */
    case 1066:	/* ldeorlb */
      value = 1066;	/* --> ldeorlb.  */
      break;
    case 1150:	/* steorlh */
    case 1069:	/* ldeorlh */
      value = 1069;	/* --> ldeorlh.  */
      break;
    case 1151:	/* steorl */
    case 1072:	/* ldeorl */
      value = 1072;	/* --> ldeorl.  */
      break;
    case 1152:	/* stsetb */
    case 1074:	/* ldsetb */
      value = 1074;	/* --> ldsetb.  */
      break;
    case 1153:	/* stseth */
    case 1075:	/* ldseth */
      value = 1075;	/* --> ldseth.  */
      break;
    case 1154:	/* stset */
    case 1076:	/* ldset */
      value = 1076;	/* --> ldset.  */
      break;
    case 1155:	/* stsetlb */
    case 1078:	/* ldsetlb */
      value = 1078;	/* --> ldsetlb.  */
      break;
    case 1156:	/* stsetlh */
    case 1081:	/* ldsetlh */
      value = 1081;	/* --> ldsetlh.  */
      break;
    case 1157:	/* stsetl */
    case 1084:	/* ldsetl */
      value = 1084;	/* --> ldsetl.  */
      break;
    case 1158:	/* stsmaxb */
    case 1086:	/* ldsmaxb */
      value = 1086;	/* --> ldsmaxb.  */
      break;
    case 1159:	/* stsmaxh */
    case 1087:	/* ldsmaxh */
      value = 1087;	/* --> ldsmaxh.  */
      break;
    case 1160:	/* stsmax */
    case 1088:	/* ldsmax */
      value = 1088;	/* --> ldsmax.  */
      break;
    case 1161:	/* stsmaxlb */
    case 1090:	/* ldsmaxlb */
      value = 1090;	/* --> ldsmaxlb.  */
      break;
    case 1162:	/* stsmaxlh */
    case 1093:	/* ldsmaxlh */
      value = 1093;	/* --> ldsmaxlh.  */
      break;
    case 1163:	/* stsmaxl */
    case 1096:	/* ldsmaxl */
      value = 1096;	/* --> ldsmaxl.  */
      break;
    case 1164:	/* stsminb */
    case 1098:	/* ldsminb */
      value = 1098;	/* --> ldsminb.  */
      break;
    case 1165:	/* stsminh */
    case 1099:	/* ldsminh */
      value = 1099;	/* --> ldsminh.  */
      break;
    case 1166:	/* stsmin */
    case 1100:	/* ldsmin */
      value = 1100;	/* --> ldsmin.  */
      break;
    case 1167:	/* stsminlb */
    case 1102:	/* ldsminlb */
      value = 1102;	/* --> ldsminlb.  */
      break;
    case 1168:	/* stsminlh */
    case 1105:	/* ldsminlh */
      value = 1105;	/* --> ldsminlh.  */
      break;
    case 1169:	/* stsminl */
    case 1108:	/* ldsminl */
      value = 1108;	/* --> ldsminl.  */
      break;
    case 1170:	/* stumaxb */
    case 1110:	/* ldumaxb */
      value = 1110;	/* --> ldumaxb.  */
      break;
    case 1171:	/* stumaxh */
    case 1111:	/* ldumaxh */
      value = 1111;	/* --> ldumaxh.  */
      break;
    case 1172:	/* stumax */
    case 1112:	/* ldumax */
      value = 1112;	/* --> ldumax.  */
      break;
    case 1173:	/* stumaxlb */
    case 1114:	/* ldumaxlb */
      value = 1114;	/* --> ldumaxlb.  */
      break;
    case 1174:	/* stumaxlh */
    case 1117:	/* ldumaxlh */
      value = 1117;	/* --> ldumaxlh.  */
      break;
    case 1175:	/* stumaxl */
    case 1120:	/* ldumaxl */
      value = 1120;	/* --> ldumaxl.  */
      break;
    case 1176:	/* stuminb */
    case 1122:	/* lduminb */
      value = 1122;	/* --> lduminb.  */
      break;
    case 1177:	/* stuminh */
    case 1123:	/* lduminh */
      value = 1123;	/* --> lduminh.  */
      break;
    case 1178:	/* stumin */
    case 1124:	/* ldumin */
      value = 1124;	/* --> ldumin.  */
      break;
    case 1179:	/* stuminlb */
    case 1126:	/* lduminlb */
      value = 1126;	/* --> lduminlb.  */
      break;
    case 1180:	/* stuminlh */
    case 1129:	/* lduminlh */
      value = 1129;	/* --> lduminlh.  */
      break;
    case 1181:	/* stuminl */
    case 1132:	/* lduminl */
      value = 1132;	/* --> lduminl.  */
      break;
    case 1183:	/* mov */
    case 1182:	/* movn */
      value = 1182;	/* --> movn.  */
      break;
    case 1185:	/* mov */
    case 1184:	/* movz */
      value = 1184;	/* --> movz.  */
      break;
    case 1193:	/* mov */
    case 1192:	/* cpy */
      value = 1192;	/* --> cpy.  */
      break;
    case 1201:	/* cmp */
    case 1200:	/* subs */
      value = 1200;	/* --> subs.  */
      break;
    case 1404:	/* autibsp */
    case 1403:	/* autibz */
    case 1402:	/* autiasp */
    case 1401:	/* autiaz */
    case 1400:	/* pacibsp */
    case 1399:	/* pacibz */
    case 1398:	/* paciasp */
    case 1397:	/* paciaz */
    case 1376:	/* tsb */
    case 1375:	/* psb */
    case 1374:	/* esb */
    case 1373:	/* autib1716 */
    case 1372:	/* autia1716 */
    case 1371:	/* pacib1716 */
    case 1370:	/* pacia1716 */
    case 1369:	/* xpaclri */
    case 1367:	/* sevl */
    case 1366:	/* sev */
    case 1365:	/* wfi */
    case 1364:	/* wfe */
    case 1363:	/* yield */
    case 1362:	/* bti */
    case 1361:	/* csdb */
    case 1360:	/* nop */
    case 1359:	/* hint */
      value = 1359;	/* --> hint.  */
      break;
    case 1381:	/* pssbb */
    case 1380:	/* ssbb */
    case 1379:	/* dfb */
    case 1378:	/* dsb */
      value = 1378;	/* --> dsb.  */
      break;
    case 1392:	/* cpp */
    case 1391:	/* dvp */
    case 1390:	/* cfp */
    case 1389:	/* tlbi */
    case 1388:	/* ic */
    case 1387:	/* dc */
    case 1386:	/* at */
    case 1385:	/* sys */
      value = 1385;	/* --> sys.  */
      break;
    case 2202:	/* bic */
    case 1452:	/* and */
      value = 1452;	/* --> and.  */
      break;
    case 1435:	/* mov */
    case 1454:	/* and */
      value = 1454;	/* --> and.  */
      break;
    case 1439:	/* movs */
    case 1455:	/* ands */
      value = 1455;	/* --> ands.  */
      break;
    case 2203:	/* cmple */
    case 1490:	/* cmpge */
      value = 1490;	/* --> cmpge.  */
      break;
    case 2206:	/* cmplt */
    case 1493:	/* cmpgt */
      value = 1493;	/* --> cmpgt.  */
      break;
    case 2204:	/* cmplo */
    case 1495:	/* cmphi */
      value = 1495;	/* --> cmphi.  */
      break;
    case 2205:	/* cmpls */
    case 1498:	/* cmphs */
      value = 1498;	/* --> cmphs.  */
      break;
    case 1432:	/* mov */
    case 1520:	/* cpy */
      value = 1520;	/* --> cpy.  */
      break;
    case 1434:	/* mov */
    case 1521:	/* cpy */
      value = 1521;	/* --> cpy.  */
      break;
    case 2213:	/* fmov */
    case 1437:	/* mov */
    case 1522:	/* cpy */
      value = 1522;	/* --> cpy.  */
      break;
    case 1427:	/* mov */
    case 1534:	/* dup */
      value = 1534;	/* --> dup.  */
      break;
    case 1429:	/* mov */
    case 1426:	/* mov */
    case 1535:	/* dup */
      value = 1535;	/* --> dup.  */
      break;
    case 2212:	/* fmov */
    case 1431:	/* mov */
    case 1536:	/* dup */
      value = 1536;	/* --> dup.  */
      break;
    case 1430:	/* mov */
    case 1537:	/* dupm */
      value = 1537;	/* --> dupm.  */
      break;
    case 2207:	/* eon */
    case 1539:	/* eor */
      value = 1539;	/* --> eor.  */
      break;
    case 1440:	/* not */
    case 1541:	/* eor */
      value = 1541;	/* --> eor.  */
      break;
    case 1441:	/* nots */
    case 1542:	/* eors */
      value = 1542;	/* --> eors.  */
      break;
    case 2208:	/* facle */
    case 1547:	/* facge */
      value = 1547;	/* --> facge.  */
      break;
    case 2209:	/* faclt */
    case 1548:	/* facgt */
      value = 1548;	/* --> facgt.  */
      break;
    case 2210:	/* fcmle */
    case 1561:	/* fcmge */
      value = 1561;	/* --> fcmge.  */
      break;
    case 2211:	/* fcmlt */
    case 1563:	/* fcmgt */
      value = 1563;	/* --> fcmgt.  */
      break;
    case 1424:	/* fmov */
    case 1569:	/* fcpy */
      value = 1569;	/* --> fcpy.  */
      break;
    case 1423:	/* fmov */
    case 1592:	/* fdup */
      value = 1592;	/* --> fdup.  */
      break;
    case 1425:	/* mov */
    case 1923:	/* orr */
      value = 1923;	/* --> orr.  */
      break;
    case 2214:	/* orn */
    case 1924:	/* orr */
      value = 1924;	/* --> orr.  */
      break;
    case 1428:	/* mov */
    case 1926:	/* orr */
      value = 1926;	/* --> orr.  */
      break;
    case 1438:	/* movs */
    case 1927:	/* orrs */
      value = 1927;	/* --> orrs.  */
      break;
    case 1433:	/* mov */
    case 1989:	/* sel */
      value = 1989;	/* --> sel.  */
      break;
    case 1436:	/* mov */
    case 1990:	/* sel */
      value = 1990;	/* --> sel.  */
      break;
    default: return NULL;
    }

  return aarch64_opcode_table + value;
}

bfd_boolean
aarch64_insert_operand (const aarch64_operand *self,
			   const aarch64_opnd_info *info,
			   aarch64_insn *code, const aarch64_inst *inst,
			   aarch64_operand_error *errors)
{
  /* Use the index as the key.  */
  int key = self - aarch64_operands;
  switch (key)
    {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 17:
    case 18:
    case 19:
    case 20:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 166:
    case 167:
    case 168:
    case 169:
    case 170:
    case 171:
    case 172:
    case 173:
    case 174:
    case 175:
    case 190:
    case 191:
    case 192:
    case 193:
    case 194:
    case 195:
    case 196:
    case 197:
    case 198:
    case 204:
    case 207:
    case 211:
    case 212:
    case 213:
    case 214:
    case 215:
    case 216:
    case 217:
    case 218:
    case 219:
      return aarch64_ins_regno (self, info, code, inst, errors);
    case 15:
    case 223:
      return aarch64_ins_reg_extended (self, info, code, inst, errors);
    case 16:
      return aarch64_ins_reg_shifted (self, info, code, inst, errors);
    case 21:
      return aarch64_ins_ft (self, info, code, inst, errors);
    case 33:
    case 34:
    case 35:
    case 36:
    case 210:
      return aarch64_ins_reglane (self, info, code, inst, errors);
    case 37:
      return aarch64_ins_reglist (self, info, code, inst, errors);
    case 38:
      return aarch64_ins_ldst_reglist (self, info, code, inst, errors);
    case 39:
      return aarch64_ins_ldst_reglist_r (self, info, code, inst, errors);
    case 40:
      return aarch64_ins_ldst_elemlist (self, info, code, inst, errors);
    case 41:
    case 42:
    case 43:
    case 44:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 163:
    case 165:
    case 182:
    case 183:
    case 184:
    case 185:
    case 186:
    case 187:
    case 188:
    case 189:
    case 209:
    case 227:
    case 235:
    case 239:
      return aarch64_ins_imm (self, info, code, inst, errors);
    case 45:
    case 46:
      return aarch64_ins_advsimd_imm_shift (self, info, code, inst, errors);
    case 47:
    case 48:
    case 49:
      return aarch64_ins_advsimd_imm_modified (self, info, code, inst, errors);
    case 53:
    case 153:
      return aarch64_ins_fpimm (self, info, code, inst, errors);
    case 71:
    case 161:
      return aarch64_ins_limm (self, info, code, inst, errors);
    case 72:
    case 226:
    case 228:
      return aarch64_ins_aimm (self, info, code, inst, errors);
    case 73:
      return aarch64_ins_imm_half (self, info, code, inst, errors);
    case 74:
      return aarch64_ins_fbits (self, info, code, inst, errors);
    case 76:
    case 77:
    case 158:
      return aarch64_ins_imm_rotate2 (self, info, code, inst, errors);
    case 78:
    case 157:
    case 159:
      return aarch64_ins_imm_rotate1 (self, info, code, inst, errors);
    case 79:
    case 80:
      return aarch64_ins_cond (self, info, code, inst, errors);
    case 86:
    case 95:
    case 232:
      return aarch64_ins_addr_simple (self, info, code, inst, errors);
    case 87:
    case 237:
      return aarch64_ins_addr_regoff (self, info, code, inst, errors);
    case 88:
    case 89:
    case 90:
    case 92:
    case 94:
    case 231:
    case 233:
    case 234:
    case 238:
      return aarch64_ins_addr_simm (self, info, code, inst, errors);
    case 91:
      return aarch64_ins_addr_simm10 (self, info, code, inst, errors);
    case 93:
    case 236:
      return aarch64_ins_addr_uimm (self, info, code, inst, errors);
    case 96:
      return aarch64_ins_addr_offset (self, info, code, inst, errors);
    case 97:
      return aarch64_ins_simd_addr_post (self, info, code, inst, errors);
    case 98:
      return aarch64_ins_sysreg (self, info, code, inst, errors);
    case 99:
      return aarch64_ins_pstatefield (self, info, code, inst, errors);
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
      return aarch64_ins_sysins_op (self, info, code, inst, errors);
    case 105:
    case 106:
      return aarch64_ins_barrier (self, info, code, inst, errors);
    case 107:
      return aarch64_ins_prfop (self, info, code, inst, errors);
    case 108:
      return aarch64_ins_none (self, info, code, inst, errors);
    case 109:
      return aarch64_ins_hint (self, info, code, inst, errors);
    case 110:
    case 111:
      return aarch64_ins_sve_addr_ri_s4 (self, info, code, inst, errors);
    case 112:
    case 113:
    case 114:
    case 115:
      return aarch64_ins_sve_addr_ri_s4xvl (self, info, code, inst, errors);
    case 116:
      return aarch64_ins_sve_addr_ri_s6xvl (self, info, code, inst, errors);
    case 117:
      return aarch64_ins_sve_addr_ri_s9xvl (self, info, code, inst, errors);
    case 118:
    case 119:
    case 120:
    case 121:
      return aarch64_ins_sve_addr_ri_u6 (self, info, code, inst, errors);
    case 122:
    case 123:
    case 124:
    case 125:
    case 126:
    case 127:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
      return aarch64_ins_sve_addr_rr_lsl (self, info, code, inst, errors);
    case 136:
    case 137:
    case 138:
    case 139:
    case 140:
    case 141:
    case 142:
    case 143:
      return aarch64_ins_sve_addr_rz_xtw (self, info, code, inst, errors);
    case 144:
    case 145:
    case 146:
    case 147:
      return aarch64_ins_sve_addr_zi_u5 (self, info, code, inst, errors);
    case 148:
      return aarch64_ins_sve_addr_zz_lsl (self, info, code, inst, errors);
    case 149:
      return aarch64_ins_sve_addr_zz_sxtw (self, info, code, inst, errors);
    case 150:
      return aarch64_ins_sve_addr_zz_uxtw (self, info, code, inst, errors);
    case 151:
      return aarch64_ins_sve_aimm (self, info, code, inst, errors);
    case 152:
      return aarch64_ins_sve_asimm (self, info, code, inst, errors);
    case 154:
      return aarch64_ins_sve_float_half_one (self, info, code, inst, errors);
    case 155:
      return aarch64_ins_sve_float_half_two (self, info, code, inst, errors);
    case 156:
      return aarch64_ins_sve_float_zero_one (self, info, code, inst, errors);
    case 160:
      return aarch64_ins_inv_limm (self, info, code, inst, errors);
    case 162:
      return aarch64_ins_sve_limm_mov (self, info, code, inst, errors);
    case 164:
      return aarch64_ins_sve_scale (self, info, code, inst, errors);
    case 176:
    case 177:
    case 178:
      return aarch64_ins_sve_shlimm (self, info, code, inst, errors);
    case 179:
    case 180:
    case 181:
      return aarch64_ins_sve_shrimm (self, info, code, inst, errors);
    case 199:
    case 200:
    case 201:
    case 202:
    case 203:
      return aarch64_ins_sve_quad_index (self, info, code, inst, errors);
    case 205:
      return aarch64_ins_sve_index (self, info, code, inst, errors);
    case 206:
    case 208:
      return aarch64_ins_sve_reglist (self, info, code, inst, errors);
    case 220:
    case 221:
      return aarch64_ins_regsz (self, info, code, inst, errors);
    case 222:
      return aarch64_ins_fregsz (self, info, code, inst, errors);
    case 229:
      return aarch64_ins_perm (self, info, code, inst, errors);
    case 230:
      return aarch64_ins_form (self, info, code, inst, errors);
    default: assert (0); abort ();
    }
}
