/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2025 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

extern const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_t2rpntlvwz0 0x1c
#define MN_xsha1 0x28
#define MN_fld1 0x2e
#define MN_ud1 0x33
#define MN_sha1msg1 0x37
#define MN_vsha512msg1 0x40
#define MN_vsm3msg1 0x4c
#define MN_sha256msg1 0x55
#define MN_fprem1 0x60
#define MN_f2xm1 0x67
#define MN_fyl2xp1 0x6d
#define MN_t2rpntlvwz0t1 0x75
#define MN_t2rpntlvwz1t1 0x83
#define MN_tileloaddt1 0x91
#define MN_prefetcht1 0x9d
#define MN_prefetchit1 0xa8
#define MN_pfrcpit1 0xb4
#define MN_pfrsqit1 0xbd
#define MN_int1 0xc6
#define MN_t2rpntlvwz0rst1 0xcb
#define MN_t2rpntlvwz1rst1 0xdb
#define MN_tileloaddrst1 0xeb
#define MN_prefetchwt1 0xf9
#define MN_t2rpntlvwz1 0x105
#define MN_xsha512 0x111
#define MN_vmovdqa32 0x119
#define MN_data32 0x123
#define MN_crc32 0x12a
#define MN_endbr32 0x130
#define MN_addr32 0x138
#define MN_vmovdqu32 0x13f
#define MN_ud2 0x149
#define MN_fldlg2 0x14d
#define MN_xrng2 0x154
#define MN_sha1msg2 0x15a
#define MN_vsha512msg2 0x163
#define MN_vsm3msg2 0x16f
#define MN_sha256msg2 0x178
#define MN_push2 0x183
#define MN_sm2 0x189
#define MN_fldln2 0x18d
#define MN_pop2 0x194
#define MN_vsha512rnds2 0x199
#define MN_vsm3rnds2 0x1a6
#define MN_sha256rnds2 0x1b0
#define MN_prefetcht2 0x1bc
#define MN_pfrcpit2 0x1c7
#define MN_prefetchrst2 0x1d0
#define MN_vbroadcastf32x2 0x1dd
#define MN_vbroadcasti32x2 0x1ed
#define MN_vshuff64x2 0x1fd
#define MN_vextractf64x2 0x208
#define MN_vinsertf64x2 0x216
#define MN_vbroadcastf64x2 0x223
#define MN_vshufi64x2 0x233
#define MN_vextracti64x2 0x23e
#define MN_vinserti64x2 0x24c
#define MN_vbroadcasti64x2 0x259
#define MN_sm3 0x269
#define MN_int3 0x26d
#define MN_vmovdqa64 0x272
#define MN_xsavec64 0x27c
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x285
#define MN_endbr64 0x28e
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x296
#define MN_xsaves64 0x2a0
#define MN_xrstors64 0x2a9
#define MN_xsaveopt64 0x2b3
#define MN_vmovdqu64 0x2be
#define MN_rex64 0x2c8
#define MN_xsha384 0x2ce
#define MN_sm4 0x2d6
#define MN_sha1rnds4 0x2da
#define MN_vsm4rnds4 0x2e4
#define MN_vshuff32x4 0x2ee
#define MN_vextractf32x4 0x2f9
#define MN_vinsertf32x4 0x307
#define MN_vbroadcastf32x4 0x314
#define MN_vshufi32x4 0x324
#define MN_vextracti32x4 0x32f
#define MN_vinserti32x4 0x33d
#define MN_vbroadcasti32x4 0x34a
#define MN_vextractf64x4 0x35a
#define MN_vinsertf64x4 0x368
#define MN_vbroadcastf64x4 0x375
#define MN_vextracti64x4 0x385
#define MN_vinserti64x4 0x393
#define MN_vbroadcasti64x4 0x3a0
#define MN_vsm4key4 0x3b0
#define MN_data16 0x3b9
#define MN_vfmsub231bf16 0x3c0
#define MN_vfnmsub231bf16 0x3ce
#define MN_vfmadd231bf16 0x3dd
#define MN_vfnmadd231bf16 0x3eb
#define MN_vfmsub132bf16 0x3fa
#define MN_vfnmsub132bf16 0x408
#define MN_vfmadd132bf16 0x417
#define MN_vfnmadd132bf16 0x425
#define MN_vcvtne2ps2bf16 0x434
#define MN_vcvtneps2bf16 0x443
#define MN_vfmsub213bf16 0x451
#define MN_vfnmsub213bf16 0x45f
#define MN_vfmadd213bf16 0x46e
#define MN_vfnmadd213bf16 0x47c
#define MN_vsubbf16 0x48b
#define MN_vaddbf16 0x494
#define MN_vreducebf16 0x49d
#define MN_vrndscalebf16 0x4a9
#define MN_vscalefbf16 0x4b7
#define MN_vmulbf16 0x4c3
#define MN_vminbf16 0x4cc
#define MN_vrcpbf16 0x4d5
#define MN_vcmpbf16 0x4de
#define MN_vgetexpbf16 0x4e7
#define MN_vcomisbf16 0x4f3
#define MN_vfpclassbf16 0x4fe
#define MN_vgetmantbf16 0x50b
#define MN_vrsqrtbf16 0x518
#define MN_vsqrtbf16 0x523
#define MN_vdivbf16 0x52d
#define MN_vminmaxbf16 0x536
#define MN_vmaxbf16 0x542
#define MN_tconjtfp16 0x54b
#define MN_addr16 0x556
#define MN_vmovdqu16 0x55d
#define MN_xsha256 0x567
#define MN_encodekey256 0x56f
#define MN_vperm2f128 0x57c
#define MN_vextractf128 0x587
#define MN_vinsertf128 0x594
#define MN_vbroadcastf128 0x5a0
#define MN_vperm2i128 0x5af
#define MN_vextracti128 0x5ba
#define MN_vinserti128 0x5c7
#define MN_vbroadcasti128 0x5d3
#define MN_encodekey128 0x5e2
#define MN_vcvt2ph2bf8 0x5ef
#define MN_vcvtbiasph2bf8 0x5fb
#define MN_vcvtph2bf8 0x60a
#define MN_vcvt2ph2hf8 0x615
#define MN_vcvtbiasph2hf8 0x621
#define MN_vcvtph2hf8 0x630
#define MN_vmovdqu8 0x63b
#define MN_vextractf32x8 0x644
#define MN_vinsertf32x8 0x652
#define MN_vbroadcastf32x8 0x65f
#define MN_vextracti32x8 0x66f
#define MN_vinserti32x8 0x67d
#define MN_vbroadcasti32x8 0x68a
#define MN_ud2a 0x69a
#define MN_aaa 0x69f
#define MN_daa 0x6a3
#define MN_ssca 0x6a7
#define MN_lea 0x6ac
#define MN_invlpga 0x6b0
#define MN_pusha 0x6b8
#define MN_ja 0x6be
#define MN_jna 0x6c1
#define MN_ccmpna 0x6c5
#define MN_setna 0x6cc
#define MN_ctestna 0x6d2
#define MN_setzuna 0x6da
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna (MN_cfcmovna + 1)
#define MN_cfcmovna 0x6e2
#define MN_ccmpa 0x6eb
#define MN_popa 0x6f1
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x6f6
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x700
#define MN_seta 0x708
#define MN_prefetchnta 0x70d
#define MN_ctesta 0x719
#define MN_setzua 0x720
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova (MN_cfcmova + 1)
#define MN_cfcmova 0x727
#define MN_rex_b 0x72f
#define MN_ud2b 0x735
#define MN_vpermi2b 0x73a
#define MN_vpmovm2b 0x743
#define MN_vpermt2b 0x74c
#define MN_movdir64b 0x755
#define MN_cmpxchg16b 0x75f
#define MN_cmpxchg8b 0x76a
#define MN_vpshab 0x774
#define MN_sbb 0x77b
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x77f
#define MN_xcrypt_ecb 0x786
#define MN_xcryptecb 0x791
#define MN_llwpcb 0x79b
#define MN_slwpcb 0x7a2
#define MN_kaddb 0x7a9
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x7af
#define MN_kandb 0x7b6
#define MN_vpexpandb 0x7bc
#define MN_vpmovusdb 0x7c6
#define MN_vpmovsdb 0x7d0
#define MN_vpmovdb 0x7d9
#define MN_vpcomgeb 0x7e1
#define MN_vpcomleb 0x7ea
#define MN_vpcmpnleb 0x7f3
#define MN_vpcmpleb 0x7fd
#define MN_vpcomfalseb 0x806
#define MN_vpcomtrueb 0x812
#define MN_xcrypt_cfb 0x81d
#define MN_xcryptcfb 0x828
#define MN_xcrypt_ofb 0x832
#define MN_xcryptofb 0x83d
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x847
#define MN_invlpgb 0x84f
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x857
#define MN_jb 0x85e
#define MN_pbndkb 0x861
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x868
#define MN_vpshlb 0x872
#define MN_kshiftlb 0x879
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x882
#define MN_vpblendmb 0x88d
#define MN_vptestnmb 0x897
#define MN_vpcomb 0x8a1
#define MN_vpshufbitqmb 0x8a8
#define MN_vpermb 0x8b5
#define MN_vptestmb 0x8bc
#define MN_kandnb 0x8c5
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x8cc
#define MN_jnb 0x8d4
#define MN_ccmpnb 0x8d8
#define MN_setnb 0x8df
#define MN_ctestnb 0x8e5
#define MN_setzunb 0x8ed
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb (MN_cfcmovnb + 1)
#define MN_cfcmovnb 0x8f5
#define MN_ccmpb 0x8fe
#define MN_vpcmpb 0x904
#define MN_vpcomeqb 0x90b
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x914
#define MN_vpcomneqb 0x923
#define MN_vpcmpneqb 0x92d
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x937
#define MN_vpmovusqb 0x940
#define MN_vpmovsqb 0x94a
#define MN_vpmultishiftqb 0x953
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0x962
#define MN_vpmovqb 0x974
#define MN_rex_rb 0x97c
#define MN_korb 0x983
#define MN_kxnorb 0x988
#define MN_kxorb 0x98f
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0x995
#define MN_kshiftrb 0x99d
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0x9a6
#define MN_rex_wrb 0x9ae
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0x9b6
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0x9bd
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0x9c5
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0x9cd
#define MN_vmovrsb 0x9d5
#define MN_vpcompressb 0x9dd
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0x9e9
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0x9f2
#define MN_pavgusb 0x9fb
#define MN_movsb 0xa03
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0xa09
#define MN_setb 0xa11
#define MN_vpcomgtb 0xa16
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0xa1f
#define MN_vpcomltb 0xa28
#define MN_vpcmpnltb 0xa31
#define MN_vpcmpltb 0xa3b
#define MN_vpopcntb 0xa44
#define MN_knotb 0xa4d
#define MN_vprotb 0xa53
#define MN_vpbroadcastb 0xa5a
#define MN_ctestb 0xa67
#define MN_ktestb 0xa6e
#define MN_kortestb 0xa75
#define MN_vpcomgeub 0xa7e
#define MN_vpcomleub 0xa88
#define MN_vpcmpnleub 0xa92
#define MN_vpcmpleub 0xa9d
#define MN_vpcomfalseub 0xaa7
#define MN_vpcomtrueub 0xab4
#define MN_vpcomub 0xac0
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0xac8
#define MN_vpcmpub 0xad0
#define MN_vpcomequb 0xad8
#define MN_vpcomnequb 0xae2
#define MN_vpcmpnequb 0xaed
#define MN_vpcmpequb 0xaf8
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0xb02
#define MN_fisub 0xb08
#define MN_vpcomgtub 0xb0e
#define MN_vpcomltub 0xb18
#define MN_vpcmpnltub 0xb22
#define MN_vpcmpltub 0xb2d
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0xb37
#define MN_setzub 0xb3f
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0xb46
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb (MN_cfcmovb + 1)
#define MN_cfcmovb 0xb50
#define MN_kmovb 0xb58
#define MN_rex_wb 0xb5e
#define MN_clwb 0xb65
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0xb6a
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0xb74
#define MN_vpmovuswb 0xb7e
#define MN_vpmovswb 0xb88
#define MN_vpmovwb 0xb91
#define MN_rex_xb 0xb99
#define MN_rex_rxb 0xba0
#define MN_rex_wrxb 0xba8
#define MN_rex_wxb 0xbb1
#define MN_movzb 0xbb9
#define MN_clac 0xbbf
#define MN_stac 0xbc4
#define MN_xcrypt_cbc 0xbc9
#define MN_xcryptcbc 0xbd4
#define MN_pfacc 0xbde
#define MN_pfnacc 0xbe4
#define MN_pfpnacc 0xbeb
#define MN_adc 0xbf3
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0xbf7
#define MN_getsec 0xbff
#define MN_xsavec 0xc06
#define MN_blcic 0xc0d
#define MN_blsic 0xc13
#define MN_jc 0xc19
#define MN_t1mskc 0xc1c
#define MN_clc 0xc23
#define MN_cmc 0xc27
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0xc2b
#define MN_rdpmc 0xc33
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0xc39
#define MN_inc 0xc41
#define MN_jnc 0xc45
#define MN_ccmpnc 0xc49
#define MN_setnc 0xc50
#define MN_ctestnc 0xc56
#define MN_vmfunc 0xc5e
#define MN_setzunc 0xc65
#define MN_cmovnc (MN_cfcmovnc + 2)
#define MN_cfcmovnc 0xc6d
#define MN_tlbsync 0xc76
#define MN_ccmpc 0xc7e
#define MN_rdtsc 0xc84
#define MN_btc 0xc8a
#define MN_setc 0xc8e
#define MN_stc (MN_ctestc + 3)
#define MN_ctestc 0xc93
#define MN_setzuc 0xc9a
#define MN_cmovc (MN_cfcmovc + 2)
#define MN_cfcmovc 0xca1
#define MN_vpermi2d 0xca9
#define MN_vpmovm2d 0xcb2
#define MN_vpermt2d 0xcbb
#define MN_vpbroadcastmw2d 0xcc4
#define MN_aad 0xcd4
#define MN_vmread 0xcd8
#define MN_vpshad 0xcdf
#define MN_vmload 0xce6
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0xced
#define MN_vphaddbd 0xcf4
#define MN_vphaddubd 0xcfd
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0xd07
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0xd0f
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0xd16
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0xd20
#define MN_add (MN_aadd + 1)
#define MN_aadd 0xd2a
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0xd2f
#define MN_fiadd 0xd35
#define MN_tileloadd 0xd3b
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0xd45
#define MN_cmpaxadd 0xd4f
#define MN_cmpnbxadd 0xd58
#define MN_cmpbxadd 0xd62
#define MN_cmpncxadd 0xd6b
#define MN_cmpcxadd 0xd75
#define MN_cmpnaexadd 0xd7e
#define MN_cmpaexadd 0xd89
#define MN_cmpnbexadd 0xd93
#define MN_cmpbexadd 0xd9e
#define MN_cmpngexadd 0xda8
#define MN_cmpgexadd 0xdb3
#define MN_cmpnlexadd 0xdbd
#define MN_cmplexadd 0xdc8
#define MN_cmpnexadd 0xdd2
#define MN_cmpexadd 0xddc
#define MN_cmppexadd 0xde5
#define MN_cmpngxadd 0xdef
#define MN_cmpgxadd 0xdf9
#define MN_cmpnlxadd 0xe02
#define MN_cmplxadd 0xe0c
#define MN_cmpnoxadd 0xe15
#define MN_cmpoxadd 0xe1f
#define MN_cmppoxadd 0xe28
#define MN_cmpnpxadd 0xe32
#define MN_cmppxadd 0xe3c
#define MN_cmpnsxadd 0xe45
#define MN_cmpsxadd 0xe4f
#define MN_cmpnzxadd 0xe58
#define MN_cmpzxadd 0xe62
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xe6b
#define MN_kaddd 0xe73
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xe79
#define MN_vpshldd 0xe80
#define MN_kandd 0xe88
#define MN_vpandd 0xe8e
#define MN_vpexpandd 0xe95
#define MN_vpblendd 0xe9f
#define MN_vpgatherdd 0xea8
#define MN_vpscatterdd 0xeb3
#define MN_vpshrdd 0xebf
#define MN_vpmacsdd 0xec7
#define MN_vpmacssdd 0xed0
#define MN_rdseed 0xeda
#define MN_vpcomged 0xee1
#define MN_vpcomled 0xeea
#define MN_vpcmpnled 0xef3
#define MN_vpcmpled 0xefd
#define MN_tilestored 0xf06
#define MN_vpcomfalsed 0xf11
#define MN_ttransposed 0xf1d
#define MN_vpcomtrued 0xf29
#define MN_pi2fd 0xf34
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xf3a
#define MN_vpternlogd 0xf42
#define MN_pf2id 0xf4d
#define MN_invpcid 0xf53
#define MN_rdpid 0xf5b
#define MN_invvpid 0xf61
#define MN_cpuid 0xf69
#define MN_fbld 0xf6f
#define MN_cld 0xf74
#define MN_fld 0xf78
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0xf7c
#define MN_fild 0xf83
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0xf88
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0xf8f
#define MN_vprold 0xf97
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0xf9e
#define MN_vmptrld 0xfa5
#define MN_kshiftld 0xfad
#define MN_enqcmd 0xfb6
#define MN_vpblendmd 0xfbd
#define MN_vptestnmd 0xfc7
#define MN_vpcomd 0xfd1
#define MN_vpermd 0xfd8
#define MN_vptestmd 0xfdf
#define MN_and (MN_aand + 1)
#define MN_aand 0xfe8
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0xfed
#define MN_rdrand 0xff3
#define MN_bnd 0xffa
#define MN_kandnd 0xffe
#define MN_vpandnd 0x1005
#define MN_xend 0x100d
#define MN_valignd 0x1012
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0x101a
#define MN_bound 0x1022
#define MN_slod 0x1028
#define MN_vfmaddsub231pd 0x102d
#define MN_vfmsub231pd 0x103c
#define MN_vfnmsub231pd 0x1048
#define MN_vfmsubadd231pd 0x1055
#define MN_vfmadd231pd 0x1064
#define MN_vfnmadd231pd 0x1070
#define MN_vfmaddsub132pd 0x107d
#define MN_vfmsub132pd 0x108c
#define MN_vfnmsub132pd 0x1098
#define MN_vfmsubadd132pd 0x10a5
#define MN_vfmadd132pd 0x10b4
#define MN_vfnmadd132pd 0x10c0
#define MN_vcvtph2pd 0x10cd
#define MN_vpermi2pd 0x10d7
#define MN_cvtpi2pd 0x10e1
#define MN_vpermil2pd 0x10ea
#define MN_vexp2pd 0x10f5
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0x10fd
#define MN_vcvtudq2pd 0x1107
#define MN_vcvtqq2pd 0x1112
#define MN_vcvtuqq2pd 0x111c
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0x1127
#define MN_vpermt2pd 0x1131
#define MN_vfmaddsub213pd 0x113b
#define MN_vfmsub213pd 0x114a
#define MN_vfnmsub213pd 0x1156
#define MN_vfmsubadd213pd 0x1163
#define MN_vfmadd213pd 0x1172
#define MN_vfnmadd213pd 0x117e
#define MN_vrcp14pd 0x118b
#define MN_vrsqrt14pd 0x1194
#define MN_vrcp28pd 0x119f
#define MN_vrsqrt28pd 0x11a8
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0x11b3
#define MN_pswapd 0x11bb
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0x11c2
#define MN_vaddsubpd 0x11ce
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0x11d8
#define MN_vfmsubpd 0x11e0
#define MN_vfnmsubpd 0x11e9
#define MN_vsubpd 0x11f3
#define MN_vgatherpf0dpd 0x11fa
#define MN_vscatterpf0dpd 0x1208
#define MN_vgatherpf1dpd 0x1217
#define MN_vscatterpf1dpd 0x1225
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0x1234
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0x1240
#define MN_vfmaddpd 0x1248
#define MN_vfnmaddpd 0x1251
#define MN_vaddpd 0x125b
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0x1262
#define MN_vandpd 0x126c
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0x1273
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0x127c
#define MN_vgatherdpd 0x1285
#define MN_vscatterdpd 0x1290
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0x129c
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0x12a8
#define MN_vreducepd 0x12b2
#define MN_vrangepd 0x12bc
#define MN_vcmpngepd 0x12c5
#define MN_vcmpgepd 0x12cf
#define MN_vrndscalepd 0x12d8
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0x12e4
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0x12ee
#define MN_vcmpfalsepd 0x12f7
#define MN_vcmptruepd 0x1303
#define MN_vscalefpd 0x130e
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0x1318
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0x1320
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0x132a
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0x1332
#define MN_vpermilpd 0x133c
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0x1346
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0x1350
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x1357
#define MN_vpcmpd 0x135f
#define MN_vblendmpd 0x1366
#define MN_vfixupimmpd 0x1370
#define MN_vpermpd 0x137c
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x1384
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x138c
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x1393
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x1399
#define MN_vgetexppd 0x13a0
#define MN_vgatherpf0qpd 0x13aa
#define MN_vscatterpf0qpd 0x13b8
#define MN_vgatherpf1qpd 0x13c7
#define MN_vscatterpf1qpd 0x13d5
#define MN_vcmpunord_qpd 0x13e4
#define MN_vcmpord_qpd 0x13f2
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x13fe
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x1408
#define MN_vcmpge_oqpd 0x1411
#define MN_vcmple_oqpd 0x141d
#define MN_vcmpfalse_oqpd 0x1429
#define MN_vcmpneq_oqpd 0x1438
#define MN_vcmpeq_oqpd 0x1445
#define MN_vcmpgt_oqpd 0x1451
#define MN_vcmplt_oqpd 0x145d
#define MN_vgatherqpd 0x1469
#define MN_vscatterqpd 0x1474
#define MN_vcmpnge_uqpd 0x1480
#define MN_vcmpnle_uqpd 0x148d
#define MN_vcmptrue_uqpd 0x149a
#define MN_vcmpneq_uqpd 0x14a8
#define MN_vcmpeq_uqpd 0x14b5
#define MN_vcmpngt_uqpd 0x14c1
#define MN_vcmpnlt_uqpd 0x14ce
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x14db
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x14e1
#define MN_vcmpunord_spd 0x14e8
#define MN_vcmpord_spd 0x14f6
#define MN_vcmpge_ospd 0x1502
#define MN_vcmple_ospd 0x150e
#define MN_vcmpfalse_ospd 0x151a
#define MN_vcmpneq_ospd 0x1529
#define MN_vcmpeq_ospd 0x1536
#define MN_vcmpgt_ospd 0x1542
#define MN_vcmplt_ospd 0x154e
#define MN_vfpclasspd 0x155a
#define MN_incsspd 0x1565
#define MN_rdsspd 0x156d
#define MN_vcompresspd 0x1574
#define MN_vcmpnge_uspd 0x1580
#define MN_vcmpnle_uspd 0x158d
#define MN_vcmptrue_uspd 0x159a
#define MN_vcmpneq_uspd 0x15a8
#define MN_vcmpeq_uspd 0x15b5
#define MN_vcmpngt_uspd 0x15c1
#define MN_vcmpnlt_uspd 0x15ce
#define MN_vcmpngtpd 0x15db
#define MN_vcmpgtpd 0x15e5
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x15ee
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x15f8
#define MN_vgetmantpd 0x1601
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x160c
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x1615
#define MN_vtestpd 0x161d
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x1625
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x162d
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x1637
#define MN_vmaskmovpd 0x163e
#define MN_maxpd (MN_vminmaxpd + 4)
#define MN_vminmaxpd 0x1649
#define MN_vmaxpd 0x1653
#define MN_vfrczpd 0x165a
#define MN_vpcomeqd 0x1662
#define MN_vpcomneqd 0x166b
#define MN_vpcmpneqd 0x1675
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x167f
#define MN_vpgatherqd 0x1688
#define MN_vpscatterqd 0x1693
#define MN_vpmovusqd 0x169f
#define MN_vpmovsqd 0x16a9
#define MN_vpmovqd 0x16b2
#define MN_shrd 0x16ba
#define MN_kord 0x16bf
#define MN_kxnord 0x16c4
#define MN_vpord 0x16cb
#define MN_vprord 0x16d1
#define MN_word (MN_aword + 1)
#define MN_aword 0x16d8
#define MN_dword (MN_adword + 1)
#define MN_adword 0x16de
#define MN_kxord 0x16e5
#define MN_vpxord 0x16eb
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x16f2
#define MN_kshiftrd 0x16fa
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x1703
#define MN_vfmsub231sd 0x170b
#define MN_vfnmsub231sd 0x1717
#define MN_vfmadd231sd 0x1724
#define MN_vfnmadd231sd 0x1730
#define MN_vfmsub132sd 0x173d
#define MN_vfnmsub132sd 0x1749
#define MN_vfmadd132sd 0x1756
#define MN_vfnmadd132sd 0x1762
#define MN_vcvtsh2sd 0x176f
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x1779
#define MN_vcvtusi2sd 0x1783
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x178e
#define MN_vfmsub213sd 0x1798
#define MN_vfnmsub213sd 0x17a4
#define MN_vfmadd213sd 0x17b1
#define MN_vfnmadd213sd 0x17bd
#define MN_vrcp14sd 0x17ca
#define MN_vrsqrt14sd 0x17d3
#define MN_vrcp28sd 0x17de
#define MN_vrsqrt28sd 0x17e7
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x17f2
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x17f9
#define MN_vfnmsubsd 0x1802
#define MN_vsubsd 0x180c
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x1813
#define MN_vfnmaddsd 0x181c
#define MN_vaddsd 0x1826
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x182d
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x1836
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x1842
#define MN_vreducesd 0x184c
#define MN_vrangesd 0x1856
#define MN_vcmpngesd 0x185f
#define MN_vcmpgesd 0x1869
#define MN_vrndscalesd 0x1872
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x187e
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x1888
#define MN_vcmpfalsesd 0x1891
#define MN_vcmptruesd 0x189d
#define MN_vscalefsd 0x18a8
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x18b2
#define MN_vcomisd 0x18bb
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x18c3
#define MN_vfixupimmsd 0x18ca
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x18d6
#define MN_vminsd 0x18de
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x18e5
#define MN_vgetexpsd 0x18ec
#define MN_vcmpunord_qsd 0x18f6
#define MN_vcmpord_qsd 0x1904
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x1910
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x191a
#define MN_vcmpge_oqsd 0x1923
#define MN_vcmple_oqsd 0x192f
#define MN_vcmpfalse_oqsd 0x193b
#define MN_vcmpneq_oqsd 0x194a
#define MN_vcmpeq_oqsd 0x1957
#define MN_vcmpgt_oqsd 0x1963
#define MN_vcmplt_oqsd 0x196f
#define MN_vcmpnge_uqsd 0x197b
#define MN_vcmpnle_uqsd 0x1988
#define MN_vcmptrue_uqsd 0x1995
#define MN_vcmpneq_uqsd 0x19a3
#define MN_vcmpeq_uqsd 0x19b0
#define MN_vcmpngt_uqsd 0x19bc
#define MN_vcmpnlt_uqsd 0x19c9
#define MN_vmovrsd 0x19d6
#define MN_vcmpunord_ssd 0x19de
#define MN_vcmpord_ssd 0x19ec
#define MN_vpdpbssd 0x19f8
#define MN_tdpbssd 0x1a01
#define MN_vpcompressd 0x1a09
#define MN_vcmpge_ossd 0x1a15
#define MN_vcmple_ossd 0x1a21
#define MN_vcmpfalse_ossd 0x1a2d
#define MN_vcmpneq_ossd 0x1a3c
#define MN_vcmpeq_ossd 0x1a49
#define MN_vcmpgt_ossd 0x1a55
#define MN_vcmplt_ossd 0x1a61
#define MN_wrssd 0x1a6d
#define MN_vfpclasssd 0x1a73
#define MN_vcmpnge_ussd 0x1a7e
#define MN_vcmpnle_ussd 0x1a8b
#define MN_vcmptrue_ussd 0x1a98
#define MN_vcmpneq_ussd 0x1aa6
#define MN_vcmpeq_ussd 0x1ab3
#define MN_vcmpngt_ussd 0x1abf
#define MN_vcmpnlt_ussd 0x1acc
#define MN_wrussd 0x1ad9
#define MN_vp4dpwssd 0x1ae0
#define MN_vpdpwssd 0x1aea
#define MN_vcmpngtsd 0x1af3
#define MN_vcmpgtsd 0x1afd
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x1b06
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x1b10
#define MN_vgetmantsd 0x1b19
#define MN_movntsd 0x1b24
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x1b2c
#define MN_vbroadcastsd 0x1b34
#define MN_vpdpbusd 0x1b41
#define MN_tdpbusd 0x1b4a
#define MN_vpdpwusd 0x1b52
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x1b5b
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x1b62
#define MN_maxsd (MN_vminmaxsd + 4)
#define MN_vminmaxsd 0x1b69
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1b73
#define MN_vmaxsd 0x1b7b
#define MN_vucomxsd 0x1b82
#define MN_vcomxsd 0x1b8b
#define MN_vfrczsd 0x1b93
#define MN_vp2intersectd 0x1b9b
#define MN_vpconflictd 0x1ba9
#define MN_vpcomgtd 0x1bb5
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x1bbe
#define MN_cltd 0x1bc7
#define MN_vpcomltd 0x1bcc
#define MN_vpcmpnltd 0x1bd5
#define MN_vpcmpltd 0x1bdf
#define MN_vpopcntd 0x1be8
#define MN_vplzcntd 0x1bf1
#define MN_knotd 0x1bfa
#define MN_vprotd 0x1c00
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x1c07
#define MN_ktestd 0x1c14
#define MN_kortestd 0x1c1b
#define MN_cwtd 0x1c24
#define MN_vpcomgeud 0x1c29
#define MN_vpcomleud 0x1c33
#define MN_vpcmpnleud 0x1c3d
#define MN_vpcmpleud 0x1c48
#define MN_vpcomfalseud 0x1c52
#define MN_vpcomtrueud 0x1c5f
#define MN_vpcomud 0x1c6b
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x1c73
#define MN_vpcmpud 0x1c7b
#define MN_vpcomequd 0x1c83
#define MN_vpcomnequd 0x1c8d
#define MN_vpcmpnequd 0x1c98
#define MN_vpcmpequd 0x1ca3
#define MN_vpdpbsud 0x1cad
#define MN_tdpbsud 0x1cb6
#define MN_vpdpwsud 0x1cbe
#define MN_vpcomgtud 0x1cc7
#define MN_vpcomltud 0x1cd1
#define MN_vpcmpnltud 0x1cdb
#define MN_vpcmpltud 0x1ce6
#define MN_vpdpbuud 0x1cf0
#define MN_tdpbuud 0x1cf9
#define MN_vpdpwuud 0x1d01
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x1d0a
#define MN_vpsravd 0x1d12
#define MN_vpshldvd 0x1d1a
#define MN_vpshrdvd 0x1d23
#define MN_vpsllvd 0x1d2c
#define MN_vprolvd 0x1d34
#define MN_vpsrlvd 0x1d3c
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x1d44
#define MN_wbnoinvd 0x1d4b
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x1d54
#define MN_vmovd 0x1d5f
#define MN_vprorvd 0x1d65
#define MN_vphsubwd 0x1d6d
#define MN_cwd 0x1d76
#define MN_vphaddwd 0x1d7a
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1d83
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1d8c
#define MN_kunpckwd 0x1d97
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1da0
#define MN_vpmacswd 0x1dab
#define MN_vpmadcswd 0x1db4
#define MN_vpmacsswd 0x1dbe
#define MN_vpmadcsswd 0x1dc8
#define MN_vphadduwd 0x1dd3
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1ddd
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1de7
#define MN_movsxd 0x1df1
#define MN_fldl2e 0x1df8
#define MN_jae 0x1dff
#define MN_jnae 0x1e03
#define MN_ccmpnae 0x1e08
#define MN_setnae 0x1e10
#define MN_ctestnae 0x1e17
#define MN_setzunae 0x1e20
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae (MN_cfcmovnae + 1)
#define MN_cfcmovnae 0x1e29
#define MN_ccmpae 0x1e33
#define MN_setae 0x1e3a
#define MN_ctestae 0x1e40
#define MN_setzuae 0x1e48
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae (MN_cfcmovae + 1)
#define MN_cfcmovae 0x1e50
#define MN_jbe 0x1e59
#define MN_jnbe 0x1e5d
#define MN_ccmpnbe 0x1e62
#define MN_setnbe 0x1e6a
#define MN_ctestnbe 0x1e71
#define MN_setzunbe 0x1e7a
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe (MN_cfcmovnbe + 1)
#define MN_cfcmovnbe 0x1e83
#define MN_ccmpbe 0x1e8d
#define MN_setbe 0x1e94
#define MN_ctestbe 0x1e9a
#define MN_setzube 0x1ea2
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe (MN_cfcmovbe + 1)
#define MN_cfcmovbe 0x1eaa
#define MN_lfence 0x1eb3
#define MN_mfence 0x1eba
#define MN_sfence 0x1ec1
#define MN_cwde 0x1ec8
#define MN_ffree 0x1ecd
#define MN_jge 0x1ed3
#define MN_jnge 0x1ed7
#define MN_ccmpnge 0x1edc
#define MN_setnge 0x1ee4
#define MN_ctestnge 0x1eeb
#define MN_setzunge 0x1ef4
#define MN_cmovnge (MN_cfcmovnge + 2)
#define MN_cfcmovnge 0x1efd
#define MN_ccmpge 0x1f07
#define MN_pfcmpge 0x1f0e
#define MN_setge 0x1f16
#define MN_ctestge 0x1f1c
#define MN_setzuge 0x1f24
#define MN_cmovge (MN_cfcmovge + 2)
#define MN_cfcmovge 0x1f2c
#define MN_je 0x1f35
#define MN_fscale 0x1f38
#define MN_jle 0x1f3f
#define MN_jnle 0x1f43
#define MN_ccmpnle 0x1f48
#define MN_setnle 0x1f50
#define MN_ctestnle 0x1f57
#define MN_setzunle 0x1f60
#define MN_cmovnle (MN_cfcmovnle + 2)
#define MN_cfcmovnle 0x1f69
#define MN_ccmple 0x1f73
#define MN_setle 0x1f7a
#define MN_ctestle 0x1f80
#define MN_setzule 0x1f88
#define MN_cmovle (MN_cfcmovle + 2)
#define MN_cfcmovle 0x1f90
#define MN_vmresume 0x1f99
#define MN_jne 0x1fa2
#define MN_repne 0x1fa6
#define MN_ccmpne 0x1fac
#define MN_loopne 0x1fb3
#define MN_setne 0x1fba
#define MN_ctestne 0x1fc0
#define MN_setzune 0x1fc8
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne (MN_cfcmovne + 1)
#define MN_cfcmovne 0x1fd0
#define MN_repe 0x1fd9
#define MN_jpe 0x1fde
#define MN_ccmpe 0x1fe2
#define MN_loope 0x1fe8
#define MN_setpe 0x1fee
#define MN_setzupe 0x1ff4
#define MN_cmovpe (MN_cfcmovpe + 2)
#define MN_cfcmovpe 0x1ffc
#define MN_cdqe 0x2005
#define MN_xacquire 0x200a
#define MN_xstore 0x2013
#define MN_rdfsbase 0x201a
#define MN_wrfsbase 0x2023
#define MN_rdgsbase 0x202c
#define MN_wrgsbase 0x2035
#define MN_tilerelease 0x203e
#define MN_xrelease 0x204a
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x2053
#define MN_pvalidate 0x205a
#define MN_rmpupdate 0x2064
#define MN_sete 0x206e
#define MN_vmwrite 0x2073
#define MN_ptwrite 0x207b
#define MN_cldemote 0x2083
#define MN_cteste 0x208c
#define MN_sha1nexte 0x2093
#define MN_setzue 0x209d
#define MN_leave 0x20a4
#define MN_fsave 0x20aa
#define MN_vmsave 0x20b0
#define MN_fnsave 0x20b7
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x20be
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove (MN_cfcmove + 1)
#define MN_cfcmove 0x20c5
#define MN_serialize 0x20cd
#define MN_vmxoff 0x20d7
#define MN_lahf 0x20de
#define MN_sahf 0x20e3
#define MN_pushf 0x20e8
#define MN_ccmpf 0x20ee
#define MN_popf 0x20f4
#define MN_bsf 0x20f9
#define MN_retf 0x20fd
#define MN_ctestf 0x2102
#define MN_neg 0x2109
#define MN_ldtilecfg 0x210d
#define MN_sttilecfg 0x2117
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x2121
#define MN_pconfig 0x2129
#define MN_jg 0x2131
#define MN_jng 0x2134
#define MN_ccmpng 0x2138
#define MN_xstore_rng 0x213f
#define MN_xstorerng 0x214a
#define MN_setng 0x2154
#define MN_ctestng 0x215a
#define MN_setzung 0x2162
#define MN_cmovng (MN_cfcmovng + 2)
#define MN_cfcmovng 0x216a
#define MN_invlpg 0x2173
#define MN_ccmpg 0x217a
#define MN_setg 0x2180
#define MN_ctestg 0x2185
#define MN_setzug 0x218c
#define MN_cmovg (MN_cfcmovg + 2)
#define MN_cfcmovg 0x2193
#define MN_tcvtrowps2bf16h 0x219b
#define MN_vmlaunch 0x21ab
#define MN_prefetch 0x21b4
#define MN_fxch 0x21bd
#define MN_tcvtrowps2phh 0x21c2
#define MN_vfmaddsub231ph 0x21d0
#define MN_vfmsub231ph 0x21df
#define MN_vfnmsub231ph 0x21eb
#define MN_vfmsubadd231ph 0x21f8
#define MN_vfmadd231ph 0x2207
#define MN_vfnmadd231ph 0x2213
#define MN_vfmaddsub132ph 0x2220
#define MN_vfmsub132ph 0x222f
#define MN_vfnmsub132ph 0x223b
#define MN_vfmsubadd132ph 0x2248
#define MN_vfmadd132ph 0x2257
#define MN_vfnmadd132ph 0x2263
#define MN_vcvthf82ph 0x2270
#define MN_vcvtpd2ph 0x227b
#define MN_vcvtdq2ph 0x2285
#define MN_vcvtudq2ph 0x228f
#define MN_vcvtqq2ph 0x229a
#define MN_vcvtuqq2ph 0x22a4
#define MN_vcvtps2ph 0x22af
#define MN_vcvtw2ph 0x22b9
#define MN_vcvtuw2ph 0x22c2
#define MN_vfmaddsub213ph 0x22cc
#define MN_vfmsub213ph 0x22db
#define MN_vfnmsub213ph 0x22e7
#define MN_vfmsubadd213ph 0x22f4
#define MN_vfmadd213ph 0x2303
#define MN_vfnmadd213ph 0x230f
#define MN_vsubph 0x231c
#define MN_vfcmaddcph 0x2323
#define MN_vfmaddcph 0x232e
#define MN_vfcmulcph 0x2338
#define MN_vfmulcph 0x2342
#define MN_vaddph 0x234b
#define MN_vcmpunordph 0x2352
#define MN_vcmpordph 0x235e
#define MN_vreduceph 0x2368
#define MN_vcmpngeph 0x2372
#define MN_vcmpgeph 0x237c
#define MN_vrndscaleph 0x2385
#define MN_vcmpnleph 0x2391
#define MN_vcmpleph 0x239b
#define MN_vcmpfalseph 0x23a4
#define MN_vcmptrueph 0x23b0
#define MN_vscalefph 0x23bb
#define MN_vmulph 0x23c5
#define MN_vminph 0x23cc
#define MN_vrcpph 0x23d3
#define MN_vcmpph 0x23da
#define MN_vgetexpph 0x23e1
#define MN_vcmpunord_qph 0x23eb
#define MN_vcmpord_qph 0x23f9
#define MN_vcmpneqph 0x2405
#define MN_vcmpeqph 0x240f
#define MN_vcmpge_oqph 0x2418
#define MN_vcmple_oqph 0x2424
#define MN_vcmpfalse_oqph 0x2430
#define MN_vcmpneq_oqph 0x243f
#define MN_vcmpeq_oqph 0x244c
#define MN_vcmpgt_oqph 0x2458
#define MN_vcmplt_oqph 0x2464
#define MN_vcmpnge_uqph 0x2470
#define MN_vcmpnle_uqph 0x247d
#define MN_vcmptrue_uqph 0x248a
#define MN_vcmpneq_uqph 0x2498
#define MN_vcmpeq_uqph 0x24a5
#define MN_vcmpngt_uqph 0x24b1
#define MN_vcmpnlt_uqph 0x24be
#define MN_vcmpunord_sph 0x24cb
#define MN_vcmpord_sph 0x24d9
#define MN_vcmpge_osph 0x24e5
#define MN_vcmple_osph 0x24f1
#define MN_vcmpfalse_osph 0x24fd
#define MN_vcmpneq_osph 0x250c
#define MN_vcmpeq_osph 0x2519
#define MN_vcmpgt_osph 0x2525
#define MN_vcmplt_osph 0x2531
#define MN_vfpclassph 0x253d
#define MN_vcmpnge_usph 0x2548
#define MN_vcmpnle_usph 0x2555
#define MN_vcmptrue_usph 0x2562
#define MN_vcmpneq_usph 0x2570
#define MN_vcmpeq_usph 0x257d
#define MN_vcmpngt_usph 0x2589
#define MN_vcmpnlt_usph 0x2596
#define MN_vcmpngtph 0x25a3
#define MN_vcmpgtph 0x25ad
#define MN_vcmpnltph 0x25b6
#define MN_vcmpltph 0x25c0
#define MN_vgetmantph 0x25c9
#define MN_vrsqrtph 0x25d4
#define MN_vsqrtph 0x25dd
#define MN_vdivph 0x25e5
#define MN_vminmaxph 0x25ec
#define MN_vmaxph 0x25f6
#define MN_vpmacsdqh 0x25fd
#define MN_vpmacssdqh 0x2607
#define MN_vfmsub231sh 0x2612
#define MN_vfnmsub231sh 0x261e
#define MN_vfmadd231sh 0x262b
#define MN_vfnmadd231sh 0x2637
#define MN_vfmsub132sh 0x2644
#define MN_vfnmsub132sh 0x2650
#define MN_vfmadd132sh 0x265d
#define MN_vfnmadd132sh 0x2669
#define MN_vcvtsd2sh 0x2676
#define MN_vcvtsi2sh 0x2680
#define MN_vcvtusi2sh 0x268a
#define MN_vcvtss2sh 0x2695
#define MN_vfmsub213sh 0x269f
#define MN_vfnmsub213sh 0x26ab
#define MN_vfmadd213sh 0x26b8
#define MN_vfnmadd213sh 0x26c4
#define MN_psmash 0x26d1
#define MN_vsubsh 0x26d8
#define MN_vfcmaddcsh 0x26df
#define MN_vfmaddcsh 0x26ea
#define MN_vfcmulcsh 0x26f4
#define MN_vfmulcsh 0x26fe
#define MN_vaddsh 0x2707
#define MN_vcmpunordsh 0x270e
#define MN_vcmpordsh 0x271a
#define MN_vreducesh 0x2724
#define MN_vcmpngesh 0x272e
#define MN_vcmpgesh 0x2738
#define MN_vrndscalesh 0x2741
#define MN_vcmpnlesh 0x274d
#define MN_vcmplesh 0x2757
#define MN_vcmpfalsesh 0x2760
#define MN_vcmptruesh 0x276c
#define MN_vscalefsh 0x2777
#define MN_vucomish 0x2781
#define MN_vcomish 0x278a
#define MN_vmulsh 0x2792
#define MN_vminsh 0x2799
#define MN_vrcpsh 0x27a0
#define MN_vcmpsh 0x27a7
#define MN_vgetexpsh 0x27ae
#define MN_vcmpunord_qsh 0x27b8
#define MN_vcmpord_qsh 0x27c6
#define MN_vcmpneqsh 0x27d2
#define MN_vcmpeqsh 0x27dc
#define MN_vcmpge_oqsh 0x27e5
#define MN_vcmple_oqsh 0x27f1
#define MN_vcmpfalse_oqsh 0x27fd
#define MN_vcmpneq_oqsh 0x280c
#define MN_vcmpeq_oqsh 0x2819
#define MN_vcmpgt_oqsh 0x2825
#define MN_vcmplt_oqsh 0x2831
#define MN_vcmpnge_uqsh 0x283d
#define MN_vcmpnle_uqsh 0x284a
#define MN_vcmptrue_uqsh 0x2857
#define MN_vcmpneq_uqsh 0x2865
#define MN_vcmpeq_uqsh 0x2872
#define MN_vcmpngt_uqsh 0x287e
#define MN_vcmpnlt_uqsh 0x288b
#define MN_vcmpunord_ssh 0x2898
#define MN_vcmpord_ssh 0x28a6
#define MN_vcmpge_ossh 0x28b2
#define MN_vcmple_ossh 0x28be
#define MN_vcmpfalse_ossh 0x28ca
#define MN_vcmpneq_ossh 0x28d9
#define MN_vcmpeq_ossh 0x28e6
#define MN_vcmpgt_ossh 0x28f2
#define MN_vcmplt_ossh 0x28fe
#define MN_vfpclasssh 0x290a
#define MN_vcmpnge_ussh 0x2915
#define MN_vcmpnle_ussh 0x2922
#define MN_vcmptrue_ussh 0x292f
#define MN_vcmpneq_ussh 0x293d
#define MN_vcmpeq_ussh 0x294a
#define MN_vcmpngt_ussh 0x2956
#define MN_vcmpnlt_ussh 0x2963
#define MN_vcmpngtsh 0x2970
#define MN_vcmpgtsh 0x297a
#define MN_vcmpnltsh 0x2983
#define MN_vcmpltsh 0x298d
#define MN_vgetmantsh 0x2996
#define MN_vrsqrtsh 0x29a1
#define MN_vsqrtsh 0x29aa
#define MN_clflush 0x29b2
#define MN_push 0x29ba
#define MN_vdivsh 0x29bf
#define MN_vmovsh 0x29c6
#define MN_vminmaxsh 0x29cd
#define MN_vmaxsh 0x29d7
#define MN_vucomxsh 0x29de
#define MN_vcomxsh 0x29e7
#define MN_blci 0x29ef
#define MN_clgi 0x29f4
#define MN_stgi 0x29f9
#define MN_bzhi 0x29fe
#define MN_cli 0x2a03
#define MN_fcomi 0x2a07
#define MN_fucomi 0x2a0d
#define MN_feni 0x2a14
#define MN_fneni 0x2a19
#define MN_cvttpd2pi 0x2a1f
#define MN_cvtpd2pi 0x2a29
#define MN_cvttps2pi 0x2a32
#define MN_cvtps2pi 0x2a3c
#define MN_fldpi 0x2a45
#define MN_senduipi 0x2a4b
#define MN_fcompi 0x2a54
#define MN_fucompi 0x2a5b
#define MN_movdiri 0x2a63
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x2a6b
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x2a76
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x2a81
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x2a8c
#define MN_vcvttsh2si 0x2a96
#define MN_vcvtsh2si 0x2aa1
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x2aab
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x2ab6
#define MN_fdisi 0x2ac0
#define MN_fndisi 0x2ac6
#define MN_blsi 0x2acd
#define MN_vcvttsd2usi 0x2ad2
#define MN_vcvtsd2usi 0x2ade
#define MN_vcvttsh2usi 0x2ae9
#define MN_vcvtsh2usi 0x2af5
#define MN_vcvttss2usi 0x2b00
#define MN_vcvtss2usi 0x2b0c
#define MN_movnti 0x2b17
#define MN_sti 0x2b1e
#define MN_clui 0x2b22
#define MN_stui (MN_testui + 2)
#define MN_testui 0x2b27
#define MN_notrack 0x2b2e
#define MN_lock 0x2b36
#define MN_bndmk 0x2b3b
#define MN_xresldtrk 0x2b41
#define MN_xsusldtrk 0x2b4b
#define MN_blcmsk 0x2b55
#define MN_blsmsk 0x2b5c
#define MN_tzmsk 0x2b63
#define MN_tcvtrowps2bf16l 0x2b69
#define MN_sal 0x2b79
#define MN_lwpval 0x2b7d
#define MN_bndcl 0x2b84
#define MN_rcl 0x2b8a
#define MN_tcvtrowps2phl 0x2b8e
#define MN_shl 0x2b9c
#define MN_jl 0x2ba0
#define MN_aesdec256kl 0x2ba3
#define MN_aesenc256kl 0x2baf
#define MN_aesdecwide256kl 0x2bbb
#define MN_aesencwide256kl 0x2bcb
#define MN_aesdec128kl 0x2bdb
#define MN_aesenc128kl 0x2be7
#define MN_aesdecwide128kl 0x2bf3
#define MN_aesencwide128kl 0x2c03
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x2c13
#define MN_lcall 0x2c1a
#define MN_seamcall 0x2c20
#define MN_vmmcall 0x2c29
#define MN_vmcall 0x2c31
#define MN_syscall 0x2c38
#define MN_vzeroall 0x2c40
#define MN_fildll 0x2c49
#define MN_blcfill 0x2c50
#define MN_blsfill 0x2c58
#define MN_fistpll 0x2c60
#define MN_fisttpll 0x2c68
#define MN_jnl 0x2c71
#define MN_ccmpnl 0x2c75
#define MN_setnl 0x2c7c
#define MN_ctestnl 0x2c82
#define MN_setzunl 0x2c8a
#define MN_cmovnl (MN_cfcmovnl + 2)
#define MN_cfcmovnl 0x2c92
#define MN_rol 0x2c9b
#define MN_ccmpl 0x2c9f
#define MN_arpl 0x2ca5
#define MN_vpmacsdql 0x2caa
#define MN_vpmacssdql 0x2cb4
#define MN_lsl 0x2cbf
#define MN_movsl 0x2cc3
#define MN_setl 0x2cc9
#define MN_ctestl 0x2cce
#define MN_cwtl 0x2cd5
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x2cda
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x2ce0
#define MN_montmul 0x2ce6
#define MN_setzul 0x2cee
#define MN_cmovl (MN_cfcmovl + 2)
#define MN_cfcmovl 0x2cf5
#define MN_vpmovb2m 0x2cfd
#define MN_vpmovd2m 0x2d06
#define MN_vpmovq2m 0x2d0f
#define MN_vpmovw2m 0x2d18
#define MN_aam 0x2d21
#define MN_fxam 0x2d25
#define MN_fprem 0x2d2a
#define MN_fcom 0x2d30
#define MN_ficom 0x2d35
#define MN_fucom 0x2d3b
#define MN_fsetpm 0x2d41
#define MN_fnsetpm 0x2d48
#define MN_frstpm 0x2d50
#define MN_vpperm 0x2d57
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x2d5e
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x2d69
#define MN_rsm 0x2d74
#define MN_fpatan 0x2d78
#define MN_fptan 0x2d7f
#define MN_bndcn 0x2d85
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x2d8b
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2d92
#define MN_pfmin 0x2d99
#define MN_fsin 0x2d9f
#define MN_vmxon 0x2da4
#define MN_vmrun 0x2daa
#define MN_jo 0x2db0
#define MN_jno 0x2db3
#define MN_ccmpno 0x2db7
#define MN_setno 0x2dbe
#define MN_ctestno 0x2dc4
#define MN_setzuno 0x2dcc
#define MN_cmovno (MN_cfcmovno + 2)
#define MN_cfcmovno 0x2dd4
#define MN_jpo 0x2ddd
#define MN_ccmpo 0x2de1
#define MN_setpo 0x2de7
#define MN_setzupo 0x2ded
#define MN_cmovpo (MN_cfcmovpo + 2)
#define MN_cfcmovpo 0x2df5
#define MN_cqo 0x2dfe
#define MN_tilezero 0x2e02
#define MN_clzero 0x2e0b
#define MN_seto 0x2e12
#define MN_into 0x2e17
#define MN_cqto 0x2e1c
#define MN_ctesto 0x2e21
#define MN_ssto 0x2e28
#define MN_setzuo 0x2e2d
#define MN_cmovo (MN_cfcmovo + 2)
#define MN_cfcmovo 0x2e34
#define MN_push2p 0x2e3c
#define MN_pop2p 0x2e43
#define MN_bswap 0x2e49
#define MN_fsubp 0x2e4f
#define MN_pfrcp 0x2e55
#define MN_rdtscp 0x2e5b
#define MN_faddp 0x2e62
#define MN_pdep 0x2e68
#define MN_ffreep 0x2e6d
#define MN_rep 0x2e74
#define MN_pushp 0x2e78
#define MN_fcomip 0x2e7e
#define MN_fucomip 0x2e85
#define MN_jp 0x2e8d
#define MN_fmulp 0x2e90
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x2e96
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x2e9b
#define MN_fcomp 0x2ea0
#define MN_ficomp 0x2ea6
#define MN_fucomp 0x2ead
#define MN_jnp 0x2eb4
#define MN_setnp 0x2eb8
#define MN_setzunp 0x2ebe
#define MN_cmovnp (MN_cfcmovnp + 2)
#define MN_cfcmovnp 0x2ec6
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2ecf
#define MN_loop 0x2ed4
#define MN_pop 0x2ed9
#define MN_fcompp 0x2edd
#define MN_fucompp 0x2ee4
#define MN_popp 0x2eec
#define MN_fsubrp 0x2ef1
#define MN_fdivrp 0x2ef8
#define MN_rstorssp 0x2eff
#define MN_saveprevssp 0x2f08
#define MN_setp 0x2f14
#define MN_fbstp 0x2f19
#define MN_fdecstp 0x2f1f
#define MN_fincstp 0x2f27
#define MN_fstp 0x2f2f
#define MN_fistp 0x2f34
#define MN_fisttp 0x2f3a
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x2f41
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x2f4a
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x2f54
#define MN_setzup 0x2f5e
#define MN_fdivp 0x2f65
#define MN_cmovp (MN_cfcmovp + 2)
#define MN_cfcmovp 0x2f6b
#define MN_vpbroadcastmb2q 0x2f73
#define MN_vpermi2q 0x2f83
#define MN_vpmovm2q 0x2f8c
#define MN_movdq2q 0x2f95
#define MN_vpermt2q 0x2f9d
#define MN_vpshaq 0x2fa6
#define MN_vpsraq 0x2fad
#define MN_vphaddbq 0x2fb4
#define MN_vphaddubq 0x2fbd
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x2fc7
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x2fce
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x2fd8
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x2fe2
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x2fed
#define MN_vcvttph2dq 0x2ff7
#define MN_vcvtph2dq 0x3002
#define MN_movq2dq 0x300c
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x3014
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x301f
#define MN_vphsubdq 0x3029
#define MN_cdq 0x3032
#define MN_kaddq 0x3036
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x303c
#define MN_vphadddq 0x3043
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x304c
#define MN_kunpckdq 0x3057
#define MN_vpshldq 0x3060
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x3068
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x3073
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x307b
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x3083
#define MN_kandq 0x308b
#define MN_vpandq 0x3091
#define MN_vpexpandq 0x3098
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x30a2
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x30ae
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x30bc
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x30ca
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x30d6
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x30e4
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x30f2
#define MN_vpgatherdq 0x30fd
#define MN_vpscatterdq 0x3108
#define MN_vpshrdq 0x3114
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x311c
#define MN_vcvttpd2udq 0x3125
#define MN_vcvtpd2udq 0x3131
#define MN_vcvttph2udq 0x313c
#define MN_vcvtph2udq 0x3148
#define MN_vcvttps2udq 0x3153
#define MN_vcvtps2udq 0x315f
#define MN_vphaddudq 0x316a
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x3174
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x317d
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x3187
#define MN_vpcomgeq 0x3191
#define MN_vpcomleq 0x319a
#define MN_vpcmpnleq 0x31a3
#define MN_vpcmpleq 0x31ad
#define MN_pfcmpeq 0x31b6
#define MN_vpcomfalseq 0x31be
#define MN_vpcomtrueq 0x31ca
#define MN_vpternlogq 0x31d5
#define MN_vpshlq 0x31e0
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x31e7
#define MN_vpmullq 0x31ee
#define MN_vprolq 0x31f6
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x31fd
#define MN_kshiftlq 0x3204
#define MN_vpblendmq 0x320d
#define MN_vptestnmq 0x3217
#define MN_vpcomq 0x3221
#define MN_vpermq 0x3228
#define MN_vptestmq 0x322f
#define MN_kandnq 0x3238
#define MN_vpandnq 0x323f
#define MN_valignq 0x3247
#define MN_vpcmpq 0x324f
#define MN_incsspq 0x3256
#define MN_rdsspq 0x325e
#define MN_vcvttpd2qq 0x3265
#define MN_vcvtpd2qq 0x3270
#define MN_vcvttph2qq 0x327a
#define MN_vcvtph2qq 0x3285
#define MN_vcvttps2qq 0x328f
#define MN_vcvtps2qq 0x329a
#define MN_vpcomeqq 0x32a4
#define MN_vpcomneqq 0x32ad
#define MN_vpcmpneqq 0x32b7
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x32c1
#define MN_vpgatherqq 0x32ca
#define MN_vpscatterqq 0x32d5
#define MN_vcvttpd2uqq 0x32e1
#define MN_vcvtpd2uqq 0x32ed
#define MN_vcvttph2uqq 0x32f8
#define MN_vcvtph2uqq 0x3304
#define MN_vcvttps2uqq 0x330f
#define MN_vcvtps2uqq 0x331b
#define MN_korq 0x3326
#define MN_kxnorq 0x332b
#define MN_vporq 0x3332
#define MN_vprorq 0x3338
#define MN_kxorq 0x333f
#define MN_vpxorq 0x3345
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x334c
#define MN_kshiftrq 0x3354
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x335d
#define MN_vpabsq 0x3365
#define MN_vpminsq 0x336c
#define MN_vmovrsq 0x3374
#define MN_vpcompressq 0x337c
#define MN_wrssq 0x3388
#define MN_wrussq 0x338e
#define MN_vpmaxsq 0x3395
#define MN_vp2intersectq 0x339d
#define MN_vpconflictq 0x33ab
#define MN_vpcomgtq 0x33b7
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x33c0
#define MN_cltq 0x33c9
#define MN_vpcomltq 0x33ce
#define MN_vpcmpnltq 0x33d7
#define MN_vpcmpltq 0x33e1
#define MN_vpopcntq 0x33ea
#define MN_vplzcntq 0x33f3
#define MN_movntq 0x33fc
#define MN_knotq 0x3403
#define MN_vprotq 0x3409
#define MN_insertq 0x3410
#define MN_vpbroadcastq 0x3418
#define MN_ktestq 0x3425
#define MN_kortestq 0x342c
#define MN_vpcomgeuq 0x3435
#define MN_vpcomleuq 0x343f
#define MN_vpcmpnleuq 0x3449
#define MN_vpcmpleuq 0x3454
#define MN_vpcomfalseuq 0x345e
#define MN_vpcomtrueuq 0x346b
#define MN_vpmadd52huq 0x3477
#define MN_vpmadd52luq 0x3483
#define MN_vpcomuq 0x348f
#define MN_vpminuq 0x3497
#define MN_vpcmpuq 0x349f
#define MN_vpcomequq 0x34a7
#define MN_vpcomnequq 0x34b1
#define MN_vpcmpnequq 0x34bc
#define MN_vpcmpequq 0x34c7
#define MN_vpcomgtuq 0x34d1
#define MN_vpcomltuq 0x34db
#define MN_vpcmpnltuq 0x34e5
#define MN_vpcmpltuq 0x34f0
#define MN_vpmaxuq 0x34fa
#define MN_vpsravq 0x3502
#define MN_vpshldvq 0x350a
#define MN_vpshrdvq 0x3513
#define MN_vpsllvq 0x351c
#define MN_vprolvq 0x3524
#define MN_vpsrlvq 0x352c
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x3534
#define MN_vmovq 0x353f
#define MN_vprorvq 0x3545
#define MN_vphaddwq 0x354d
#define MN_vphadduwq 0x3556
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x3560
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x356a
#define MN_rex_r 0x3574
#define MN_vmclear 0x357a
#define MN_lar 0x3582
#define MN_sar 0x3586
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x358a
#define MN_fisubr 0x3591
#define MN_rcr 0x3598
#define MN_vzeroupper 0x359c
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x35a7
#define MN_shr 0x35b0
#define MN_clr 0x35b4
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x35b8
#define MN_or (MN_aor + 1)
#define MN_aor 0x35c1
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x35c5
#define MN_ror 0x35ca
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x35ce
#define MN_frstor 0x35d7
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x35de
#define MN_xor (MN_axor + 1)
#define MN_axor 0x35e6
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x35eb
#define MN_verr 0x35f1
#define MN_bsr 0x35f6
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x35fa
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x3603
#define MN_blsr 0x360c
#define MN_rdmsr (MN_urdmsr + 1)
#define MN_urdmsr 0x3611
#define MN_wrmsr (MN_uwrmsr + 1)
#define MN_uwrmsr 0x3618
#define MN_btr 0x361f
#define MN_xcrypt_ctr 0x3623
#define MN_xcryptctr 0x362e
#define MN_ltr 0x3638
#define MN_str 0x363c
#define MN_bextr 0x3640
#define MN_fdivr 0x3646
#define MN_fidivr 0x364c
#define MN_rex_wr 0x3653
#define MN_vcvt2ph2bf8s 0x365a
#define MN_vcvtbiasph2bf8s 0x3667
#define MN_vcvtph2bf8s 0x3677
#define MN_vcvt2ph2hf8s 0x3683
#define MN_vcvtbiasph2hf8s 0x3690
#define MN_vcvtph2hf8s 0x36a0
#define MN_aas 0x36ac
#define MN_scas 0x36b0
#define MN_das 0x36b5
#define MN_fabs 0x36b9
#define MN_jmpabs 0x36be
#define MN_movabs 0x36c5
#define MN_vcvttbf162ibs 0x36cc
#define MN_vcvtbf162ibs 0x36da
#define MN_vcvttph2ibs 0x36e7
#define MN_vcvtph2ibs 0x36f3
#define MN_vcvttps2ibs 0x36fe
#define MN_vcvtps2ibs 0x370a
#define MN_vcvttbf162iubs 0x3715
#define MN_vcvtbf162iubs 0x3724
#define MN_vcvttph2iubs 0x3732
#define MN_vcvtph2iubs 0x373f
#define MN_vcvttps2iubs 0x374b
#define MN_vcvtps2iubs 0x3758
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x3764
#define MN_ds (MN_lds + 1)
#define MN_lds 0x3769
#define MN_enqcmds 0x376d
#define MN_lods 0x3775
#define MN_vpdpbssds 0x377a
#define MN_vp4dpwssds 0x3784
#define MN_vpdpwssds 0x378f
#define MN_vpdpbusds 0x3799
#define MN_vpdpwusds 0x37a3
#define MN_vpdpbsuds 0x37ad
#define MN_vpdpwsuds 0x37b7
#define MN_vpdpbuuds 0x37c1
#define MN_vpdpwuuds 0x37cb
#define MN_es (MN_les + 1)
#define MN_les 0x37d5
#define MN_xsaves 0x37d9
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x37e0
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x37e4
#define MN_lgs 0x37e9
#define MN_swapgs 0x37ed
#define MN_fchs 0x37f4
#define MN_vcvttsd2sis 0x37f9
#define MN_vcvttss2sis 0x3805
#define MN_vcvttsd2usis 0x3811
#define MN_vcvttss2usis 0x381e
#define MN_js 0x382b
#define MN_encls 0x382e
#define MN_emms (MN_femms + 1)
#define MN_femms 0x3834
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x383a
#define MN_jns 0x3841
#define MN_ccmpns 0x3845
#define MN_wrmsrns 0x384c
#define MN_setns 0x3854
#define MN_ctestns 0x385a
#define MN_setzuns 0x3862
#define MN_cmovns (MN_cfcmovns + 2)
#define MN_cfcmovns 0x386a
#define MN_fcos 0x3873
#define MN_fsincos 0x3878
#define MN_stos 0x3880
#define MN_vfmaddsub231ps 0x3885
#define MN_vfmsub231ps 0x3894
#define MN_vfnmsub231ps 0x38a0
#define MN_vfmsubadd231ps 0x38ad
#define MN_vfmadd231ps 0x38bc
#define MN_vfnmadd231ps 0x38c8
#define MN_vfmaddsub132ps 0x38d5
#define MN_vfmsub132ps 0x38e4
#define MN_vfnmsub132ps 0x38f0
#define MN_vfmsubadd132ps 0x38fd
#define MN_vfmadd132ps 0x390c
#define MN_vfnmadd132ps 0x3918
#define MN_tmmultf32ps (MN_ttmmultf32ps + 1)
#define MN_ttmmultf32ps 0x3925
#define MN_vcvtneebf162ps 0x3932
#define MN_vbcstnebf162ps 0x3941
#define MN_vcvtneobf162ps 0x3950
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x395f
#define MN_tcvtrowd2ps 0x3969
#define MN_vcvtneeph2ps 0x3975
#define MN_vcvtneoph2ps 0x3982
#define MN_vcvtph2ps 0x398f
#define MN_vbcstnesh2ps 0x3999
#define MN_vpermi2ps 0x39a6
#define MN_cvtpi2ps 0x39b0
#define MN_vpermil2ps 0x39b9
#define MN_vexp2ps 0x39c4
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x39cc
#define MN_vcvtudq2ps 0x39d6
#define MN_vcvtqq2ps 0x39e1
#define MN_vcvtuqq2ps 0x39eb
#define MN_vpermt2ps 0x39f6
#define MN_vfmaddsub213ps 0x3a00
#define MN_vfmsub213ps 0x3a0f
#define MN_vfnmsub213ps 0x3a1b
#define MN_vfmsubadd213ps 0x3a28
#define MN_vfmadd213ps 0x3a37
#define MN_vfnmadd213ps 0x3a43
#define MN_vrcp14ps 0x3a50
#define MN_vrsqrt14ps 0x3a59
#define MN_tdpbf16ps (MN_ttdpbf16ps + 1)
#define MN_ttdpbf16ps 0x3a64
#define MN_vdpbf16ps 0x3a6f
#define MN_tcmmrlfp16ps (MN_ttcmmrlfp16ps + 1)
#define MN_ttcmmrlfp16ps 0x3a79
#define MN_tcmmimfp16ps (MN_tconjtcmmimfp16ps + 5)
#define MN_tconjtcmmimfp16ps 0x3a87
#define MN_ttcmmimfp16ps 0x3a99
#define MN_tdpfp16ps (MN_ttdpfp16ps + 1)
#define MN_ttdpfp16ps 0x3aa7
#define MN_vrcp28ps 0x3ab2
#define MN_vrsqrt28ps 0x3abb
#define MN_tdphbf8ps 0x3ac6
#define MN_tdpbf8ps 0x3ad0
#define MN_tdpbhf8ps 0x3ad9
#define MN_tdphf8ps 0x3ae3
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x3aec
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3af4
#define MN_vaddsubps 0x3b00
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x3b0a
#define MN_vfmsubps 0x3b12
#define MN_vfnmsubps 0x3b1b
#define MN_vsubps 0x3b25
#define MN_vgatherpf0dps 0x3b2c
#define MN_vscatterpf0dps 0x3b3a
#define MN_vgatherpf1dps 0x3b49
#define MN_vscatterpf1dps 0x3b57
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3b66
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3b72
#define MN_v4fmaddps 0x3b7a
#define MN_vfmaddps 0x3b84
#define MN_v4fnmaddps 0x3b8d
#define MN_vfnmaddps 0x3b98
#define MN_vaddps 0x3ba2
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x3ba9
#define MN_vandps 0x3bb3
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x3bba
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x3bc3
#define MN_vgatherdps 0x3bcc
#define MN_vscatterdps 0x3bd7
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3be3
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3bef
#define MN_vreduceps 0x3bf9
#define MN_vrangeps 0x3c03
#define MN_vcmpngeps 0x3c0c
#define MN_vcmpgeps 0x3c16
#define MN_vrndscaleps 0x3c1f
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x3c2b
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x3c35
#define MN_vcmpfalseps 0x3c3e
#define MN_vcmptrueps 0x3c4a
#define MN_vscalefps 0x3c55
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3c5f
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3c67
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3c71
#define MN_vdpphps 0x3c7a
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x3c82
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x3c8a
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x3c94
#define MN_vpermilps 0x3c9d
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x3ca7
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x3cb1
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x3cb8
#define MN_cmps (MN_ccmps + 1)
#define MN_ccmps 0x3cc0
#define MN_vblendmps 0x3cc6
#define MN_vfixupimmps 0x3cd0
#define MN_vpermps 0x3cdc
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x3ce4
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3cec
#define MN_seamops 0x3cf3
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3cfb
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x3d02
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x3d08
#define MN_vgetexpps 0x3d0f
#define MN_vgatherpf0qps 0x3d19
#define MN_vscatterpf0qps 0x3d27
#define MN_vgatherpf1qps 0x3d36
#define MN_vscatterpf1qps 0x3d44
#define MN_vcmpunord_qps 0x3d53
#define MN_vcmpord_qps 0x3d61
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3d6d
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x3d77
#define MN_vcmpge_oqps 0x3d80
#define MN_vcmple_oqps 0x3d8c
#define MN_vcmpfalse_oqps 0x3d98
#define MN_vcmpneq_oqps 0x3da7
#define MN_vcmpeq_oqps 0x3db4
#define MN_vcmpgt_oqps 0x3dc0
#define MN_vcmplt_oqps 0x3dcc
#define MN_vgatherqps 0x3dd8
#define MN_vscatterqps 0x3de3
#define MN_vcmpnge_uqps 0x3def
#define MN_vcmpnle_uqps 0x3dfc
#define MN_vcmptrue_uqps 0x3e09
#define MN_vcmpneq_uqps 0x3e17
#define MN_vcmpeq_uqps 0x3e24
#define MN_vcmpngt_uqps 0x3e30
#define MN_vcmpnlt_uqps 0x3e3d
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x3e4a
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x3e50
#define MN_vcmpunord_sps 0x3e57
#define MN_vcmpord_sps 0x3e65
#define MN_vcmpge_osps 0x3e71
#define MN_vcmple_osps 0x3e7d
#define MN_vcmpfalse_osps 0x3e89
#define MN_vcmpneq_osps 0x3e98
#define MN_vcmpeq_osps 0x3ea5
#define MN_vcmpgt_osps 0x3eb1
#define MN_vcmplt_osps 0x3ebd
#define MN_vfpclassps 0x3ec9
#define MN_vcompressps 0x3ed4
#define MN_vcmpnge_usps 0x3ee0
#define MN_vcmpnle_usps 0x3eed
#define MN_vcmptrue_usps 0x3efa
#define MN_vcmpneq_usps 0x3f08
#define MN_vcmpeq_usps 0x3f15
#define MN_vcmpngt_usps 0x3f21
#define MN_vcmpnlt_usps 0x3f2e
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x3f3b
#define MN_vcmpngtps 0x3f46
#define MN_vcmpgtps 0x3f50
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x3f59
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x3f63
#define MN_vgetmantps 0x3f6c
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x3f77
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x3f80
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x3f8a
#define MN_vsqrtps 0x3f93
#define MN_vtestps 0x3f9b
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x3fa3
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x3fab
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x3fb5
#define MN_vmaskmovps 0x3fbc
#define MN_maxps (MN_vminmaxps + 4)
#define MN_vminmaxps 0x3fc7
#define MN_vmaxps 0x3fd1
#define MN_vfrczps 0x3fd8
#define MN_vcvttpd2dqs 0x3fe0
#define MN_vcvttps2dqs 0x3fec
#define MN_vcvttpd2udqs 0x3ff8
#define MN_vcvttps2udqs 0x4005
#define MN_vcvttpd2qqs 0x4012
#define MN_vcvttps2qqs 0x401e
#define MN_vcvttpd2uqqs 0x402a
#define MN_vcvttps2uqqs 0x4037
#define MN_t2rpntlvwz0rs 0x4044
#define MN_t2rpntlvwz1rs 0x4052
#define MN_tileloaddrs 0x4060
#define MN_xrstors 0x406c
#define MN_movrs 0x4074
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x407a
#define MN_vfnmsub231ss 0x4086
#define MN_vfmadd231ss 0x4093
#define MN_vfnmadd231ss 0x409f
#define MN_vfmsub132ss 0x40ac
#define MN_vfnmsub132ss 0x40b8
#define MN_vfmadd132ss 0x40c5
#define MN_vfnmadd132ss 0x40d1
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x40de
#define MN_vcvtsh2ss 0x40e8
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x40f2
#define MN_vcvtusi2ss 0x40fc
#define MN_vfmsub213ss 0x4107
#define MN_vfnmsub213ss 0x4113
#define MN_vfmadd213ss 0x4120
#define MN_vfnmadd213ss 0x412c
#define MN_vrcp14ss 0x4139
#define MN_vrsqrt14ss 0x4142
#define MN_vrcp28ss 0x414d
#define MN_vrsqrt28ss 0x4156
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x4161
#define MN_vfnmsubss 0x416a
#define MN_vsubss 0x4174
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x417b
#define MN_vfmaddss 0x4185
#define MN_v4fnmaddss 0x418e
#define MN_vfnmaddss 0x4199
#define MN_vaddss 0x41a3
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x41aa
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x41b3
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x41bf
#define MN_vreducess 0x41c9
#define MN_vrangess 0x41d3
#define MN_vcmpngess 0x41dc
#define MN_vcmpgess 0x41e6
#define MN_vrndscaless 0x41ef
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x41fb
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x4205
#define MN_vcmpfalsess 0x420e
#define MN_vcmptruess 0x421a
#define MN_vscalefss 0x4225
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x422f
#define MN_vcomiss 0x4238
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x4240
#define MN_vfixupimmss 0x4247
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x4253
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x425a
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x4261
#define MN_vgetexpss 0x4268
#define MN_vcmpunord_qss 0x4272
#define MN_vcmpord_qss 0x4280
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x428c
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x4296
#define MN_vcmpge_oqss 0x429f
#define MN_vcmple_oqss 0x42ab
#define MN_vcmpfalse_oqss 0x42b7
#define MN_vcmpneq_oqss 0x42c6
#define MN_vcmpeq_oqss 0x42d3
#define MN_vcmpgt_oqss 0x42df
#define MN_vcmplt_oqss 0x42eb
#define MN_vcmpnge_uqss 0x42f7
#define MN_vcmpnle_uqss 0x4304
#define MN_vcmptrue_uqss 0x4311
#define MN_vcmpneq_uqss 0x431f
#define MN_vcmpeq_uqss 0x432c
#define MN_vcmpngt_uqss 0x4338
#define MN_vcmpnlt_uqss 0x4345
#define MN_vcmpunord_sss 0x4352
#define MN_vcmpord_sss 0x4360
#define MN_vcmpge_osss 0x436c
#define MN_vcmple_osss 0x4378
#define MN_vcmpfalse_osss 0x4384
#define MN_vcmpneq_osss 0x4393
#define MN_vcmpeq_osss 0x43a0
#define MN_vcmpgt_osss 0x43ac
#define MN_vcmplt_osss 0x43b8
#define MN_vfpclassss 0x43c4
#define MN_vcmpnge_usss 0x43cf
#define MN_vcmpnle_usss 0x43dc
#define MN_vcmptrue_usss 0x43e9
#define MN_vcmpneq_usss 0x43f7
#define MN_vcmpeq_usss 0x4404
#define MN_vcmpngt_usss 0x4410
#define MN_vcmpnlt_usss 0x441d
#define MN_vcmpngtss 0x442a
#define MN_vcmpgtss 0x4434
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x443d
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x4447
#define MN_vgetmantss 0x4450
#define MN_movntss 0x445b
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x4463
#define MN_vsqrtss 0x446c
#define MN_vbroadcastss 0x4474
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x4481
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x4488
#define MN_maxss (MN_vminmaxss + 4)
#define MN_vminmaxss 0x448f
#define MN_vmaxss 0x4499
#define MN_vucomxss 0x44a0
#define MN_vcomxss 0x44a9
#define MN_vfrczss 0x44b1
#define MN_bts 0x44b9
#define MN_erets 0x44bd
#define MN_sets 0x44c3
#define MN_clts 0x44c8
#define MN_ctests 0x44cd
#define MN_outs 0x44d4
#define MN_setzus 0x44d9
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs (MN_cfcmovs + 2)
#define MN_cfcmovs 0x44e0
#define MN_fldl2t 0x44e8
#define MN_xlat 0x44ef
#define MN_bt 0x44f4
#define MN_fxtract 0x44f7
#define MN_lgdt 0x44ff
#define MN_sgdt 0x4504
#define MN_lidt 0x4509
#define MN_sidt 0x450e
#define MN_fldt 0x4513
#define MN_lldt 0x4518
#define MN_sldt 0x451d
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x4522
#define MN_lret 0x4528
#define MN_seamret 0x452d
#define MN_sysret 0x4535
#define MN_hreset 0x453c
#define MN_pfcmpgt 0x4543
#define MN_ht 0x454b
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x454e
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x4554
#define MN_mcommit 0x455b
#define MN_finit 0x4563
#define MN_skinit 0x4569
#define MN_fninit 0x4570
#define MN_vmgexit 0x4577
#define MN_sysexit 0x457f
#define MN_hlt 0x4587
#define MN_popcnt 0x458b
#define MN_lzcnt 0x4592
#define MN_tzcnt 0x4598
#define MN_hnt 0x459e
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x45a2
#define MN_not 0x45aa
#define MN_invept 0x45ae
#define MN_ccmpt 0x45b5
#define MN_xsaveopt 0x45bb
#define MN_clflushopt 0x45c4
#define MN_fstpt 0x45cf
#define MN_xabort 0x45d5
#define MN_fsqrt 0x45dc
#define MN_pfrsqrt 0x45e2
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x45ea
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x45f6
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x4602
#define MN_xtest 0x4609
#define MN_fst 0x460f
#define MN_fist 0x4613
#define MN_rdmsrlist 0x4618
#define MN_wrmsrlist 0x4622
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x462c
#define MN_vmptrst 0x463d
#define MN_ftst 0x4645
#define MN_rmpadjust 0x464a
#define MN_ctestt 0x4654
#define MN_out 0x465b
#define MN_pext 0x465f
#define MN_bndcu 0x4664
#define MN_enclu 0x466a
#define MN_fcmovnu 0x4670
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x4678
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x467f
#define MN_vmovdqu 0x468b
#define MN_rdpkru 0x4693
#define MN_wrpkru 0x469a
#define MN_rdpru 0x46a1
#define MN_eretu 0x46a7
#define MN_fcmovu 0x46ad
#define MN_imulzu 0x46b4
#define MN_xgetbv 0x46bb
#define MN_xsetbv 0x46c2
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x46c9
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x46ce
#define MN_enclv 0x46d4
#define MN_fldenv 0x46da
#define MN_fstenv 0x46e1
#define MN_fnstenv 0x46e8
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x46f0
#define MN_bndmov 0x46f7
#define MN_smov 0x46fe
#define MN_rex_w 0x4703
#define MN_vcvttph2w 0x4709
#define MN_vcvtph2w 0x4713
#define MN_vpermi2w 0x471c
#define MN_vpmovm2w 0x4725
#define MN_vpermt2w 0x472e
#define MN_vpshaw 0x4737
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x473e
#define MN_vphsubbw 0x4745
#define MN_cbw 0x474e
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x4752
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x475c
#define MN_vpsadbw 0x4765
#define MN_vphaddbw 0x476d
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x4776
#define MN_kunpckbw 0x4781
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x478a
#define MN_vphaddubw 0x4795
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x479f
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x47a7
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x47ae
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x47b8
#define MN_fldcw 0x47c2
#define MN_fstcw 0x47c8
#define MN_fnstcw 0x47ce
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x47d5
#define MN_kaddw 0x47dd
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x47e3
#define MN_vpshldw 0x47ea
#define MN_kandw 0x47f2
#define MN_vpexpandw 0x47f8
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x4802
#define MN_vpshrdw 0x480b
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x4813
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x481d
#define MN_vpmovusdw 0x4827
#define MN_vpmovsdw 0x4831
#define MN_vpmovdw 0x483a
#define MN_vpcomgew 0x4842
#define MN_vpcomlew 0x484b
#define MN_vpcmpnlew 0x4854
#define MN_vpcmplew 0x485e
#define MN_vpcomfalsew 0x4867
#define MN_vpcomtruew 0x4873
#define MN_pi2fw 0x487e
#define MN_pshufw 0x4884
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x488b
#define MN_prefetchw 0x4892
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x489c
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x48a5
#define MN_pf2iw 0x48ad
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x48b3
#define MN_vpshlw 0x48bc
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x48c3
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x48ca
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x48d2
#define MN_kshiftlw 0x48d9
#define MN_vpblendmw 0x48e2
#define MN_vptestnmw 0x48ec
#define MN_vpcomw 0x48f6
#define MN_vpermw 0x48fd
#define MN_vptestmw 0x4904
#define MN_kandnw 0x490d
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x4914
#define MN_tilemovrow 0x491c
#define MN_vpcmpw 0x4927
#define MN_vpcomeqw 0x492e
#define MN_vpcomneqw 0x4937
#define MN_vpcmpneqw 0x4941
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x494b
#define MN_vpmovusqw 0x4954
#define MN_vpmovsqw 0x495e
#define MN_vpmovqw 0x4967
#define MN_verw 0x496f
#define MN_pmulhrw 0x4974
#define MN_korw 0x497c
#define MN_kxnorw 0x4981
#define MN_kxorw 0x4988
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x498e
#define MN_kshiftrw 0x4996
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x499f
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x49a7
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x49ae
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x49b9
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x49c2
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x49ca
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x49d3
#define MN_lmsw 0x49db
#define MN_smsw 0x49e0
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x49e5
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x49ed
#define MN_vmovrsw 0x49f7
#define MN_vpcompressw 0x49ff
#define MN_fstsw 0x4a0b
#define MN_fnstsw 0x4a11
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x4a18
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x4a21
#define MN_movsw 0x4a2a
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x4a30
#define MN_cbtw 0x4a38
#define MN_vpcomgtw 0x4a3d
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x4a46
#define MN_vpcomltw 0x4a4f
#define MN_vpcmpnltw 0x4a58
#define MN_vpcmpltw 0x4a62
#define MN_vpopcntw 0x4a6b
#define MN_knotw 0x4a74
#define MN_vprotw 0x4a7a
#define MN_vpbroadcastw 0x4a81
#define MN_ktestw 0x4a8e
#define MN_kortestw 0x4a95
#define MN_vcvttph2uw 0x4a9e
#define MN_vcvtph2uw 0x4aa9
#define MN_vpcomgeuw 0x4ab3
#define MN_vpcomleuw 0x4abd
#define MN_vpcmpnleuw 0x4ac7
#define MN_vpcmpleuw 0x4ad2
#define MN_vpcomfalseuw 0x4adc
#define MN_vpcomtrueuw 0x4ae9
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x4af5
#define MN_vpcomuw 0x4afe
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x4b06
#define MN_vpcmpuw 0x4b0e
#define MN_vpcomequw 0x4b16
#define MN_vpcomnequw 0x4b20
#define MN_vpcmpnequw 0x4b2b
#define MN_vpcmpequw 0x4b36
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x4b40
#define MN_vpcomgtuw 0x4b4c
#define MN_vpcomltuw 0x4b56
#define MN_vpcmpnltuw 0x4b60
#define MN_vpcmpltuw 0x4b6b
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x4b75
#define MN_vpsravw 0x4b7d
#define MN_vpshldvw 0x4b85
#define MN_vpshrdvw 0x4b8e
#define MN_vpsllvw 0x4b97
#define MN_vpsrlvw 0x4b9f
#define MN_kmovw 0x4ba7
#define MN_vmovw 0x4bad
#define MN_vpmacsww 0x4bb3
#define MN_vpmacssww 0x4bbc
#define MN_movzw 0x4bc6
#define MN_rex_x 0x4bcc
#define MN_fyl2x 0x4bd2
#define MN_rex64x 0x4bd8
#define MN_vcvtneps2bf16x 0x4bdf
#define MN_vfpclassbf16x 0x4bee
#define MN_vcvtph2bf8x 0x4bfc
#define MN_vcvtph2hf8x 0x4c08
#define MN_pfmax 0x4c14
#define MN_adcx 0x4c1a
#define MN_bndldx 0x4c1f
#define MN_vfpclasspdx 0x4c26
#define MN_fclex 0x4c32
#define MN_fnclex 0x4c38
#define MN_rex 0x4c3f
#define MN_vcvtpd2phx 0x4c43
#define MN_vcvtdq2phx 0x4c4e
#define MN_vcvtudq2phx 0x4c59
#define MN_vcvtqq2phx 0x4c65
#define MN_vcvtuqq2phx 0x4c70
#define MN_vcvt2ps2phx 0x4c7c
#define MN_vcvtps2phx 0x4c88
#define MN_vfpclassphx 0x4c93
#define MN_shlx 0x4c9f
#define MN_mulx 0x4ca4
#define MN_adox 0x4ca9
#define MN_vcvttpd2dqx 0x4cae
#define MN_vcvtpd2dqx 0x4cba
#define MN_vcvttpd2udqx 0x4cc5
#define MN_vcvtpd2udqx 0x4cd2
#define MN_rex_rx 0x4cde
#define MN_sarx 0x4ce5
#define MN_shrx 0x4cea
#define MN_rorx 0x4cef
#define MN_monitorx 0x4cf4
#define MN_rex_wrx 0x4cfd
#define MN_vcvtph2bf8sx 0x4d05
#define MN_vcvtph2hf8sx 0x4d12
#define MN_vcvtpd2psx 0x4d1f
#define MN_vcvtph2psx 0x4d2a
#define MN_vcvtqq2psx 0x4d35
#define MN_vcvtuqq2psx 0x4d40
#define MN_vfpclasspsx 0x4d4c
#define MN_vcvttpd2dqsx 0x4d58
#define MN_vcvttpd2udqsx 0x4d65
#define MN_movsx 0x4d73
#define MN_mwaitx 0x4d79
#define MN_bndstx 0x4d80
#define MN_rex_wx 0x4d87
#define MN_rexx 0x4d8e
#define MN_vcvtps2phxx 0x4d93
#define MN_movzx 0x4d9f
#define MN_rex64y 0x4da5
#define MN_vcvtneps2bf16y 0x4dac
#define MN_vfpclassbf16y 0x4dbb
#define MN_vcvtph2bf8y 0x4dc9
#define MN_vcvtph2hf8y 0x4dd5
#define MN_vfpclasspdy 0x4de1
#define MN_loadiwkey 0x4ded
#define MN_vcvtpd2phy 0x4df7
#define MN_vcvtdq2phy 0x4e02
#define MN_vcvtudq2phy 0x4e0d
#define MN_vcvtqq2phy 0x4e19
#define MN_vcvtuqq2phy 0x4e24
#define MN_vfpclassphy 0x4e30
#define MN_vcvttpd2dqy 0x4e3c
#define MN_vcvtpd2dqy 0x4e48
#define MN_vcvttpd2udqy 0x4e53
#define MN_vcvtpd2udqy 0x4e60
#define MN_rmpquery 0x4e6c
#define MN_vcvtph2bf8sy 0x4e75
#define MN_vcvtph2hf8sy 0x4e82
#define MN_clrssbsy 0x4e8f
#define MN_setssbsy 0x4e98
#define MN_vcvtpd2psy 0x4ea1
#define MN_vcvtqq2psy 0x4eac
#define MN_vcvtuqq2psy 0x4eb7
#define MN_vfpclasspsy 0x4ec3
#define MN_vcvttpd2dqsy 0x4ecf
#define MN_vcvttpd2udqsy 0x4edc
#define MN_rex64xy 0x4eea
#define MN_rexy 0x4ef2
#define MN_vcvtps2phxy 0x4ef7
#define MN_rexxy 0x4f03
#define MN_rex64z 0x4f09
#define MN_vfpclassbf16z 0x4f10
#define MN_fldz 0x4f1e
#define MN_vfpclasspdz 0x4f23
#define MN_vcvtpd2phz 0x4f2f
#define MN_vcvtqq2phz 0x4f3a
#define MN_vcvtuqq2phz 0x4f45
#define MN_vfpclassphz 0x4f51
#define MN_jz 0x4f5d
#define MN_jnz 0x4f60
#define MN_repnz 0x4f64
#define MN_ccmpnz 0x4f6a
#define MN_loopnz 0x4f71
#define MN_setnz 0x4f78
#define MN_ctestnz 0x4f7e
#define MN_setzunz 0x4f86
#define MN_cmovnz (MN_cfcmovnz + 2)
#define MN_cfcmovnz 0x4f8e
#define MN_repz 0x4f97
#define MN_ccmpz 0x4f9c
#define MN_loopz 0x4fa2
#define MN_vfpclasspsz 0x4fa8
#define MN_setz 0x4fb4
#define MN_ctestz 0x4fb9
#define MN_setzuz 0x4fc0
#define MN_cmovz (MN_cfcmovz + 2)
#define MN_cfcmovz 0x4fc7
#define MN_rex64xz 0x4fcf
#define MN_jecxz 0x4fd7
#define MN_jcxz 0x4fdd
#define MN_jrcxz 0x4fe2
#define MN_rexz 0x4fe8
#define MN_rexxz 0x4fed
#define MN_rex64yz 0x4ff3
#define MN_rex64xyz 0x4ffb
#define MN_rexyz 0x5004
#define MN_rexxyz 0x500a
#define MN__disp32_ 0x5011
#define MN__rex2_ 0x501a
#define MN__vex2_ 0x5021
#define MN__vex3_ 0x5028
#define MN__disp16_ 0x502f
#define MN__disp8_ 0x5038
#define MN__load_ 0x5040
#define MN__store_ 0x5047
#define MN__nooptimize_ 0x504f
#define MN__nf_ 0x505c
#define MN__rex_ 0x5061
#define MN__evex_ 0x5067
#define MN__vex_ 0x506e
#define MN__insn 0x5074
