/* This file is automatically generated by i386-gen.  Do not edit!  */
/* Copyright (C) 2007-2023 Free Software Foundation, Inc.

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

extern const char i386_mnemonics[];

#define MN_ud0 0x1
#define MN_prefetcht0 0x5
#define MN_prefetchit0 0x10
#define MN_xsha1 0x1c
#define MN_fld1 0x22
#define MN_ud1 0x27
#define MN_sha1msg1 0x2b
#define MN_sha256msg1 0x34
#define MN_fprem1 0x3f
#define MN_f2xm1 0x46
#define MN_fyl2xp1 0x4c
#define MN_tileloaddt1 0x54
#define MN_prefetcht1 0x60
#define MN_prefetchit1 0x6b
#define MN_pfrcpit1 0x77
#define MN_pfrsqit1 0x80
#define MN_int1 0x89
#define MN_prefetchwt1 0x8e
#define MN_vmovdqa32 0x9a
#define MN_data32 0xa4
#define MN_crc32 0xab
#define MN_endbr32 0xb1
#define MN_addr32 0xb9
#define MN_vmovdqu32 0xc0
#define MN_ud2 0xca
#define MN_fldlg2 0xce
#define MN_sha1msg2 0xd5
#define MN_sha256msg2 0xde
#define MN_fldln2 0xe9
#define MN_sha256rnds2 0xf0
#define MN_prefetcht2 0xfc
#define MN_pfrcpit2 0x107
#define MN_vbroadcastf32x2 0x110
#define MN_vbroadcasti32x2 0x120
#define MN_vshuff64x2 0x130
#define MN_vextractf64x2 0x13b
#define MN_vinsertf64x2 0x149
#define MN_vbroadcastf64x2 0x156
#define MN_vshufi64x2 0x166
#define MN_vextracti64x2 0x171
#define MN_vinserti64x2 0x17f
#define MN_vbroadcasti64x2 0x18c
#define MN_int3 0x19c
#define MN_vmovdqa64 0x1a1
#define MN_xsavec64 0x1ab
#define MN_xsave64 (MN_fxsave64 + 1)
#define MN_fxsave64 0x1b4
#define MN_endbr64 0x1bd
#define MN_xrstor64 (MN_fxrstor64 + 1)
#define MN_fxrstor64 0x1c5
#define MN_xsaves64 0x1cf
#define MN_xrstors64 0x1d8
#define MN_xsaveopt64 0x1e2
#define MN_vmovdqu64 0x1ed
#define MN_rex64 0x1f7
#define MN_sha1rnds4 0x1fd
#define MN_vshuff32x4 0x207
#define MN_vextractf32x4 0x212
#define MN_vinsertf32x4 0x220
#define MN_vbroadcastf32x4 0x22d
#define MN_vshufi32x4 0x23d
#define MN_vextracti32x4 0x248
#define MN_vinserti32x4 0x256
#define MN_vbroadcasti32x4 0x263
#define MN_vextractf64x4 0x273
#define MN_vinsertf64x4 0x281
#define MN_vbroadcastf64x4 0x28e
#define MN_vextracti64x4 0x29e
#define MN_vinserti64x4 0x2ac
#define MN_vbroadcasti64x4 0x2b9
#define MN_data16 0x2c9
#define MN_vcvtne2ps2bf16 0x2d0
#define MN_vcvtneps2bf16 0x2df
#define MN_addr16 0x2ed
#define MN_vmovdqu16 0x2f4
#define MN_xsha256 0x2fe
#define MN_encodekey256 0x306
#define MN_vperm2f128 0x313
#define MN_vextractf128 0x31e
#define MN_vinsertf128 0x32b
#define MN_vbroadcastf128 0x337
#define MN_vperm2i128 0x346
#define MN_vextracti128 0x351
#define MN_vinserti128 0x35e
#define MN_vbroadcasti128 0x36a
#define MN_encodekey128 0x379
#define MN_vmovdqu8 0x386
#define MN_vextractf32x8 0x38f
#define MN_vinsertf32x8 0x39d
#define MN_vbroadcastf32x8 0x3aa
#define MN_vextracti32x8 0x3ba
#define MN_vinserti32x8 0x3c8
#define MN_vbroadcasti32x8 0x3d5
#define MN_ud2a 0x3e5
#define MN_aaa 0x3ea
#define MN_daa 0x3ee
#define MN_ssca 0x3f2
#define MN_lea 0x3f7
#define MN_invlpga 0x3fb
#define MN_pusha 0x403
#define MN_ja 0x409
#define MN_jna 0x40c
#define MN_setna 0x410
#define MN_cmovna (MN_fcmovna + 1)
#define MN_fcmovna 0x416
#define MN_popa 0x41e
#define MN_movntdqa (MN_vmovntdqa + 1)
#define MN_vmovntdqa 0x423
#define MN_movdqa (MN_vmovdqa + 1)
#define MN_vmovdqa 0x42d
#define MN_seta 0x435
#define MN_prefetchnta 0x43a
#define MN_cmova (MN_fcmova + 1)
#define MN_fcmova 0x446
#define MN_rex_b 0x44d
#define MN_ud2b 0x453
#define MN_vpermi2b 0x458
#define MN_vpmovm2b 0x461
#define MN_vpermt2b 0x46a
#define MN_movdir64b 0x473
#define MN_cmpxchg16b 0x47d
#define MN_cmpxchg8b 0x488
#define MN_vpshab 0x492
#define MN_sbb 0x499
#define MN_psubb (MN_vpsubb + 1)
#define MN_vpsubb 0x49d
#define MN_xcrypt_ecb 0x4a4
#define MN_xcryptecb 0x4af
#define MN_llwpcb 0x4b9
#define MN_slwpcb 0x4c0
#define MN_kaddb 0x4c7
#define MN_paddb (MN_vpaddb + 1)
#define MN_vpaddb 0x4cd
#define MN_kandb 0x4d4
#define MN_vpexpandb 0x4da
#define MN_vpmovusdb 0x4e4
#define MN_vpmovsdb 0x4ee
#define MN_vpmovdb 0x4f7
#define MN_vpcomgeb 0x4ff
#define MN_vpcomleb 0x508
#define MN_vpcmpnleb 0x511
#define MN_vpcmpleb 0x51b
#define MN_vpcomfalseb 0x524
#define MN_vpcomtrueb 0x530
#define MN_xcrypt_cfb 0x53b
#define MN_xcryptcfb 0x546
#define MN_xcrypt_ofb 0x550
#define MN_xcryptofb 0x55b
#define MN_pshufb (MN_vpshufb + 1)
#define MN_vpshufb 0x565
#define MN_invlpgb 0x56d
#define MN_pavgb (MN_vpavgb + 1)
#define MN_vpavgb 0x575
#define MN_jb 0x57c
#define MN_pmovmskb (MN_vpmovmskb + 1)
#define MN_vpmovmskb 0x57f
#define MN_vpshlb 0x589
#define MN_kshiftlb 0x590
#define MN_gf2p8mulb (MN_vgf2p8mulb + 1)
#define MN_vgf2p8mulb 0x599
#define MN_vpblendmb 0x5a4
#define MN_vptestnmb 0x5ae
#define MN_vpcomb 0x5b8
#define MN_vpshufbitqmb 0x5bf
#define MN_vpermb 0x5cc
#define MN_vptestmb 0x5d3
#define MN_kandnb 0x5dc
#define MN_psignb (MN_vpsignb + 1)
#define MN_vpsignb 0x5e3
#define MN_jnb 0x5eb
#define MN_setnb 0x5ef
#define MN_cmovnb (MN_fcmovnb + 1)
#define MN_fcmovnb 0x5f5
#define MN_vpcmpb 0x5fd
#define MN_vpcomeqb 0x604
#define MN_gf2p8affineqb (MN_vgf2p8affineqb + 1)
#define MN_vgf2p8affineqb 0x60d
#define MN_vpcomneqb 0x61c
#define MN_vpcmpneqb 0x626
#define MN_pcmpeqb (MN_vpcmpeqb + 1)
#define MN_vpcmpeqb 0x630
#define MN_vpmovusqb 0x639
#define MN_vpmovsqb 0x643
#define MN_vpmultishiftqb 0x64c
#define MN_gf2p8affineinvqb (MN_vgf2p8affineinvqb + 1)
#define MN_vgf2p8affineinvqb 0x65b
#define MN_vpmovqb 0x66d
#define MN_rex_rb 0x675
#define MN_korb 0x67c
#define MN_kxnorb 0x681
#define MN_kxorb 0x688
#define MN_pinsrb (MN_vpinsrb + 1)
#define MN_vpinsrb 0x68e
#define MN_kshiftrb 0x696
#define MN_pextrb (MN_vpextrb + 1)
#define MN_vpextrb 0x69f
#define MN_rex_wrb 0x6a7
#define MN_pabsb (MN_vpabsb + 1)
#define MN_vpabsb 0x6af
#define MN_psubsb (MN_vpsubsb + 1)
#define MN_vpsubsb 0x6b6
#define MN_paddsb (MN_vpaddsb + 1)
#define MN_vpaddsb 0x6be
#define MN_pminsb (MN_vpminsb + 1)
#define MN_vpminsb 0x6c6
#define MN_vpcompressb 0x6ce
#define MN_psubusb (MN_vpsubusb + 1)
#define MN_vpsubusb 0x6da
#define MN_paddusb (MN_vpaddusb + 1)
#define MN_vpaddusb 0x6e3
#define MN_pavgusb 0x6ec
#define MN_movsb 0x6f4
#define MN_pmaxsb (MN_vpmaxsb + 1)
#define MN_vpmaxsb 0x6fa
#define MN_setb 0x702
#define MN_vpcomgtb 0x707
#define MN_pcmpgtb (MN_vpcmpgtb + 1)
#define MN_vpcmpgtb 0x710
#define MN_vpcomltb 0x719
#define MN_vpcmpnltb 0x722
#define MN_vpcmpltb 0x72c
#define MN_vpopcntb 0x735
#define MN_knotb 0x73e
#define MN_vprotb 0x744
#define MN_vpbroadcastb 0x74b
#define MN_ktestb 0x758
#define MN_kortestb 0x75f
#define MN_vpcomgeub 0x768
#define MN_vpcomleub 0x772
#define MN_vpcmpnleub 0x77c
#define MN_vpcmpleub 0x787
#define MN_vpcomfalseub 0x791
#define MN_vpcomtrueub 0x79e
#define MN_vpcomub 0x7aa
#define MN_pminub (MN_vpminub + 1)
#define MN_vpminub 0x7b2
#define MN_vpcmpub 0x7ba
#define MN_vpcomequb 0x7c2
#define MN_vpcomnequb 0x7cc
#define MN_vpcmpnequb 0x7d7
#define MN_vpcmpequb 0x7e2
#define MN_sub (MN_fsub + 1)
#define MN_fsub (MN_pfsub + 1)
#define MN_pfsub 0x7ec
#define MN_fisub 0x7f2
#define MN_vpcomgtub 0x7f8
#define MN_vpcomltub 0x802
#define MN_vpcmpnltub 0x80c
#define MN_vpcmpltub 0x817
#define MN_pmaxub (MN_vpmaxub + 1)
#define MN_vpmaxub 0x821
#define MN_pblendvb (MN_vpblendvb + 1)
#define MN_vpblendvb 0x829
#define MN_cmovb (MN_fcmovb + 1)
#define MN_fcmovb 0x833
#define MN_kmovb 0x83a
#define MN_rex_wb 0x840
#define MN_clwb 0x847
#define MN_packsswb (MN_vpacksswb + 1)
#define MN_vpacksswb 0x84c
#define MN_packuswb (MN_vpackuswb + 1)
#define MN_vpackuswb 0x856
#define MN_vpmovuswb 0x860
#define MN_vpmovswb 0x86a
#define MN_vpmovwb 0x873
#define MN_rex_xb 0x87b
#define MN_rex_rxb 0x882
#define MN_rex_wrxb 0x88a
#define MN_rex_wxb 0x893
#define MN_movzb 0x89b
#define MN_clac 0x8a1
#define MN_stac 0x8a6
#define MN_xcrypt_cbc 0x8ab
#define MN_xcryptcbc 0x8b6
#define MN_pfacc 0x8c0
#define MN_pfnacc 0x8c6
#define MN_pfpnacc 0x8cd
#define MN_adc 0x8d5
#define MN_dec (MN_aesdec + 3)
#define MN_aesdec (MN_vaesdec + 1)
#define MN_vaesdec 0x8d9
#define MN_getsec 0x8e1
#define MN_xsavec 0x8e8
#define MN_blcic 0x8ef
#define MN_blsic 0x8f5
#define MN_jc 0x8fb
#define MN_t1mskc 0x8fe
#define MN_clc 0x905
#define MN_cmc 0x909
#define MN_aesimc (MN_vaesimc + 1)
#define MN_vaesimc 0x90d
#define MN_rdpmc 0x915
#define MN_aesenc (MN_vaesenc + 1)
#define MN_vaesenc 0x91b
#define MN_inc 0x923
#define MN_jnc 0x927
#define MN_setnc 0x92b
#define MN_vmfunc 0x931
#define MN_cmovnc 0x938
#define MN_tlbsync 0x93f
#define MN_rdtsc 0x947
#define MN_btc 0x94d
#define MN_setc 0x951
#define MN_stc 0x956
#define MN_cmovc 0x95a
#define MN_vpermi2d 0x960
#define MN_vpmovm2d 0x969
#define MN_vpermt2d 0x972
#define MN_vpbroadcastmw2d 0x97b
#define MN_aad 0x98b
#define MN_vmread 0x98f
#define MN_vpshad 0x996
#define MN_vmload 0x99d
#define MN_psrad (MN_vpsrad + 1)
#define MN_vpsrad 0x9a4
#define MN_vphaddbd 0x9ab
#define MN_vphaddubd 0x9b4
#define MN_phsubd (MN_vphsubd + 1)
#define MN_vphsubd 0x9be
#define MN_psubd (MN_vpsubd + 1)
#define MN_vpsubd 0x9c6
#define MN_pmovsxbd (MN_vpmovsxbd + 1)
#define MN_vpmovsxbd 0x9cd
#define MN_pmovzxbd (MN_vpmovzxbd + 1)
#define MN_vpmovzxbd 0x9d7
#define MN_add (MN_aadd + 1)
#define MN_aadd 0x9e1
#define MN_fadd (MN_pfadd + 1)
#define MN_pfadd 0x9e6
#define MN_fiadd 0x9ec
#define MN_tileloadd 0x9f2
#define MN_xadd (MN_cmpnaxadd + 5)
#define MN_cmpnaxadd 0x9fc
#define MN_cmpaxadd 0xa06
#define MN_cmpnbxadd 0xa0f
#define MN_cmpbxadd 0xa19
#define MN_cmpncxadd 0xa22
#define MN_cmpcxadd 0xa2c
#define MN_cmpnaexadd 0xa35
#define MN_cmpaexadd 0xa40
#define MN_cmpnbexadd 0xa4a
#define MN_cmpbexadd 0xa55
#define MN_cmpngexadd 0xa5f
#define MN_cmpgexadd 0xa6a
#define MN_cmpnlexadd 0xa74
#define MN_cmplexadd 0xa7f
#define MN_cmpnexadd 0xa89
#define MN_cmpexadd 0xa93
#define MN_cmppexadd 0xa9c
#define MN_cmpngxadd 0xaa6
#define MN_cmpgxadd 0xab0
#define MN_cmpnlxadd 0xab9
#define MN_cmplxadd 0xac3
#define MN_cmpnoxadd 0xacc
#define MN_cmpoxadd 0xad6
#define MN_cmppoxadd 0xadf
#define MN_cmpnpxadd 0xae9
#define MN_cmppxadd 0xaf3
#define MN_cmpnsxadd 0xafc
#define MN_cmpsxadd 0xb06
#define MN_cmpnzxadd 0xb0f
#define MN_cmpzxadd 0xb19
#define MN_phaddd (MN_vphaddd + 1)
#define MN_vphaddd 0xb22
#define MN_kaddd 0xb2a
#define MN_paddd (MN_vpaddd + 1)
#define MN_vpaddd 0xb30
#define MN_vpshldd 0xb37
#define MN_kandd 0xb3f
#define MN_vpandd 0xb45
#define MN_vpexpandd 0xb4c
#define MN_vpblendd 0xb56
#define MN_vpgatherdd 0xb5f
#define MN_vpscatterdd 0xb6a
#define MN_vpshrdd 0xb76
#define MN_vpmacsdd 0xb7e
#define MN_vpmacssdd 0xb87
#define MN_rdseed 0xb91
#define MN_vpcomged 0xb98
#define MN_vpcomled 0xba1
#define MN_vpcmpnled 0xbaa
#define MN_vpcmpled 0xbb4
#define MN_tilestored 0xbbd
#define MN_vpcomfalsed 0xbc8
#define MN_vpcomtrued 0xbd4
#define MN_pi2fd 0xbdf
#define MN_pshufd (MN_vpshufd + 1)
#define MN_vpshufd 0xbe5
#define MN_vpternlogd 0xbed
#define MN_pf2id 0xbf8
#define MN_invpcid 0xbfe
#define MN_rdpid 0xc06
#define MN_invvpid 0xc0c
#define MN_cpuid 0xc14
#define MN_fbld 0xc1a
#define MN_cld 0xc1f
#define MN_fld 0xc23
#define MN_shld (MN_vpshld + 2)
#define MN_vpshld 0xc27
#define MN_fild 0xc2e
#define MN_pslld (MN_vpslld + 1)
#define MN_vpslld 0xc33
#define MN_pmulld (MN_vpmulld + 1)
#define MN_vpmulld 0xc3a
#define MN_vprold 0xc42
#define MN_psrld (MN_vpsrld + 1)
#define MN_vpsrld 0xc49
#define MN_vmptrld 0xc50
#define MN_kshiftld 0xc58
#define MN_enqcmd 0xc61
#define MN_vpblendmd 0xc68
#define MN_vptestnmd 0xc72
#define MN_vpcomd 0xc7c
#define MN_vpermd 0xc83
#define MN_vptestmd 0xc8a
#define MN_and (MN_aand + 1)
#define MN_aand 0xc93
#define MN_pand (MN_vpand + 1)
#define MN_vpand 0xc98
#define MN_rdrand 0xc9e
#define MN_bnd 0xca5
#define MN_kandnd 0xca9
#define MN_vpandnd 0xcb0
#define MN_xend 0xcb8
#define MN_valignd 0xcbd
#define MN_psignd (MN_vpsignd + 1)
#define MN_vpsignd 0xcc5
#define MN_bound 0xccd
#define MN_slod 0xcd3
#define MN_vfmaddsub231pd 0xcd8
#define MN_vfmsub231pd 0xce7
#define MN_vfnmsub231pd 0xcf3
#define MN_vfmsubadd231pd 0xd00
#define MN_vfmadd231pd 0xd0f
#define MN_vfnmadd231pd 0xd1b
#define MN_vfmaddsub132pd 0xd28
#define MN_vfmsub132pd 0xd37
#define MN_vfnmsub132pd 0xd43
#define MN_vfmsubadd132pd 0xd50
#define MN_vfmadd132pd 0xd5f
#define MN_vfnmadd132pd 0xd6b
#define MN_vcvtph2pd 0xd78
#define MN_vpermi2pd 0xd82
#define MN_cvtpi2pd 0xd8c
#define MN_vpermil2pd 0xd95
#define MN_vexp2pd 0xda0
#define MN_cvtdq2pd (MN_vcvtdq2pd + 1)
#define MN_vcvtdq2pd 0xda8
#define MN_vcvtudq2pd 0xdb2
#define MN_vcvtqq2pd 0xdbd
#define MN_vcvtuqq2pd 0xdc7
#define MN_cvtps2pd (MN_vcvtps2pd + 1)
#define MN_vcvtps2pd 0xdd2
#define MN_vpermt2pd 0xddc
#define MN_vfmaddsub213pd 0xde6
#define MN_vfmsub213pd 0xdf5
#define MN_vfnmsub213pd 0xe01
#define MN_vfmsubadd213pd 0xe0e
#define MN_vfmadd213pd 0xe1d
#define MN_vfnmadd213pd 0xe29
#define MN_vrcp14pd 0xe36
#define MN_vrsqrt14pd 0xe3f
#define MN_vrcp28pd 0xe4a
#define MN_vrsqrt28pd 0xe53
#define MN_movapd (MN_vmovapd + 1)
#define MN_vmovapd 0xe5e
#define MN_pswapd 0xe66
#define MN_subpd (MN_addsubpd + 3)
#define MN_addsubpd (MN_vfmaddsubpd + 3)
#define MN_vfmaddsubpd 0xe6d
#define MN_vaddsubpd 0xe79
#define MN_hsubpd (MN_vhsubpd + 1)
#define MN_vhsubpd 0xe83
#define MN_vfmsubpd 0xe8b
#define MN_vfnmsubpd 0xe94
#define MN_vsubpd 0xe9e
#define MN_vgatherpf0dpd 0xea5
#define MN_vscatterpf0dpd 0xeb3
#define MN_vgatherpf1dpd 0xec2
#define MN_vscatterpf1dpd 0xed0
#define MN_addpd (MN_vfmsubaddpd + 6)
#define MN_vfmsubaddpd 0xedf
#define MN_haddpd (MN_vhaddpd + 1)
#define MN_vhaddpd 0xeeb
#define MN_vfmaddpd 0xef3
#define MN_vfnmaddpd 0xefc
#define MN_vaddpd 0xf06
#define MN_andpd (MN_vexpandpd + 4)
#define MN_vexpandpd 0xf0d
#define MN_vandpd 0xf17
#define MN_blendpd (MN_vblendpd + 1)
#define MN_vblendpd 0xf1e
#define MN_roundpd (MN_vroundpd + 1)
#define MN_vroundpd 0xf27
#define MN_vgatherdpd 0xf30
#define MN_vscatterdpd 0xf3b
#define MN_cmpunordpd (MN_vcmpunordpd + 1)
#define MN_vcmpunordpd 0xf47
#define MN_cmpordpd (MN_vcmpordpd + 1)
#define MN_vcmpordpd 0xf53
#define MN_vreducepd 0xf5d
#define MN_vrangepd 0xf67
#define MN_vcmpngepd 0xf70
#define MN_vcmpgepd 0xf7a
#define MN_vrndscalepd 0xf83
#define MN_cmpnlepd (MN_vcmpnlepd + 1)
#define MN_vcmpnlepd 0xf8f
#define MN_cmplepd (MN_vcmplepd + 1)
#define MN_vcmplepd 0xf99
#define MN_vcmpfalsepd 0xfa2
#define MN_vcmptruepd 0xfae
#define MN_vscalefpd 0xfb9
#define MN_shufpd (MN_vshufpd + 1)
#define MN_vshufpd 0xfc3
#define MN_unpckhpd (MN_vunpckhpd + 1)
#define MN_vunpckhpd 0xfcb
#define MN_movhpd (MN_vmovhpd + 1)
#define MN_vmovhpd 0xfd5
#define MN_movmskpd (MN_vmovmskpd + 1)
#define MN_vmovmskpd 0xfdd
#define MN_vpermilpd 0xfe7
#define MN_unpcklpd (MN_vunpcklpd + 1)
#define MN_vunpcklpd 0xff1
#define MN_mulpd (MN_vmulpd + 1)
#define MN_vmulpd 0xffb
#define MN_movlpd (MN_vmovlpd + 1)
#define MN_vmovlpd 0x1002
#define MN_vpcmpd 0x100a
#define MN_vblendmpd 0x1011
#define MN_vfixupimmpd 0x101b
#define MN_vpermpd 0x1027
#define MN_andnpd (MN_vandnpd + 1)
#define MN_vandnpd 0x102f
#define MN_minpd (MN_vminpd + 1)
#define MN_vminpd 0x1037
#define MN_dppd (MN_vdppd + 1)
#define MN_vdppd 0x103e
#define MN_cmppd (MN_vcmppd + 1)
#define MN_vcmppd 0x1044
#define MN_vgetexppd 0x104b
#define MN_vgatherpf0qpd 0x1055
#define MN_vscatterpf0qpd 0x1063
#define MN_vgatherpf1qpd 0x1072
#define MN_vscatterpf1qpd 0x1080
#define MN_vcmpunord_qpd 0x108f
#define MN_vcmpord_qpd 0x109d
#define MN_cmpneqpd (MN_vcmpneqpd + 1)
#define MN_vcmpneqpd 0x10a9
#define MN_cmpeqpd (MN_vcmpeqpd + 1)
#define MN_vcmpeqpd 0x10b3
#define MN_vcmpge_oqpd 0x10bc
#define MN_vcmple_oqpd 0x10c8
#define MN_vcmpfalse_oqpd 0x10d4
#define MN_vcmpneq_oqpd 0x10e3
#define MN_vcmpeq_oqpd 0x10f0
#define MN_vcmpgt_oqpd 0x10fc
#define MN_vcmplt_oqpd 0x1108
#define MN_vgatherqpd 0x1114
#define MN_vscatterqpd 0x111f
#define MN_vcmpnge_uqpd 0x112b
#define MN_vcmpnle_uqpd 0x1138
#define MN_vcmptrue_uqpd 0x1145
#define MN_vcmpneq_uqpd 0x1153
#define MN_vcmpeq_uqpd 0x1160
#define MN_vcmpngt_uqpd 0x116c
#define MN_vcmpnlt_uqpd 0x1179
#define MN_orpd (MN_vorpd + 1)
#define MN_vorpd 0x1186
#define MN_xorpd (MN_vxorpd + 1)
#define MN_vxorpd 0x118c
#define MN_vcmpunord_spd 0x1193
#define MN_vcmpord_spd 0x11a1
#define MN_vcmpge_ospd 0x11ad
#define MN_vcmple_ospd 0x11b9
#define MN_vcmpfalse_ospd 0x11c5
#define MN_vcmpneq_ospd 0x11d4
#define MN_vcmpeq_ospd 0x11e1
#define MN_vcmpgt_ospd 0x11ed
#define MN_vcmplt_ospd 0x11f9
#define MN_vfpclasspd 0x1205
#define MN_incsspd 0x1210
#define MN_rdsspd 0x1218
#define MN_vcompresspd 0x121f
#define MN_vcmpnge_uspd 0x122b
#define MN_vcmpnle_uspd 0x1238
#define MN_vcmptrue_uspd 0x1245
#define MN_vcmpneq_uspd 0x1253
#define MN_vcmpeq_uspd 0x1260
#define MN_vcmpngt_uspd 0x126c
#define MN_vcmpnlt_uspd 0x1279
#define MN_vcmpngtpd 0x1286
#define MN_vcmpgtpd 0x1290
#define MN_cmpnltpd (MN_vcmpnltpd + 1)
#define MN_vcmpnltpd 0x1299
#define MN_cmpltpd (MN_vcmpltpd + 1)
#define MN_vcmpltpd 0x12a3
#define MN_vgetmantpd 0x12ac
#define MN_movntpd (MN_vmovntpd + 1)
#define MN_vmovntpd 0x12b7
#define MN_sqrtpd (MN_vsqrtpd + 1)
#define MN_vsqrtpd 0x12c0
#define MN_vtestpd 0x12c8
#define MN_movupd (MN_vmovupd + 1)
#define MN_vmovupd 0x12d0
#define MN_blendvpd (MN_vblendvpd + 1)
#define MN_vblendvpd 0x12d8
#define MN_divpd (MN_vdivpd + 1)
#define MN_vdivpd 0x12e2
#define MN_vmaskmovpd 0x12e9
#define MN_maxpd (MN_vmaxpd + 1)
#define MN_vmaxpd 0x12f4
#define MN_vfrczpd 0x12fb
#define MN_vpcomeqd 0x1303
#define MN_vpcomneqd 0x130c
#define MN_vpcmpneqd 0x1316
#define MN_pcmpeqd (MN_vpcmpeqd + 1)
#define MN_vpcmpeqd 0x1320
#define MN_vpgatherqd 0x1329
#define MN_vpscatterqd 0x1334
#define MN_vpmovusqd 0x1340
#define MN_vpmovsqd 0x134a
#define MN_vpmovqd 0x1353
#define MN_shrd 0x135b
#define MN_kord 0x1360
#define MN_kxnord 0x1365
#define MN_vpord 0x136c
#define MN_vprord 0x1372
#define MN_word (MN_aword + 1)
#define MN_aword 0x1379
#define MN_dword (MN_adword + 1)
#define MN_adword 0x137f
#define MN_kxord 0x1386
#define MN_vpxord 0x138c
#define MN_pinsrd (MN_vpinsrd + 1)
#define MN_vpinsrd 0x1393
#define MN_kshiftrd 0x139b
#define MN_pextrd (MN_vpextrd + 1)
#define MN_vpextrd 0x13a4
#define MN_vfmsub231sd 0x13ac
#define MN_vfnmsub231sd 0x13b8
#define MN_vfmadd231sd 0x13c5
#define MN_vfnmadd231sd 0x13d1
#define MN_vfmsub132sd 0x13de
#define MN_vfnmsub132sd 0x13ea
#define MN_vfmadd132sd 0x13f7
#define MN_vfnmadd132sd 0x1403
#define MN_vcvtsh2sd 0x1410
#define MN_cvtsi2sd (MN_vcvtsi2sd + 1)
#define MN_vcvtsi2sd 0x141a
#define MN_vcvtusi2sd 0x1424
#define MN_cvtss2sd (MN_vcvtss2sd + 1)
#define MN_vcvtss2sd 0x142f
#define MN_vfmsub213sd 0x1439
#define MN_vfnmsub213sd 0x1445
#define MN_vfmadd213sd 0x1452
#define MN_vfnmadd213sd 0x145e
#define MN_vrcp14sd 0x146b
#define MN_vrsqrt14sd 0x1474
#define MN_vrcp28sd 0x147f
#define MN_vrsqrt28sd 0x1488
#define MN_pabsd (MN_vpabsd + 1)
#define MN_vpabsd 0x1493
#define MN_subsd (MN_vfmsubsd + 3)
#define MN_vfmsubsd 0x149a
#define MN_vfnmsubsd 0x14a3
#define MN_vsubsd 0x14ad
#define MN_addsd (MN_vfmaddsd + 3)
#define MN_vfmaddsd 0x14b4
#define MN_vfnmaddsd 0x14bd
#define MN_vaddsd 0x14c7
#define MN_roundsd (MN_vroundsd + 1)
#define MN_vroundsd 0x14ce
#define MN_cmpunordsd (MN_vcmpunordsd + 1)
#define MN_vcmpunordsd 0x14d7
#define MN_cmpordsd (MN_vcmpordsd + 1)
#define MN_vcmpordsd 0x14e3
#define MN_vreducesd 0x14ed
#define MN_vrangesd 0x14f7
#define MN_vcmpngesd 0x1500
#define MN_vcmpgesd 0x150a
#define MN_vrndscalesd 0x1513
#define MN_cmpnlesd (MN_vcmpnlesd + 1)
#define MN_vcmpnlesd 0x151f
#define MN_cmplesd (MN_vcmplesd + 1)
#define MN_vcmplesd 0x1529
#define MN_vcmpfalsesd 0x1532
#define MN_vcmptruesd 0x153e
#define MN_vscalefsd 0x1549
#define MN_comisd (MN_ucomisd + 1)
#define MN_ucomisd (MN_vucomisd + 1)
#define MN_vucomisd 0x1553
#define MN_vcomisd 0x155c
#define MN_mulsd (MN_vmulsd + 1)
#define MN_vmulsd 0x1564
#define MN_vfixupimmsd 0x156b
#define MN_minsd (MN_pminsd + 1)
#define MN_pminsd (MN_vpminsd + 1)
#define MN_vpminsd 0x1577
#define MN_vminsd 0x157f
#define MN_cmpsd (MN_vcmpsd + 1)
#define MN_vcmpsd 0x1586
#define MN_vgetexpsd 0x158d
#define MN_vcmpunord_qsd 0x1597
#define MN_vcmpord_qsd 0x15a5
#define MN_cmpneqsd (MN_vcmpneqsd + 1)
#define MN_vcmpneqsd 0x15b1
#define MN_cmpeqsd (MN_vcmpeqsd + 1)
#define MN_vcmpeqsd 0x15bb
#define MN_vcmpge_oqsd 0x15c4
#define MN_vcmple_oqsd 0x15d0
#define MN_vcmpfalse_oqsd 0x15dc
#define MN_vcmpneq_oqsd 0x15eb
#define MN_vcmpeq_oqsd 0x15f8
#define MN_vcmpgt_oqsd 0x1604
#define MN_vcmplt_oqsd 0x1610
#define MN_vcmpnge_uqsd 0x161c
#define MN_vcmpnle_uqsd 0x1629
#define MN_vcmptrue_uqsd 0x1636
#define MN_vcmpneq_uqsd 0x1644
#define MN_vcmpeq_uqsd 0x1651
#define MN_vcmpngt_uqsd 0x165d
#define MN_vcmpnlt_uqsd 0x166a
#define MN_vcmpunord_ssd 0x1677
#define MN_vcmpord_ssd 0x1685
#define MN_vpdpbssd 0x1691
#define MN_tdpbssd 0x169a
#define MN_vpcompressd 0x16a2
#define MN_vcmpge_ossd 0x16ae
#define MN_vcmple_ossd 0x16ba
#define MN_vcmpfalse_ossd 0x16c6
#define MN_vcmpneq_ossd 0x16d5
#define MN_vcmpeq_ossd 0x16e2
#define MN_vcmpgt_ossd 0x16ee
#define MN_vcmplt_ossd 0x16fa
#define MN_wrssd 0x1706
#define MN_vfpclasssd 0x170c
#define MN_vcmpnge_ussd 0x1717
#define MN_vcmpnle_ussd 0x1724
#define MN_vcmptrue_ussd 0x1731
#define MN_vcmpneq_ussd 0x173f
#define MN_vcmpeq_ussd 0x174c
#define MN_vcmpngt_ussd 0x1758
#define MN_vcmpnlt_ussd 0x1765
#define MN_wrussd 0x1772
#define MN_vp4dpwssd 0x1779
#define MN_vpdpwssd 0x1783
#define MN_vcmpngtsd 0x178c
#define MN_vcmpgtsd 0x1796
#define MN_cmpnltsd (MN_vcmpnltsd + 1)
#define MN_vcmpnltsd 0x179f
#define MN_cmpltsd (MN_vcmpltsd + 1)
#define MN_vcmpltsd 0x17a9
#define MN_vgetmantsd 0x17b2
#define MN_movntsd 0x17bd
#define MN_sqrtsd (MN_vsqrtsd + 1)
#define MN_vsqrtsd 0x17c5
#define MN_vbroadcastsd 0x17cd
#define MN_vpdpbusd 0x17da
#define MN_tdpbusd 0x17e3
#define MN_vpdpwusd 0x17eb
#define MN_divsd (MN_vdivsd + 1)
#define MN_vdivsd 0x17f4
#define MN_movsd (MN_vmovsd + 1)
#define MN_vmovsd 0x17fb
#define MN_maxsd (MN_pmaxsd + 1)
#define MN_pmaxsd (MN_vpmaxsd + 1)
#define MN_vpmaxsd 0x1802
#define MN_vmaxsd 0x180a
#define MN_vfrczsd 0x1811
#define MN_vp2intersectd 0x1819
#define MN_vpconflictd 0x1827
#define MN_vpcomgtd 0x1833
#define MN_pcmpgtd (MN_vpcmpgtd + 1)
#define MN_vpcmpgtd 0x183c
#define MN_cltd 0x1845
#define MN_vpcomltd 0x184a
#define MN_vpcmpnltd 0x1853
#define MN_vpcmpltd 0x185d
#define MN_vpopcntd 0x1866
#define MN_vplzcntd 0x186f
#define MN_knotd 0x1878
#define MN_vprotd 0x187e
#define MN_std (MN_vpbroadcastd + 9)
#define MN_vpbroadcastd 0x1885
#define MN_ktestd 0x1892
#define MN_kortestd 0x1899
#define MN_cwtd 0x18a2
#define MN_vpcomgeud 0x18a7
#define MN_vpcomleud 0x18b1
#define MN_vpcmpnleud 0x18bb
#define MN_vpcmpleud 0x18c6
#define MN_vpcomfalseud 0x18d0
#define MN_vpcomtrueud 0x18dd
#define MN_vpcomud 0x18e9
#define MN_pminud (MN_vpminud + 1)
#define MN_vpminud 0x18f1
#define MN_vpcmpud 0x18f9
#define MN_vpcomequd 0x1901
#define MN_vpcomnequd 0x190b
#define MN_vpcmpnequd 0x1916
#define MN_vpcmpequd 0x1921
#define MN_vpdpbsud 0x192b
#define MN_tdpbsud 0x1934
#define MN_vpdpwsud 0x193c
#define MN_vpcomgtud 0x1945
#define MN_vpcomltud 0x194f
#define MN_vpcmpnltud 0x1959
#define MN_vpcmpltud 0x1964
#define MN_vpdpbuud 0x196e
#define MN_tdpbuud 0x1977
#define MN_vpdpwuud 0x197f
#define MN_pmaxud (MN_vpmaxud + 1)
#define MN_vpmaxud 0x1988
#define MN_vpsravd 0x1990
#define MN_vpshldvd 0x1998
#define MN_vpshrdvd 0x19a1
#define MN_vpsllvd 0x19aa
#define MN_vprolvd 0x19b2
#define MN_vpsrlvd 0x19ba
#define MN_invd (MN_wbinvd + 2)
#define MN_wbinvd 0x19c2
#define MN_wbnoinvd 0x19c9
#define MN_movd (MN_kmovd + 1)
#define MN_kmovd (MN_vpmaskmovd + 5)
#define MN_vpmaskmovd 0x19d2
#define MN_vmovd 0x19dd
#define MN_vprorvd 0x19e3
#define MN_vphsubwd 0x19eb
#define MN_cwd 0x19f4
#define MN_vphaddwd 0x19f8
#define MN_pmaddwd (MN_vpmaddwd + 1)
#define MN_vpmaddwd 0x1a01
#define MN_punpckhwd (MN_vpunpckhwd + 1)
#define MN_vpunpckhwd 0x1a0a
#define MN_kunpckwd 0x1a15
#define MN_punpcklwd (MN_vpunpcklwd + 1)
#define MN_vpunpcklwd 0x1a1e
#define MN_vpmacswd 0x1a29
#define MN_vpmadcswd 0x1a32
#define MN_vpmacsswd 0x1a3c
#define MN_vpmadcsswd 0x1a46
#define MN_vphadduwd 0x1a51
#define MN_pmovsxwd (MN_vpmovsxwd + 1)
#define MN_vpmovsxwd 0x1a5b
#define MN_pmovzxwd (MN_vpmovzxwd + 1)
#define MN_vpmovzxwd 0x1a65
#define MN_movsxd 0x1a6f
#define MN_fldl2e 0x1a76
#define MN_jae 0x1a7d
#define MN_jnae 0x1a81
#define MN_setnae 0x1a86
#define MN_cmovnae (MN_fcmovnae + 1)
#define MN_fcmovnae 0x1a8d
#define MN_setae 0x1a96
#define MN_cmovae (MN_fcmovae + 1)
#define MN_fcmovae 0x1a9c
#define MN_jbe 0x1aa4
#define MN_jnbe 0x1aa8
#define MN_setnbe 0x1aad
#define MN_cmovnbe (MN_fcmovnbe + 1)
#define MN_fcmovnbe 0x1ab4
#define MN_setbe 0x1abd
#define MN_movbe (MN_cmovbe + 1)
#define MN_cmovbe (MN_fcmovbe + 1)
#define MN_fcmovbe 0x1ac3
#define MN_lfence 0x1acb
#define MN_mfence 0x1ad2
#define MN_sfence 0x1ad9
#define MN_cwde 0x1ae0
#define MN_ffree 0x1ae5
#define MN_jge 0x1aeb
#define MN_jnge 0x1aef
#define MN_setnge 0x1af4
#define MN_cmovnge 0x1afb
#define MN_pfcmpge 0x1b03
#define MN_setge 0x1b0b
#define MN_cmovge 0x1b11
#define MN_je 0x1b18
#define MN_fscale 0x1b1b
#define MN_jle 0x1b22
#define MN_jnle 0x1b26
#define MN_setnle 0x1b2b
#define MN_cmovnle 0x1b32
#define MN_setle 0x1b3a
#define MN_cmovle 0x1b40
#define MN_vmresume 0x1b47
#define MN_jne 0x1b50
#define MN_repne 0x1b54
#define MN_loopne 0x1b5a
#define MN_setne 0x1b61
#define MN_cmovne (MN_fcmovne + 1)
#define MN_fcmovne 0x1b67
#define MN_repe 0x1b6f
#define MN_jpe 0x1b74
#define MN_loope 0x1b78
#define MN_setpe 0x1b7e
#define MN_cmovpe 0x1b84
#define MN_cdqe 0x1b8b
#define MN_xacquire 0x1b90
#define MN_xstore 0x1b99
#define MN_rdfsbase 0x1ba0
#define MN_wrfsbase 0x1ba9
#define MN_rdgsbase 0x1bb2
#define MN_wrgsbase 0x1bbb
#define MN_tilerelease 0x1bc4
#define MN_xrelease 0x1bd0
#define MN_pause (MN_tpause + 1)
#define MN_tpause 0x1bd9
#define MN_pvalidate 0x1be0
#define MN_rmpupdate 0x1bea
#define MN_sete 0x1bf4
#define MN_vmwrite 0x1bf9
#define MN_ptwrite 0x1c01
#define MN_cldemote 0x1c09
#define MN_sha1nexte 0x1c12
#define MN_leave 0x1c1c
#define MN_fsave 0x1c22
#define MN_vmsave 0x1c28
#define MN_fnsave 0x1c2f
#define MN_xsave (MN_fxsave + 1)
#define MN_fxsave 0x1c36
#define MN_cmove (MN_fcmove + 1)
#define MN_fcmove 0x1c3d
#define MN_serialize 0x1c44
#define MN_vmxoff 0x1c4e
#define MN_lahf 0x1c55
#define MN_sahf 0x1c5a
#define MN_pushf 0x1c5f
#define MN_popf 0x1c65
#define MN_bsf 0x1c6a
#define MN_retf 0x1c6e
#define MN_neg 0x1c73
#define MN_ldtilecfg 0x1c77
#define MN_sttilecfg 0x1c81
#define MN_xchg (MN_cmpxchg + 3)
#define MN_cmpxchg 0x1c8b
#define MN_pconfig 0x1c93
#define MN_jg 0x1c9b
#define MN_jng 0x1c9e
#define MN_xstore_rng 0x1ca2
#define MN_xstorerng 0x1cad
#define MN_setng 0x1cb7
#define MN_cmovng 0x1cbd
#define MN_invlpg 0x1cc4
#define MN_setg 0x1ccb
#define MN_cmovg 0x1cd0
#define MN_vmlaunch 0x1cd6
#define MN_prefetch 0x1cdf
#define MN_fxch 0x1ce8
#define MN_vfmaddsub231ph 0x1ced
#define MN_vfmsub231ph 0x1cfc
#define MN_vfnmsub231ph 0x1d08
#define MN_vfmsubadd231ph 0x1d15
#define MN_vfmadd231ph 0x1d24
#define MN_vfnmadd231ph 0x1d30
#define MN_vfmaddsub132ph 0x1d3d
#define MN_vfmsub132ph 0x1d4c
#define MN_vfnmsub132ph 0x1d58
#define MN_vfmsubadd132ph 0x1d65
#define MN_vfmadd132ph 0x1d74
#define MN_vfnmadd132ph 0x1d80
#define MN_vcvtpd2ph 0x1d8d
#define MN_vcvtdq2ph 0x1d97
#define MN_vcvtudq2ph 0x1da1
#define MN_vcvtqq2ph 0x1dac
#define MN_vcvtuqq2ph 0x1db6
#define MN_vcvtps2ph 0x1dc1
#define MN_vcvtw2ph 0x1dcb
#define MN_vcvtuw2ph 0x1dd4
#define MN_vfmaddsub213ph 0x1dde
#define MN_vfmsub213ph 0x1ded
#define MN_vfnmsub213ph 0x1df9
#define MN_vfmsubadd213ph 0x1e06
#define MN_vfmadd213ph 0x1e15
#define MN_vfnmadd213ph 0x1e21
#define MN_vsubph 0x1e2e
#define MN_vfcmaddcph 0x1e35
#define MN_vfmaddcph 0x1e40
#define MN_vfcmulcph 0x1e4a
#define MN_vfmulcph 0x1e54
#define MN_vaddph 0x1e5d
#define MN_vcmpunordph 0x1e64
#define MN_vcmpordph 0x1e70
#define MN_vreduceph 0x1e7a
#define MN_vcmpngeph 0x1e84
#define MN_vcmpgeph 0x1e8e
#define MN_vrndscaleph 0x1e97
#define MN_vcmpnleph 0x1ea3
#define MN_vcmpleph 0x1ead
#define MN_vcmpfalseph 0x1eb6
#define MN_vcmptrueph 0x1ec2
#define MN_vscalefph 0x1ecd
#define MN_vmulph 0x1ed7
#define MN_vminph 0x1ede
#define MN_vrcpph 0x1ee5
#define MN_vcmpph 0x1eec
#define MN_vgetexpph 0x1ef3
#define MN_vcmpunord_qph 0x1efd
#define MN_vcmpord_qph 0x1f0b
#define MN_vcmpneqph 0x1f17
#define MN_vcmpeqph 0x1f21
#define MN_vcmpge_oqph 0x1f2a
#define MN_vcmple_oqph 0x1f36
#define MN_vcmpfalse_oqph 0x1f42
#define MN_vcmpneq_oqph 0x1f51
#define MN_vcmpeq_oqph 0x1f5e
#define MN_vcmpgt_oqph 0x1f6a
#define MN_vcmplt_oqph 0x1f76
#define MN_vcmpnge_uqph 0x1f82
#define MN_vcmpnle_uqph 0x1f8f
#define MN_vcmptrue_uqph 0x1f9c
#define MN_vcmpneq_uqph 0x1faa
#define MN_vcmpeq_uqph 0x1fb7
#define MN_vcmpngt_uqph 0x1fc3
#define MN_vcmpnlt_uqph 0x1fd0
#define MN_vcmpunord_sph 0x1fdd
#define MN_vcmpord_sph 0x1feb
#define MN_vcmpge_osph 0x1ff7
#define MN_vcmple_osph 0x2003
#define MN_vcmpfalse_osph 0x200f
#define MN_vcmpneq_osph 0x201e
#define MN_vcmpeq_osph 0x202b
#define MN_vcmpgt_osph 0x2037
#define MN_vcmplt_osph 0x2043
#define MN_vfpclassph 0x204f
#define MN_vcmpnge_usph 0x205a
#define MN_vcmpnle_usph 0x2067
#define MN_vcmptrue_usph 0x2074
#define MN_vcmpneq_usph 0x2082
#define MN_vcmpeq_usph 0x208f
#define MN_vcmpngt_usph 0x209b
#define MN_vcmpnlt_usph 0x20a8
#define MN_vcmpngtph 0x20b5
#define MN_vcmpgtph 0x20bf
#define MN_vcmpnltph 0x20c8
#define MN_vcmpltph 0x20d2
#define MN_vgetmantph 0x20db
#define MN_vrsqrtph 0x20e6
#define MN_vsqrtph 0x20ef
#define MN_vdivph 0x20f7
#define MN_vmaxph 0x20fe
#define MN_vpmacsdqh 0x2105
#define MN_vpmacssdqh 0x210f
#define MN_vfmsub231sh 0x211a
#define MN_vfnmsub231sh 0x2126
#define MN_vfmadd231sh 0x2133
#define MN_vfnmadd231sh 0x213f
#define MN_vfmsub132sh 0x214c
#define MN_vfnmsub132sh 0x2158
#define MN_vfmadd132sh 0x2165
#define MN_vfnmadd132sh 0x2171
#define MN_vcvtsd2sh 0x217e
#define MN_vcvtsi2sh 0x2188
#define MN_vcvtusi2sh 0x2192
#define MN_vcvtss2sh 0x219d
#define MN_vfmsub213sh 0x21a7
#define MN_vfnmsub213sh 0x21b3
#define MN_vfmadd213sh 0x21c0
#define MN_vfnmadd213sh 0x21cc
#define MN_psmash 0x21d9
#define MN_vsubsh 0x21e0
#define MN_vfcmaddcsh 0x21e7
#define MN_vfmaddcsh 0x21f2
#define MN_vfcmulcsh 0x21fc
#define MN_vfmulcsh 0x2206
#define MN_vaddsh 0x220f
#define MN_vcmpunordsh 0x2216
#define MN_vcmpordsh 0x2222
#define MN_vreducesh 0x222c
#define MN_vcmpngesh 0x2236
#define MN_vcmpgesh 0x2240
#define MN_vrndscalesh 0x2249
#define MN_vcmpnlesh 0x2255
#define MN_vcmplesh 0x225f
#define MN_vcmpfalsesh 0x2268
#define MN_vcmptruesh 0x2274
#define MN_vscalefsh 0x227f
#define MN_vucomish 0x2289
#define MN_vcomish 0x2292
#define MN_vmulsh 0x229a
#define MN_vminsh 0x22a1
#define MN_vrcpsh 0x22a8
#define MN_vcmpsh 0x22af
#define MN_vgetexpsh 0x22b6
#define MN_vcmpunord_qsh 0x22c0
#define MN_vcmpord_qsh 0x22ce
#define MN_vcmpneqsh 0x22da
#define MN_vcmpeqsh 0x22e4
#define MN_vcmpge_oqsh 0x22ed
#define MN_vcmple_oqsh 0x22f9
#define MN_vcmpfalse_oqsh 0x2305
#define MN_vcmpneq_oqsh 0x2314
#define MN_vcmpeq_oqsh 0x2321
#define MN_vcmpgt_oqsh 0x232d
#define MN_vcmplt_oqsh 0x2339
#define MN_vcmpnge_uqsh 0x2345
#define MN_vcmpnle_uqsh 0x2352
#define MN_vcmptrue_uqsh 0x235f
#define MN_vcmpneq_uqsh 0x236d
#define MN_vcmpeq_uqsh 0x237a
#define MN_vcmpngt_uqsh 0x2386
#define MN_vcmpnlt_uqsh 0x2393
#define MN_vcmpunord_ssh 0x23a0
#define MN_vcmpord_ssh 0x23ae
#define MN_vcmpge_ossh 0x23ba
#define MN_vcmple_ossh 0x23c6
#define MN_vcmpfalse_ossh 0x23d2
#define MN_vcmpneq_ossh 0x23e1
#define MN_vcmpeq_ossh 0x23ee
#define MN_vcmpgt_ossh 0x23fa
#define MN_vcmplt_ossh 0x2406
#define MN_vfpclasssh 0x2412
#define MN_vcmpnge_ussh 0x241d
#define MN_vcmpnle_ussh 0x242a
#define MN_vcmptrue_ussh 0x2437
#define MN_vcmpneq_ussh 0x2445
#define MN_vcmpeq_ussh 0x2452
#define MN_vcmpngt_ussh 0x245e
#define MN_vcmpnlt_ussh 0x246b
#define MN_vcmpngtsh 0x2478
#define MN_vcmpgtsh 0x2482
#define MN_vcmpnltsh 0x248b
#define MN_vcmpltsh 0x2495
#define MN_vgetmantsh 0x249e
#define MN_vrsqrtsh 0x24a9
#define MN_vsqrtsh 0x24b2
#define MN_clflush 0x24ba
#define MN_push 0x24c2
#define MN_vdivsh 0x24c7
#define MN_vmovsh 0x24ce
#define MN_vmaxsh 0x24d5
#define MN_blci 0x24dc
#define MN_clgi 0x24e1
#define MN_stgi 0x24e6
#define MN_bzhi 0x24eb
#define MN_cli 0x24f0
#define MN_fcomi 0x24f4
#define MN_fucomi 0x24fa
#define MN_feni 0x2501
#define MN_fneni 0x2506
#define MN_cvttpd2pi 0x250c
#define MN_cvtpd2pi 0x2516
#define MN_cvttps2pi 0x251f
#define MN_cvtps2pi 0x2529
#define MN_fldpi 0x2532
#define MN_senduipi 0x2538
#define MN_fcompi 0x2541
#define MN_fucompi 0x2548
#define MN_movdiri 0x2550
#define MN_pcmpestri (MN_vpcmpestri + 1)
#define MN_vpcmpestri 0x2558
#define MN_pcmpistri (MN_vpcmpistri + 1)
#define MN_vpcmpistri 0x2563
#define MN_cvttsd2si (MN_vcvttsd2si + 1)
#define MN_vcvttsd2si 0x256e
#define MN_cvtsd2si (MN_vcvtsd2si + 1)
#define MN_vcvtsd2si 0x2579
#define MN_vcvttsh2si 0x2583
#define MN_vcvtsh2si 0x258e
#define MN_cvttss2si (MN_vcvttss2si + 1)
#define MN_vcvttss2si 0x2598
#define MN_cvtss2si (MN_vcvtss2si + 1)
#define MN_vcvtss2si 0x25a3
#define MN_fdisi 0x25ad
#define MN_fndisi 0x25b3
#define MN_blsi 0x25ba
#define MN_vcvttsd2usi 0x25bf
#define MN_vcvtsd2usi 0x25cb
#define MN_vcvttsh2usi 0x25d6
#define MN_vcvtsh2usi 0x25e2
#define MN_vcvttss2usi 0x25ed
#define MN_vcvtss2usi 0x25f9
#define MN_movnti 0x2604
#define MN_sti 0x260b
#define MN_clui 0x260f
#define MN_stui (MN_testui + 2)
#define MN_testui 0x2614
#define MN_notrack 0x261b
#define MN_lock 0x2623
#define MN_bndmk 0x2628
#define MN_xresldtrk 0x262e
#define MN_xsusldtrk 0x2638
#define MN_blcmsk 0x2642
#define MN_blsmsk 0x2649
#define MN_tzmsk 0x2650
#define MN_sal 0x2656
#define MN_lwpval 0x265a
#define MN_bndcl 0x2661
#define MN_rcl 0x2667
#define MN_shl 0x266b
#define MN_jl 0x266f
#define MN_aesdec256kl 0x2672
#define MN_aesenc256kl 0x267e
#define MN_aesdecwide256kl 0x268a
#define MN_aesencwide256kl 0x269a
#define MN_aesdec128kl 0x26aa
#define MN_aesenc128kl 0x26b6
#define MN_aesdecwide128kl 0x26c2
#define MN_aesencwide128kl 0x26d2
#define MN_call (MN_tdcall + 2)
#define MN_tdcall 0x26e2
#define MN_lcall 0x26e9
#define MN_seamcall 0x26ef
#define MN_vmmcall 0x26f8
#define MN_vmcall 0x2700
#define MN_syscall 0x2707
#define MN_vzeroall 0x270f
#define MN_fildll 0x2718
#define MN_blcfill 0x271f
#define MN_blsfill 0x2727
#define MN_fistpll 0x272f
#define MN_fisttpll 0x2737
#define MN_jnl 0x2740
#define MN_setnl 0x2744
#define MN_cmovnl 0x274a
#define MN_rol 0x2751
#define MN_arpl 0x2755
#define MN_vpmacsdql 0x275a
#define MN_vpmacssdql 0x2764
#define MN_lsl 0x276f
#define MN_movsl 0x2773
#define MN_setl 0x2779
#define MN_cwtl 0x277e
#define MN_mul (MN_fmul + 1)
#define MN_fmul (MN_pfmul + 1)
#define MN_pfmul 0x2783
#define MN_imul (MN_fimul + 1)
#define MN_fimul 0x2789
#define MN_montmul 0x278f
#define MN_cmovl 0x2797
#define MN_vpmovb2m 0x279d
#define MN_vpmovd2m 0x27a6
#define MN_vpmovq2m 0x27af
#define MN_vpmovw2m 0x27b8
#define MN_aam 0x27c1
#define MN_fxam 0x27c5
#define MN_fprem 0x27ca
#define MN_fcom 0x27d0
#define MN_ficom 0x27d5
#define MN_fucom 0x27db
#define MN_fsetpm 0x27e1
#define MN_fnsetpm 0x27e8
#define MN_frstpm 0x27f0
#define MN_vpperm 0x27f7
#define MN_pcmpestrm (MN_vpcmpestrm + 1)
#define MN_vpcmpestrm 0x27fe
#define MN_pcmpistrm (MN_vpcmpistrm + 1)
#define MN_vpcmpistrm 0x2809
#define MN_rsm 0x2814
#define MN_fpatan 0x2818
#define MN_fptan 0x281f
#define MN_bndcn 0x2825
#define MN_andn (MN_pandn + 1)
#define MN_pandn (MN_vpandn + 1)
#define MN_vpandn 0x282b
#define MN_in (MN_xbegin + 4)
#define MN_xbegin 0x2832
#define MN_pfmin 0x2839
#define MN_fsin 0x283f
#define MN_vmxon 0x2844
#define MN_vmrun 0x284a
#define MN_jo 0x2850
#define MN_jno 0x2853
#define MN_setno 0x2857
#define MN_cmovno 0x285d
#define MN_jpo 0x2864
#define MN_setpo 0x2868
#define MN_cmovpo 0x286e
#define MN_cqo 0x2875
#define MN_tilezero 0x2879
#define MN_clzero 0x2882
#define MN_seto 0x2889
#define MN_into 0x288e
#define MN_cqto 0x2893
#define MN_ssto 0x2898
#define MN_cmovo 0x289d
#define MN_bswap 0x28a3
#define MN_fsubp 0x28a9
#define MN_pfrcp 0x28af
#define MN_rdtscp 0x28b5
#define MN_faddp 0x28bc
#define MN_pdep 0x28c2
#define MN_ffreep 0x28c7
#define MN_rep 0x28ce
#define MN_fcomip 0x28d2
#define MN_fucomip 0x28d9
#define MN_jp 0x28e1
#define MN_fmulp 0x28e4
#define MN_cmp (MN_scmp + 1)
#define MN_scmp 0x28ea
#define MN_jmp (MN_ljmp + 1)
#define MN_ljmp 0x28ef
#define MN_fcomp 0x28f4
#define MN_ficomp 0x28fa
#define MN_fucomp 0x2901
#define MN_jnp 0x2908
#define MN_setnp 0x290c
#define MN_cmovnp 0x2912
#define MN_nop (MN_fnop + 1)
#define MN_fnop 0x2919
#define MN_loop 0x291e
#define MN_pop 0x2923
#define MN_fcompp 0x2927
#define MN_fucompp 0x292e
#define MN_fsubrp 0x2936
#define MN_fdivrp 0x293d
#define MN_rstorssp 0x2944
#define MN_saveprevssp 0x294d
#define MN_setp 0x2959
#define MN_fbstp 0x295e
#define MN_fdecstp 0x2964
#define MN_fincstp 0x296c
#define MN_fstp 0x2974
#define MN_fistp 0x2979
#define MN_fisttp 0x297f
#define MN_movddup (MN_vmovddup + 1)
#define MN_vmovddup 0x2986
#define MN_movshdup (MN_vmovshdup + 1)
#define MN_vmovshdup 0x298f
#define MN_movsldup (MN_vmovsldup + 1)
#define MN_vmovsldup 0x2999
#define MN_fdivp 0x29a3
#define MN_cmovp 0x29a9
#define MN_vpbroadcastmb2q 0x29af
#define MN_vpermi2q 0x29bf
#define MN_vpmovm2q 0x29c8
#define MN_movdq2q 0x29d1
#define MN_vpermt2q 0x29d9
#define MN_vpshaq 0x29e2
#define MN_vpsraq 0x29e9
#define MN_vphaddbq 0x29f0
#define MN_vphaddubq 0x29f9
#define MN_psubq (MN_vpsubq + 1)
#define MN_vpsubq 0x2a03
#define MN_pmovsxbq (MN_vpmovsxbq + 1)
#define MN_vpmovsxbq 0x2a0a
#define MN_pmovzxbq (MN_vpmovzxbq + 1)
#define MN_vpmovzxbq 0x2a14
#define MN_cvttpd2dq (MN_vcvttpd2dq + 1)
#define MN_vcvttpd2dq 0x2a1e
#define MN_cvtpd2dq (MN_vcvtpd2dq + 1)
#define MN_vcvtpd2dq 0x2a29
#define MN_vcvttph2dq 0x2a33
#define MN_vcvtph2dq 0x2a3e
#define MN_movq2dq 0x2a48
#define MN_cvttps2dq (MN_vcvttps2dq + 1)
#define MN_vcvttps2dq 0x2a50
#define MN_cvtps2dq (MN_vcvtps2dq + 1)
#define MN_vcvtps2dq 0x2a5b
#define MN_vphsubdq 0x2a65
#define MN_cdq 0x2a6e
#define MN_kaddq 0x2a72
#define MN_paddq (MN_vpaddq + 1)
#define MN_vpaddq 0x2a78
#define MN_vphadddq 0x2a7f
#define MN_punpckhdq (MN_vpunpckhdq + 1)
#define MN_vpunpckhdq 0x2a88
#define MN_kunpckdq 0x2a93
#define MN_vpshldq 0x2a9c
#define MN_punpckldq (MN_vpunpckldq + 1)
#define MN_vpunpckldq 0x2aa4
#define MN_pslldq (MN_vpslldq + 1)
#define MN_vpslldq 0x2aaf
#define MN_psrldq (MN_vpsrldq + 1)
#define MN_vpsrldq 0x2ab7
#define MN_pmuldq (MN_vpmuldq + 1)
#define MN_vpmuldq 0x2abf
#define MN_kandq 0x2ac7
#define MN_vpandq 0x2acd
#define MN_vpexpandq 0x2ad4
#define MN_punpckhqdq (MN_vpunpckhqdq + 1)
#define MN_vpunpckhqdq 0x2ade
#define MN_pclmulhqhqdq (MN_vpclmulhqhqdq + 1)
#define MN_vpclmulhqhqdq 0x2aea
#define MN_pclmullqhqdq (MN_vpclmullqhqdq + 1)
#define MN_vpclmullqhqdq 0x2af8
#define MN_punpcklqdq (MN_vpunpcklqdq + 1)
#define MN_vpunpcklqdq 0x2b06
#define MN_pclmulhqlqdq (MN_vpclmulhqlqdq + 1)
#define MN_vpclmulhqlqdq 0x2b12
#define MN_pclmullqlqdq (MN_vpclmullqlqdq + 1)
#define MN_vpclmullqlqdq 0x2b20
#define MN_pclmulqdq (MN_vpclmulqdq + 1)
#define MN_vpclmulqdq 0x2b2e
#define MN_vpgatherdq 0x2b39
#define MN_vpscatterdq 0x2b44
#define MN_vpshrdq 0x2b50
#define MN_movntdq (MN_vmovntdq + 1)
#define MN_vmovntdq 0x2b58
#define MN_vcvttpd2udq 0x2b61
#define MN_vcvtpd2udq 0x2b6d
#define MN_vcvttph2udq 0x2b78
#define MN_vcvtph2udq 0x2b84
#define MN_vcvttps2udq 0x2b8f
#define MN_vcvtps2udq 0x2b9b
#define MN_vphaddudq 0x2ba6
#define MN_pmuludq (MN_vpmuludq + 1)
#define MN_vpmuludq 0x2bb0
#define MN_pmovsxdq (MN_vpmovsxdq + 1)
#define MN_vpmovsxdq 0x2bb9
#define MN_pmovzxdq (MN_vpmovzxdq + 1)
#define MN_vpmovzxdq 0x2bc3
#define MN_vpcomgeq 0x2bcd
#define MN_vpcomleq 0x2bd6
#define MN_vpcmpnleq 0x2bdf
#define MN_vpcmpleq 0x2be9
#define MN_pfcmpeq 0x2bf2
#define MN_vpcomfalseq 0x2bfa
#define MN_vpcomtrueq 0x2c06
#define MN_vpternlogq 0x2c11
#define MN_vpshlq 0x2c1c
#define MN_psllq (MN_vpsllq + 1)
#define MN_vpsllq 0x2c23
#define MN_vpmullq 0x2c2a
#define MN_vprolq 0x2c32
#define MN_psrlq (MN_vpsrlq + 1)
#define MN_vpsrlq 0x2c39
#define MN_kshiftlq 0x2c40
#define MN_vpblendmq 0x2c49
#define MN_vptestnmq 0x2c53
#define MN_vpcomq 0x2c5d
#define MN_vpermq 0x2c64
#define MN_vptestmq 0x2c6b
#define MN_kandnq 0x2c74
#define MN_vpandnq 0x2c7b
#define MN_valignq 0x2c83
#define MN_vpcmpq 0x2c8b
#define MN_incsspq 0x2c92
#define MN_rdsspq 0x2c9a
#define MN_vcvttpd2qq 0x2ca1
#define MN_vcvtpd2qq 0x2cac
#define MN_vcvttph2qq 0x2cb6
#define MN_vcvtph2qq 0x2cc1
#define MN_vcvttps2qq 0x2ccb
#define MN_vcvtps2qq 0x2cd6
#define MN_vpcomeqq 0x2ce0
#define MN_vpcomneqq 0x2ce9
#define MN_vpcmpneqq 0x2cf3
#define MN_pcmpeqq (MN_vpcmpeqq + 1)
#define MN_vpcmpeqq 0x2cfd
#define MN_vpgatherqq 0x2d06
#define MN_vpscatterqq 0x2d11
#define MN_vcvttpd2uqq 0x2d1d
#define MN_vcvtpd2uqq 0x2d29
#define MN_vcvttph2uqq 0x2d34
#define MN_vcvtph2uqq 0x2d40
#define MN_vcvttps2uqq 0x2d4b
#define MN_vcvtps2uqq 0x2d57
#define MN_korq 0x2d62
#define MN_kxnorq 0x2d67
#define MN_vporq 0x2d6e
#define MN_vprorq 0x2d74
#define MN_kxorq 0x2d7b
#define MN_vpxorq 0x2d81
#define MN_pinsrq (MN_vpinsrq + 1)
#define MN_vpinsrq 0x2d88
#define MN_kshiftrq 0x2d90
#define MN_extrq (MN_pextrq + 1)
#define MN_pextrq (MN_vpextrq + 1)
#define MN_vpextrq 0x2d99
#define MN_vpabsq 0x2da1
#define MN_vpminsq 0x2da8
#define MN_vpcompressq 0x2db0
#define MN_wrssq 0x2dbc
#define MN_wrussq 0x2dc2
#define MN_vpmaxsq 0x2dc9
#define MN_vp2intersectq 0x2dd1
#define MN_vpconflictq 0x2ddf
#define MN_vpcomgtq 0x2deb
#define MN_pcmpgtq (MN_vpcmpgtq + 1)
#define MN_vpcmpgtq 0x2df4
#define MN_cltq 0x2dfd
#define MN_vpcomltq 0x2e02
#define MN_vpcmpnltq 0x2e0b
#define MN_vpcmpltq 0x2e15
#define MN_vpopcntq 0x2e1e
#define MN_vplzcntq 0x2e27
#define MN_movntq 0x2e30
#define MN_knotq 0x2e37
#define MN_vprotq 0x2e3d
#define MN_insertq 0x2e44
#define MN_vpbroadcastq 0x2e4c
#define MN_ktestq 0x2e59
#define MN_kortestq 0x2e60
#define MN_vpcomgeuq 0x2e69
#define MN_vpcomleuq 0x2e73
#define MN_vpcmpnleuq 0x2e7d
#define MN_vpcmpleuq 0x2e88
#define MN_vpcomfalseuq 0x2e92
#define MN_vpcomtrueuq 0x2e9f
#define MN_vpmadd52huq 0x2eab
#define MN_vpmadd52luq 0x2eb7
#define MN_vpcomuq 0x2ec3
#define MN_vpminuq 0x2ecb
#define MN_vpcmpuq 0x2ed3
#define MN_vpcomequq 0x2edb
#define MN_vpcomnequq 0x2ee5
#define MN_vpcmpnequq 0x2ef0
#define MN_vpcmpequq 0x2efb
#define MN_vpcomgtuq 0x2f05
#define MN_vpcomltuq 0x2f0f
#define MN_vpcmpnltuq 0x2f19
#define MN_vpcmpltuq 0x2f24
#define MN_vpmaxuq 0x2f2e
#define MN_vpsravq 0x2f36
#define MN_vpshldvq 0x2f3e
#define MN_vpshrdvq 0x2f47
#define MN_vpsllvq 0x2f50
#define MN_vprolvq 0x2f58
#define MN_vpsrlvq 0x2f60
#define MN_movq (MN_kmovq + 1)
#define MN_kmovq (MN_maskmovq + 3)
#define MN_maskmovq (MN_vpmaskmovq + 2)
#define MN_vpmaskmovq 0x2f68
#define MN_vmovq 0x2f73
#define MN_vprorvq 0x2f79
#define MN_vphaddwq 0x2f81
#define MN_vphadduwq 0x2f8a
#define MN_pmovsxwq (MN_vpmovsxwq + 1)
#define MN_vpmovsxwq 0x2f94
#define MN_pmovzxwq (MN_vpmovzxwq + 1)
#define MN_vpmovzxwq 0x2f9e
#define MN_rex_r 0x2fa8
#define MN_vmclear 0x2fae
#define MN_lar 0x2fb6
#define MN_sar 0x2fba
#define MN_fsubr (MN_pfsubr + 1)
#define MN_pfsubr 0x2fbe
#define MN_fisubr 0x2fc5
#define MN_rcr 0x2fcc
#define MN_vzeroupper 0x2fd0
#define MN_enter (MN_sysenter + 3)
#define MN_sysenter 0x2fdb
#define MN_shr 0x2fe4
#define MN_clr 0x2fe8
#define MN_palignr (MN_vpalignr + 1)
#define MN_vpalignr 0x2fec
#define MN_or (MN_aor + 1)
#define MN_aor 0x2ff5
#define MN_por (MN_vpor + 1)
#define MN_vpor 0x2ff9
#define MN_ror 0x2ffe
#define MN_monitor (MN_umonitor + 1)
#define MN_umonitor 0x3002
#define MN_frstor 0x300b
#define MN_xrstor (MN_fxrstor + 1)
#define MN_fxrstor 0x3012
#define MN_xor (MN_axor + 1)
#define MN_axor 0x301a
#define MN_pxor (MN_vpxor + 1)
#define MN_vpxor 0x301f
#define MN_verr 0x3025
#define MN_bsr 0x302a
#define MN_ldmxcsr (MN_vldmxcsr + 1)
#define MN_vldmxcsr 0x302e
#define MN_stmxcsr (MN_vstmxcsr + 1)
#define MN_vstmxcsr 0x3037
#define MN_blsr 0x3040
#define MN_rdmsr 0x3045
#define MN_wrmsr 0x304b
#define MN_btr 0x3051
#define MN_xcrypt_ctr 0x3055
#define MN_xcryptctr 0x3060
#define MN_ltr 0x306a
#define MN_str 0x306e
#define MN_bextr 0x3072
#define MN_fdivr 0x3078
#define MN_fidivr 0x307e
#define MN_rex_wr 0x3085
#define MN_aas 0x308c
#define MN_scas 0x3090
#define MN_das 0x3095
#define MN_fabs 0x3099
#define MN_movabs 0x309e
#define MN_cs (MN_blcs + 2)
#define MN_blcs 0x30a5
#define MN_ds (MN_lds + 1)
#define MN_lds 0x30aa
#define MN_enqcmds 0x30ae
#define MN_lods 0x30b6
#define MN_vpdpbssds 0x30bb
#define MN_vp4dpwssds 0x30c5
#define MN_vpdpwssds 0x30d0
#define MN_vpdpbusds 0x30da
#define MN_vpdpwusds 0x30e4
#define MN_vpdpbsuds 0x30ee
#define MN_vpdpwsuds 0x30f8
#define MN_vpdpbuuds 0x3102
#define MN_vpdpwuuds 0x310c
#define MN_es (MN_les + 1)
#define MN_les 0x3116
#define MN_xsaves 0x311a
#define MN_fs (MN_lfs + 1)
#define MN_lfs 0x3121
#define MN_gs (MN_lkgs + 2)
#define MN_lkgs 0x3125
#define MN_lgs 0x312a
#define MN_swapgs 0x312e
#define MN_fchs 0x3135
#define MN_js 0x313a
#define MN_encls 0x313d
#define MN_emms (MN_femms + 1)
#define MN_femms 0x3143
#define MN_ins (MN_lwpins + 3)
#define MN_lwpins 0x3149
#define MN_jns 0x3150
#define MN_wrmsrns 0x3154
#define MN_setns 0x315c
#define MN_cmovns 0x3162
#define MN_fcos 0x3169
#define MN_fsincos 0x316e
#define MN_stos 0x3176
#define MN_vfmaddsub231ps 0x317b
#define MN_vfmsub231ps 0x318a
#define MN_vfnmsub231ps 0x3196
#define MN_vfmsubadd231ps 0x31a3
#define MN_vfmadd231ps 0x31b2
#define MN_vfnmadd231ps 0x31be
#define MN_vfmaddsub132ps 0x31cb
#define MN_vfmsub132ps 0x31da
#define MN_vfnmsub132ps 0x31e6
#define MN_vfmsubadd132ps 0x31f3
#define MN_vfmadd132ps 0x3202
#define MN_vfnmadd132ps 0x320e
#define MN_vcvtneebf162ps 0x321b
#define MN_vbcstnebf162ps 0x322a
#define MN_vcvtneobf162ps 0x3239
#define MN_cvtpd2ps (MN_vcvtpd2ps + 1)
#define MN_vcvtpd2ps 0x3248
#define MN_vcvtneeph2ps 0x3252
#define MN_vcvtneoph2ps 0x325f
#define MN_vcvtph2ps 0x326c
#define MN_vbcstnesh2ps 0x3276
#define MN_vpermi2ps 0x3283
#define MN_cvtpi2ps 0x328d
#define MN_vpermil2ps 0x3296
#define MN_vexp2ps 0x32a1
#define MN_cvtdq2ps (MN_vcvtdq2ps + 1)
#define MN_vcvtdq2ps 0x32a9
#define MN_vcvtudq2ps 0x32b3
#define MN_vcvtqq2ps 0x32be
#define MN_vcvtuqq2ps 0x32c8
#define MN_vpermt2ps 0x32d3
#define MN_vfmaddsub213ps 0x32dd
#define MN_vfmsub213ps 0x32ec
#define MN_vfnmsub213ps 0x32f8
#define MN_vfmsubadd213ps 0x3305
#define MN_vfmadd213ps 0x3314
#define MN_vfnmadd213ps 0x3320
#define MN_vrcp14ps 0x332d
#define MN_vrsqrt14ps 0x3336
#define MN_tdpbf16ps 0x3341
#define MN_vdpbf16ps 0x334b
#define MN_tcmmrlfp16ps 0x3355
#define MN_tcmmimfp16ps 0x3362
#define MN_tdpfp16ps 0x336f
#define MN_vrcp28ps 0x3379
#define MN_vrsqrt28ps 0x3382
#define MN_movaps (MN_vmovaps + 1)
#define MN_vmovaps 0x338d
#define MN_subps (MN_addsubps + 3)
#define MN_addsubps (MN_vfmaddsubps + 3)
#define MN_vfmaddsubps 0x3395
#define MN_vaddsubps 0x33a1
#define MN_hsubps (MN_vhsubps + 1)
#define MN_vhsubps 0x33ab
#define MN_vfmsubps 0x33b3
#define MN_vfnmsubps 0x33bc
#define MN_vsubps 0x33c6
#define MN_vgatherpf0dps 0x33cd
#define MN_vscatterpf0dps 0x33db
#define MN_vgatherpf1dps 0x33ea
#define MN_vscatterpf1dps 0x33f8
#define MN_addps (MN_vfmsubaddps + 6)
#define MN_vfmsubaddps 0x3407
#define MN_haddps (MN_vhaddps + 1)
#define MN_vhaddps 0x3413
#define MN_v4fmaddps 0x341b
#define MN_vfmaddps 0x3425
#define MN_v4fnmaddps 0x342e
#define MN_vfnmaddps 0x3439
#define MN_vaddps 0x3443
#define MN_andps (MN_vexpandps + 4)
#define MN_vexpandps 0x344a
#define MN_vandps 0x3454
#define MN_blendps (MN_vblendps + 1)
#define MN_vblendps 0x345b
#define MN_roundps (MN_vroundps + 1)
#define MN_vroundps 0x3464
#define MN_vgatherdps 0x346d
#define MN_vscatterdps 0x3478
#define MN_cmpunordps (MN_vcmpunordps + 1)
#define MN_vcmpunordps 0x3484
#define MN_cmpordps (MN_vcmpordps + 1)
#define MN_vcmpordps 0x3490
#define MN_vreduceps 0x349a
#define MN_vrangeps 0x34a4
#define MN_vcmpngeps 0x34ad
#define MN_vcmpgeps 0x34b7
#define MN_vrndscaleps 0x34c0
#define MN_cmpnleps (MN_vcmpnleps + 1)
#define MN_vcmpnleps 0x34cc
#define MN_cmpleps (MN_vcmpleps + 1)
#define MN_vcmpleps 0x34d6
#define MN_vcmpfalseps 0x34df
#define MN_vcmptrueps 0x34eb
#define MN_vscalefps 0x34f6
#define MN_shufps (MN_vshufps + 1)
#define MN_vshufps 0x3500
#define MN_unpckhps (MN_vunpckhps + 1)
#define MN_vunpckhps 0x3508
#define MN_movlhps (MN_vmovlhps + 1)
#define MN_vmovlhps 0x3512
#define MN_movhps (MN_vmovhps + 1)
#define MN_vmovhps 0x351b
#define MN_movmskps (MN_vmovmskps + 1)
#define MN_vmovmskps 0x3523
#define MN_movhlps (MN_vmovhlps + 1)
#define MN_vmovhlps 0x352d
#define MN_vpermilps 0x3536
#define MN_unpcklps (MN_vunpcklps + 1)
#define MN_vunpcklps 0x3540
#define MN_mulps (MN_vmulps + 1)
#define MN_vmulps 0x354a
#define MN_movlps (MN_vmovlps + 1)
#define MN_vmovlps 0x3551
#define MN_cmps 0x3559
#define MN_vblendmps 0x355e
#define MN_vfixupimmps 0x3568
#define MN_vpermps 0x3574
#define MN_andnps (MN_vandnps + 1)
#define MN_vandnps 0x357c
#define MN_minps (MN_vminps + 1)
#define MN_vminps 0x3584
#define MN_seamops 0x358b
#define MN_rcpps (MN_vrcpps + 1)
#define MN_vrcpps 0x3593
#define MN_dpps (MN_vdpps + 1)
#define MN_vdpps 0x359a
#define MN_cmpps (MN_vcmpps + 1)
#define MN_vcmpps 0x35a0
#define MN_vgetexpps 0x35a7
#define MN_vgatherpf0qps 0x35b1
#define MN_vscatterpf0qps 0x35bf
#define MN_vgatherpf1qps 0x35ce
#define MN_vscatterpf1qps 0x35dc
#define MN_vcmpunord_qps 0x35eb
#define MN_vcmpord_qps 0x35f9
#define MN_cmpneqps (MN_vcmpneqps + 1)
#define MN_vcmpneqps 0x3605
#define MN_cmpeqps (MN_vcmpeqps + 1)
#define MN_vcmpeqps 0x360f
#define MN_vcmpge_oqps 0x3618
#define MN_vcmple_oqps 0x3624
#define MN_vcmpfalse_oqps 0x3630
#define MN_vcmpneq_oqps 0x363f
#define MN_vcmpeq_oqps 0x364c
#define MN_vcmpgt_oqps 0x3658
#define MN_vcmplt_oqps 0x3664
#define MN_vgatherqps 0x3670
#define MN_vscatterqps 0x367b
#define MN_vcmpnge_uqps 0x3687
#define MN_vcmpnle_uqps 0x3694
#define MN_vcmptrue_uqps 0x36a1
#define MN_vcmpneq_uqps 0x36af
#define MN_vcmpeq_uqps 0x36bc
#define MN_vcmpngt_uqps 0x36c8
#define MN_vcmpnlt_uqps 0x36d5
#define MN_orps (MN_vorps + 1)
#define MN_vorps 0x36e2
#define MN_xorps (MN_vxorps + 1)
#define MN_vxorps 0x36e8
#define MN_vcmpunord_sps 0x36ef
#define MN_vcmpord_sps 0x36fd
#define MN_vcmpge_osps 0x3709
#define MN_vcmple_osps 0x3715
#define MN_vcmpfalse_osps 0x3721
#define MN_vcmpneq_osps 0x3730
#define MN_vcmpeq_osps 0x373d
#define MN_vcmpgt_osps 0x3749
#define MN_vcmplt_osps 0x3755
#define MN_vfpclassps 0x3761
#define MN_vcompressps 0x376c
#define MN_vcmpnge_usps 0x3778
#define MN_vcmpnle_usps 0x3785
#define MN_vcmptrue_usps 0x3792
#define MN_vcmpneq_usps 0x37a0
#define MN_vcmpeq_usps 0x37ad
#define MN_vcmpngt_usps 0x37b9
#define MN_vcmpnlt_usps 0x37c6
#define MN_extractps (MN_vextractps + 1)
#define MN_vextractps 0x37d3
#define MN_vcmpngtps 0x37de
#define MN_vcmpgtps 0x37e8
#define MN_cmpnltps (MN_vcmpnltps + 1)
#define MN_vcmpnltps 0x37f1
#define MN_cmpltps (MN_vcmpltps + 1)
#define MN_vcmpltps 0x37fb
#define MN_vgetmantps 0x3804
#define MN_movntps (MN_vmovntps + 1)
#define MN_vmovntps 0x380f
#define MN_insertps (MN_vinsertps + 1)
#define MN_vinsertps 0x3818
#define MN_sqrtps (MN_rsqrtps + 1)
#define MN_rsqrtps (MN_vrsqrtps + 1)
#define MN_vrsqrtps 0x3822
#define MN_vsqrtps 0x382b
#define MN_vtestps 0x3833
#define MN_movups (MN_vmovups + 1)
#define MN_vmovups 0x383b
#define MN_blendvps (MN_vblendvps + 1)
#define MN_vblendvps 0x3843
#define MN_divps (MN_vdivps + 1)
#define MN_vdivps 0x384d
#define MN_vmaskmovps 0x3854
#define MN_maxps (MN_vmaxps + 1)
#define MN_vmaxps 0x385f
#define MN_vfrczps 0x3866
#define MN_xrstors 0x386e
#define MN_ss (MN_vfmsub231ss + 9)
#define MN_vfmsub231ss 0x3876
#define MN_vfnmsub231ss 0x3882
#define MN_vfmadd231ss 0x388f
#define MN_vfnmadd231ss 0x389b
#define MN_vfmsub132ss 0x38a8
#define MN_vfnmsub132ss 0x38b4
#define MN_vfmadd132ss 0x38c1
#define MN_vfnmadd132ss 0x38cd
#define MN_cvtsd2ss (MN_vcvtsd2ss + 1)
#define MN_vcvtsd2ss 0x38da
#define MN_vcvtsh2ss 0x38e4
#define MN_cvtsi2ss (MN_vcvtsi2ss + 1)
#define MN_vcvtsi2ss 0x38ee
#define MN_vcvtusi2ss 0x38f8
#define MN_vfmsub213ss 0x3903
#define MN_vfnmsub213ss 0x390f
#define MN_vfmadd213ss 0x391c
#define MN_vfnmadd213ss 0x3928
#define MN_vrcp14ss 0x3935
#define MN_vrsqrt14ss 0x393e
#define MN_vrcp28ss 0x3949
#define MN_vrsqrt28ss 0x3952
#define MN_subss (MN_vfmsubss + 3)
#define MN_vfmsubss 0x395d
#define MN_vfnmsubss 0x3966
#define MN_vsubss 0x3970
#define MN_addss (MN_v4fmaddss + 4)
#define MN_v4fmaddss 0x3977
#define MN_vfmaddss 0x3981
#define MN_v4fnmaddss 0x398a
#define MN_vfnmaddss 0x3995
#define MN_vaddss 0x399f
#define MN_roundss (MN_vroundss + 1)
#define MN_vroundss 0x39a6
#define MN_cmpunordss (MN_vcmpunordss + 1)
#define MN_vcmpunordss 0x39af
#define MN_cmpordss (MN_vcmpordss + 1)
#define MN_vcmpordss 0x39bb
#define MN_vreducess 0x39c5
#define MN_vrangess 0x39cf
#define MN_vcmpngess 0x39d8
#define MN_vcmpgess 0x39e2
#define MN_vrndscaless 0x39eb
#define MN_cmpnless (MN_vcmpnless + 1)
#define MN_vcmpnless 0x39f7
#define MN_cmpless (MN_vcmpless + 1)
#define MN_vcmpless 0x3a01
#define MN_vcmpfalsess 0x3a0a
#define MN_vcmptruess 0x3a16
#define MN_vscalefss 0x3a21
#define MN_comiss (MN_ucomiss + 1)
#define MN_ucomiss (MN_vucomiss + 1)
#define MN_vucomiss 0x3a2b
#define MN_vcomiss 0x3a34
#define MN_lss (MN_mulss + 2)
#define MN_mulss (MN_vmulss + 1)
#define MN_vmulss 0x3a3c
#define MN_vfixupimmss 0x3a43
#define MN_minss (MN_vminss + 1)
#define MN_vminss 0x3a4f
#define MN_rcpss (MN_vrcpss + 1)
#define MN_vrcpss 0x3a56
#define MN_cmpss (MN_vcmpss + 1)
#define MN_vcmpss 0x3a5d
#define MN_vgetexpss 0x3a64
#define MN_vcmpunord_qss 0x3a6e
#define MN_vcmpord_qss 0x3a7c
#define MN_cmpneqss (MN_vcmpneqss + 1)
#define MN_vcmpneqss 0x3a88
#define MN_cmpeqss (MN_vcmpeqss + 1)
#define MN_vcmpeqss 0x3a92
#define MN_vcmpge_oqss 0x3a9b
#define MN_vcmple_oqss 0x3aa7
#define MN_vcmpfalse_oqss 0x3ab3
#define MN_vcmpneq_oqss 0x3ac2
#define MN_vcmpeq_oqss 0x3acf
#define MN_vcmpgt_oqss 0x3adb
#define MN_vcmplt_oqss 0x3ae7
#define MN_vcmpnge_uqss 0x3af3
#define MN_vcmpnle_uqss 0x3b00
#define MN_vcmptrue_uqss 0x3b0d
#define MN_vcmpneq_uqss 0x3b1b
#define MN_vcmpeq_uqss 0x3b28
#define MN_vcmpngt_uqss 0x3b34
#define MN_vcmpnlt_uqss 0x3b41
#define MN_vcmpunord_sss 0x3b4e
#define MN_vcmpord_sss 0x3b5c
#define MN_vcmpge_osss 0x3b68
#define MN_vcmple_osss 0x3b74
#define MN_vcmpfalse_osss 0x3b80
#define MN_vcmpneq_osss 0x3b8f
#define MN_vcmpeq_osss 0x3b9c
#define MN_vcmpgt_osss 0x3ba8
#define MN_vcmplt_osss 0x3bb4
#define MN_vfpclassss 0x3bc0
#define MN_vcmpnge_usss 0x3bcb
#define MN_vcmpnle_usss 0x3bd8
#define MN_vcmptrue_usss 0x3be5
#define MN_vcmpneq_usss 0x3bf3
#define MN_vcmpeq_usss 0x3c00
#define MN_vcmpngt_usss 0x3c0c
#define MN_vcmpnlt_usss 0x3c19
#define MN_vcmpngtss 0x3c26
#define MN_vcmpgtss 0x3c30
#define MN_cmpnltss (MN_vcmpnltss + 1)
#define MN_vcmpnltss 0x3c39
#define MN_cmpltss (MN_vcmpltss + 1)
#define MN_vcmpltss 0x3c43
#define MN_vgetmantss 0x3c4c
#define MN_movntss 0x3c57
#define MN_sqrtss (MN_rsqrtss + 1)
#define MN_rsqrtss (MN_vrsqrtss + 1)
#define MN_vrsqrtss 0x3c5f
#define MN_vsqrtss 0x3c68
#define MN_vbroadcastss 0x3c70
#define MN_divss (MN_vdivss + 1)
#define MN_vdivss 0x3c7d
#define MN_movss (MN_vmovss + 1)
#define MN_vmovss 0x3c84
#define MN_maxss (MN_vmaxss + 1)
#define MN_vmaxss 0x3c8b
#define MN_vfrczss 0x3c92
#define MN_bts 0x3c9a
#define MN_erets 0x3c9e
#define MN_sets 0x3ca4
#define MN_clts 0x3ca9
#define MN_outs 0x3cae
#define MN_movs (MN_cmovs + 1)
#define MN_cmovs 0x3cb3
#define MN_fldl2t 0x3cb9
#define MN_xlat 0x3cc0
#define MN_bt 0x3cc5
#define MN_fxtract 0x3cc8
#define MN_lgdt 0x3cd0
#define MN_sgdt 0x3cd5
#define MN_lidt 0x3cda
#define MN_sidt 0x3cdf
#define MN_fldt 0x3ce4
#define MN_lldt 0x3ce9
#define MN_sldt 0x3cee
#define MN_ret (MN_iret + 1)
#define MN_iret (MN_uiret + 1)
#define MN_uiret 0x3cf3
#define MN_lret 0x3cf9
#define MN_seamret 0x3cfe
#define MN_sysret 0x3d06
#define MN_hreset 0x3d0d
#define MN_pfcmpgt 0x3d14
#define MN_ht 0x3d1c
#define MN_wait (MN_fwait + 1)
#define MN_fwait 0x3d1f
#define MN_mwait (MN_umwait + 1)
#define MN_umwait 0x3d25
#define MN_mcommit 0x3d2c
#define MN_finit 0x3d34
#define MN_skinit 0x3d3a
#define MN_fninit 0x3d41
#define MN_vmgexit 0x3d48
#define MN_sysexit 0x3d50
#define MN_hlt 0x3d58
#define MN_popcnt 0x3d5c
#define MN_lzcnt 0x3d63
#define MN_tzcnt 0x3d69
#define MN_hnt 0x3d6f
#define MN_int (MN_frndint + 4)
#define MN_frndint 0x3d73
#define MN_not 0x3d7b
#define MN_invept 0x3d7f
#define MN_xsaveopt 0x3d86
#define MN_clflushopt 0x3d8f
#define MN_fstpt 0x3d9a
#define MN_xabort 0x3da0
#define MN_fsqrt 0x3da7
#define MN_pfrsqrt 0x3dad
#define MN_aesdeclast (MN_vaesdeclast + 1)
#define MN_vaesdeclast 0x3db5
#define MN_aesenclast (MN_vaesenclast + 1)
#define MN_vaesenclast 0x3dc1
#define MN_test (MN_ptest + 1)
#define MN_ptest (MN_vptest + 1)
#define MN_vptest 0x3dcd
#define MN_xtest 0x3dd4
#define MN_fst 0x3dda
#define MN_fist 0x3dde
#define MN_rdmsrlist 0x3de3
#define MN_wrmsrlist 0x3ded
#define MN_aeskeygenassist (MN_vaeskeygenassist + 1)
#define MN_vaeskeygenassist 0x3df7
#define MN_vmptrst 0x3e08
#define MN_ftst 0x3e10
#define MN_rmpadjust 0x3e15
#define MN_out 0x3e1f
#define MN_pext 0x3e23
#define MN_bndcu 0x3e28
#define MN_enclu 0x3e2e
#define MN_fcmovnu 0x3e34
#define MN_lddqu (MN_vlddqu + 1)
#define MN_vlddqu 0x3e3c
#define MN_movdqu (MN_maskmovdqu + 4)
#define MN_maskmovdqu (MN_vmaskmovdqu + 1)
#define MN_vmaskmovdqu 0x3e43
#define MN_vmovdqu 0x3e4f
#define MN_rdpkru 0x3e57
#define MN_wrpkru 0x3e5e
#define MN_rdpru 0x3e65
#define MN_eretu 0x3e6b
#define MN_fcmovu 0x3e71
#define MN_xgetbv 0x3e78
#define MN_xsetbv 0x3e7f
#define MN_div (MN_fdiv + 1)
#define MN_fdiv 0x3e86
#define MN_idiv (MN_fidiv + 1)
#define MN_fidiv 0x3e8b
#define MN_enclv 0x3e91
#define MN_fldenv 0x3e97
#define MN_fstenv 0x3e9e
#define MN_fnstenv 0x3ea5
#define MN_mov (MN_vpcmov + 3)
#define MN_vpcmov 0x3ead
#define MN_bndmov 0x3eb4
#define MN_smov 0x3ebb
#define MN_rex_w 0x3ec0
#define MN_vcvttph2w 0x3ec6
#define MN_vcvtph2w 0x3ed0
#define MN_vpermi2w 0x3ed9
#define MN_vpmovm2w 0x3ee2
#define MN_vpermt2w 0x3eeb
#define MN_vpshaw 0x3ef4
#define MN_psraw (MN_vpsraw + 1)
#define MN_vpsraw 0x3efb
#define MN_vphsubbw 0x3f02
#define MN_cbw 0x3f0b
#define MN_psadbw (MN_vdbpsadbw + 3)
#define MN_vdbpsadbw 0x3f0f
#define MN_mpsadbw (MN_vmpsadbw + 1)
#define MN_vmpsadbw 0x3f19
#define MN_vpsadbw 0x3f22
#define MN_vphaddbw 0x3f2a
#define MN_punpckhbw (MN_vpunpckhbw + 1)
#define MN_vpunpckhbw 0x3f33
#define MN_kunpckbw 0x3f3e
#define MN_punpcklbw (MN_vpunpcklbw + 1)
#define MN_vpunpcklbw 0x3f47
#define MN_vphaddubw 0x3f52
#define MN_phsubw (MN_vphsubw + 1)
#define MN_vphsubw 0x3f5c
#define MN_psubw (MN_vpsubw + 1)
#define MN_vpsubw 0x3f64
#define MN_pmovsxbw (MN_vpmovsxbw + 1)
#define MN_vpmovsxbw 0x3f6b
#define MN_pmovzxbw (MN_vpmovzxbw + 1)
#define MN_vpmovzxbw 0x3f75
#define MN_fldcw 0x3f7f
#define MN_fstcw 0x3f85
#define MN_fnstcw 0x3f8b
#define MN_phaddw (MN_vphaddw + 1)
#define MN_vphaddw 0x3f92
#define MN_kaddw 0x3f9a
#define MN_paddw (MN_vpaddw + 1)
#define MN_vpaddw 0x3fa0
#define MN_vpshldw 0x3fa7
#define MN_kandw 0x3faf
#define MN_vpexpandw 0x3fb5
#define MN_pblendw (MN_vpblendw + 1)
#define MN_vpblendw 0x3fbf
#define MN_vpshrdw 0x3fc8
#define MN_packssdw (MN_vpackssdw + 1)
#define MN_vpackssdw 0x3fd0
#define MN_packusdw (MN_vpackusdw + 1)
#define MN_vpackusdw 0x3fda
#define MN_vpmovusdw 0x3fe4
#define MN_vpmovsdw 0x3fee
#define MN_vpmovdw 0x3ff7
#define MN_vpcomgew 0x3fff
#define MN_vpcomlew 0x4008
#define MN_vpcmpnlew 0x4011
#define MN_vpcmplew 0x401b
#define MN_vpcomfalsew 0x4024
#define MN_vpcomtruew 0x4030
#define MN_pi2fw 0x403b
#define MN_pshufw 0x4041
#define MN_pavgw (MN_vpavgw + 1)
#define MN_vpavgw 0x4048
#define MN_prefetchw 0x404f
#define MN_pshufhw (MN_vpshufhw + 1)
#define MN_vpshufhw 0x4059
#define MN_pmulhw (MN_vpmulhw + 1)
#define MN_vpmulhw 0x4062
#define MN_pf2iw 0x406a
#define MN_pshuflw (MN_vpshuflw + 1)
#define MN_vpshuflw 0x4070
#define MN_vpshlw 0x4079
#define MN_psllw (MN_vpsllw + 1)
#define MN_vpsllw 0x4080
#define MN_pmullw (MN_vpmullw + 1)
#define MN_vpmullw 0x4087
#define MN_psrlw (MN_vpsrlw + 1)
#define MN_vpsrlw 0x408f
#define MN_kshiftlw 0x4096
#define MN_vpblendmw 0x409f
#define MN_vptestnmw 0x40a9
#define MN_vpcomw 0x40b3
#define MN_vpermw 0x40ba
#define MN_vptestmw 0x40c1
#define MN_kandnw 0x40ca
#define MN_psignw (MN_vpsignw + 1)
#define MN_vpsignw 0x40d1
#define MN_vpcmpw 0x40d9
#define MN_vpcomeqw 0x40e0
#define MN_vpcomneqw 0x40e9
#define MN_vpcmpneqw 0x40f3
#define MN_pcmpeqw (MN_vpcmpeqw + 1)
#define MN_vpcmpeqw 0x40fd
#define MN_vpmovusqw 0x4106
#define MN_vpmovsqw 0x4110
#define MN_vpmovqw 0x4119
#define MN_verw 0x4121
#define MN_pmulhrw 0x4126
#define MN_korw 0x412e
#define MN_kxnorw 0x4133
#define MN_kxorw 0x413a
#define MN_pinsrw (MN_vpinsrw + 1)
#define MN_vpinsrw 0x4140
#define MN_kshiftrw 0x4148
#define MN_pextrw (MN_vpextrw + 1)
#define MN_vpextrw 0x4151
#define MN_pabsw (MN_vpabsw + 1)
#define MN_vpabsw 0x4159
#define MN_pmaddubsw (MN_vpmaddubsw + 1)
#define MN_vpmaddubsw 0x4160
#define MN_phsubsw (MN_vphsubsw + 1)
#define MN_vphsubsw 0x416b
#define MN_psubsw (MN_vpsubsw + 1)
#define MN_vpsubsw 0x4174
#define MN_phaddsw (MN_vphaddsw + 1)
#define MN_vphaddsw 0x417c
#define MN_paddsw (MN_vpaddsw + 1)
#define MN_vpaddsw 0x4185
#define MN_lmsw 0x418d
#define MN_smsw 0x4192
#define MN_pminsw (MN_vpminsw + 1)
#define MN_vpminsw 0x4197
#define MN_pmulhrsw (MN_vpmulhrsw + 1)
#define MN_vpmulhrsw 0x419f
#define MN_vpcompressw 0x41a9
#define MN_fstsw 0x41b5
#define MN_fnstsw 0x41bb
#define MN_psubusw (MN_vpsubusw + 1)
#define MN_vpsubusw 0x41c2
#define MN_paddusw (MN_vpaddusw + 1)
#define MN_vpaddusw 0x41cb
#define MN_movsw 0x41d4
#define MN_pmaxsw (MN_vpmaxsw + 1)
#define MN_vpmaxsw 0x41da
#define MN_cbtw 0x41e2
#define MN_vpcomgtw 0x41e7
#define MN_pcmpgtw (MN_vpcmpgtw + 1)
#define MN_vpcmpgtw 0x41f0
#define MN_vpcomltw 0x41f9
#define MN_vpcmpnltw 0x4202
#define MN_vpcmpltw 0x420c
#define MN_vpopcntw 0x4215
#define MN_knotw 0x421e
#define MN_vprotw 0x4224
#define MN_vpbroadcastw 0x422b
#define MN_ktestw 0x4238
#define MN_kortestw 0x423f
#define MN_vcvttph2uw 0x4248
#define MN_vcvtph2uw 0x4253
#define MN_vpcomgeuw 0x425d
#define MN_vpcomleuw 0x4267
#define MN_vpcmpnleuw 0x4271
#define MN_vpcmpleuw 0x427c
#define MN_vpcomfalseuw 0x4286
#define MN_vpcomtrueuw 0x4293
#define MN_pmulhuw (MN_vpmulhuw + 1)
#define MN_vpmulhuw 0x429f
#define MN_vpcomuw 0x42a8
#define MN_pminuw (MN_vpminuw + 1)
#define MN_vpminuw 0x42b0
#define MN_vpcmpuw 0x42b8
#define MN_vpcomequw 0x42c0
#define MN_vpcomnequw 0x42ca
#define MN_vpcmpnequw 0x42d5
#define MN_vpcmpequw 0x42e0
#define MN_phminposuw (MN_vphminposuw + 1)
#define MN_vphminposuw 0x42ea
#define MN_vpcomgtuw 0x42f6
#define MN_vpcomltuw 0x4300
#define MN_vpcmpnltuw 0x430a
#define MN_vpcmpltuw 0x4315
#define MN_pmaxuw (MN_vpmaxuw + 1)
#define MN_vpmaxuw 0x431f
#define MN_vpsravw 0x4327
#define MN_vpshldvw 0x432f
#define MN_vpshrdvw 0x4338
#define MN_vpsllvw 0x4341
#define MN_vpsrlvw 0x4349
#define MN_kmovw 0x4351
#define MN_vmovw 0x4357
#define MN_vpmacsww 0x435d
#define MN_vpmacssww 0x4366
#define MN_movzw 0x4370
#define MN_rex_x 0x4376
#define MN_fyl2x 0x437c
#define MN_rex64x 0x4382
#define MN_vcvtneps2bf16x 0x4389
#define MN_pfmax 0x4398
#define MN_adcx 0x439e
#define MN_bndldx 0x43a3
#define MN_vfpclasspdx 0x43aa
#define MN_fclex 0x43b6
#define MN_fnclex 0x43bc
#define MN_rex 0x43c3
#define MN_vcvtpd2phx 0x43c7
#define MN_vcvtdq2phx 0x43d2
#define MN_vcvtudq2phx 0x43dd
#define MN_vcvtqq2phx 0x43e9
#define MN_vcvtuqq2phx 0x43f4
#define MN_vcvtps2phx 0x4400
#define MN_vfpclassphx 0x440b
#define MN_shlx 0x4417
#define MN_mulx 0x441c
#define MN_adox 0x4421
#define MN_vcvttpd2dqx 0x4426
#define MN_vcvtpd2dqx 0x4432
#define MN_vcvttpd2udqx 0x443d
#define MN_vcvtpd2udqx 0x444a
#define MN_rex_rx 0x4456
#define MN_sarx 0x445d
#define MN_shrx 0x4462
#define MN_rorx 0x4467
#define MN_monitorx 0x446c
#define MN_rex_wrx 0x4475
#define MN_vcvtpd2psx 0x447d
#define MN_vcvtph2psx 0x4488
#define MN_vcvtqq2psx 0x4493
#define MN_vcvtuqq2psx 0x449e
#define MN_vfpclasspsx 0x44aa
#define MN_movsx 0x44b6
#define MN_mwaitx 0x44bc
#define MN_bndstx 0x44c3
#define MN_rex_wx 0x44ca
#define MN_rexx 0x44d1
#define MN_vcvtps2phxx 0x44d6
#define MN_movzx 0x44e2
#define MN_rex64y 0x44e8
#define MN_vcvtneps2bf16y 0x44ef
#define MN_vfpclasspdy 0x44fe
#define MN_loadiwkey 0x450a
#define MN_vcvtpd2phy 0x4514
#define MN_vcvtdq2phy 0x451f
#define MN_vcvtudq2phy 0x452a
#define MN_vcvtqq2phy 0x4536
#define MN_vcvtuqq2phy 0x4541
#define MN_vfpclassphy 0x454d
#define MN_vcvttpd2dqy 0x4559
#define MN_vcvtpd2dqy 0x4565
#define MN_vcvttpd2udqy 0x4570
#define MN_vcvtpd2udqy 0x457d
#define MN_rmpquery 0x4589
#define MN_clrssbsy 0x4592
#define MN_setssbsy 0x459b
#define MN_vcvtpd2psy 0x45a4
#define MN_vcvtqq2psy 0x45af
#define MN_vcvtuqq2psy 0x45ba
#define MN_vfpclasspsy 0x45c6
#define MN_rex64xy 0x45d2
#define MN_rexy 0x45da
#define MN_vcvtps2phxy 0x45df
#define MN_rexxy 0x45eb
#define MN_rex64z 0x45f1
#define MN_fldz 0x45f8
#define MN_vfpclasspdz 0x45fd
#define MN_vcvtpd2phz 0x4609
#define MN_vcvtqq2phz 0x4614
#define MN_vcvtuqq2phz 0x461f
#define MN_vfpclassphz 0x462b
#define MN_jz 0x4637
#define MN_jnz 0x463a
#define MN_repnz 0x463e
#define MN_loopnz 0x4644
#define MN_setnz 0x464b
#define MN_cmovnz 0x4651
#define MN_repz 0x4658
#define MN_loopz 0x465d
#define MN_vfpclasspsz 0x4663
#define MN_setz 0x466f
#define MN_cmovz 0x4674
#define MN_rex64xz 0x467a
#define MN_jecxz 0x4682
#define MN_jcxz 0x4688
#define MN_jrcxz 0x468d
#define MN_rexz 0x4693
#define MN_rexxz 0x4698
#define MN_rex64yz 0x469e
#define MN_rex64xyz 0x46a6
#define MN_rexyz 0x46af
#define MN_rexxyz 0x46b5
#define MN__disp32_ 0x46bc
#define MN__vex2_ 0x46c5
#define MN__vex3_ 0x46cc
#define MN__disp16_ 0x46d3
#define MN__disp8_ 0x46dc
#define MN__load_ 0x46e4
#define MN__store_ 0x46eb
#define MN__nooptimize_ 0x46f3
#define MN__rex_ 0x4700
#define MN__evex_ 0x4706
#define MN__vex_ 0x470d
#define MN__insn 0x4713
