2008-11-25  Irfan Rafiq <irfan.rafiq@arc.com>

	* gas/lns/lns.exp		TODO: Exclude for ARC 
	* gas/all/gas.exp		Overhaul testsuite. TODO: activate remaining.
	* gas/arc/{ swi, sbc, add,	Updated standards after verification.
	            sleep, brk, swi,
	            rcc, bic, extb, asl,
	            asr, sexw, adc, j, 
	            lsr,mov,ror,and, 
	            xor, rlc, or, st,
	            jl, extw,add, sub}
