.*Assembler messages:
.*7: Error: SCFI: unhandled op 0x8f may cause incorrect CFI
.*8: Error: SCFI: unhandled op 0x8f may cause incorrect CFI
.*9: Error: SCFI: unhandled op 0xff may cause incorrect CFI
.*10: Error: SCFI: unhandled op 0xff may cause incorrect CFI
.*13: Error: SCFI: hand-crafting instructions not supported
.*11: Error: SCFI: unsupported stack manipulation pattern
.*16: Error: SCFI: forward pass failed for func 'foo'
