# Copyright 2022 Free Software Foundation, Inc.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# The purpose of this test-case is to check various
# gdb_test / gdb_test_multiple properties.

clean_restart

# Check that a command with trailing newline triggers an error.

set results [catch {
    gdb_test "pwd\n" ".*" "cmd with trailing newline"
} output]

gdb_assert { $results == 1 }
set expected_error_msg "Invalid trailing newline in \"pwd\n\" command"
gdb_assert { [string equal $output $expected_error_msg] }
