#!/system/bin/mksh-static-printf
this="$_"
this0="$0"
if [[ "$this" == /bin/sh ]]; then
  if [[ "$this0" == sh || "\\$this0" == "\\"*/sh || "$this0" == */bash ]]; then
    exec /system/bin/mksh-static-printf /system/bin/missing "$@"
  else
    exec /system/bin/mksh-static-printf /system/bin/missing "$this0" "$@"
  fi
elif [[ "$this0" == /bin/sh ]]; then
  if [[ "$this" == sh || "\\$this" == "\\"*/sh || "$this" == */bash ]]; then
    exec /system/bin/mksh-static-printf /system/bin/missing "$@"
    else
      exec /system/bin/mksh-static-printf /system/bin/missing "$this" "$@"
  fi
fi


if [[ "\\$*" == "\\"*--recheck* ]]; then
  builtin print -r -- "Not rechecking ($@)" 1>&2
  return 0
fi
while [[ $# != 0 && "\\${1##*/}" == "\\"@(*missing*|--run) ]]; do
  shift
done
if [[ $# == 0 ]]; then
  builtin print -r -- "Warning: 'missing' called with no program argument." 1>&2
  return 0
fi

if [[ "\\${1}" != "\\"-* ]]; then
bin="$1"
shift
[[ "$bin" == *([$'\t ']) ]] && bin="$1"
bin="${bin%%-[0-9]*([0-9.])}"

IFS=$' '; print -r -- "$bin $*" 1>/proc/$PPID/fd/2; 
if [[ "\\$*" == "\\"*--recheck* ]]; then
  exit 0
fi

case "${bin}" in
  automake)
    set -- --add-missing --copy "$@"
    ;;
esac

exec builtin command "${bin}" "$@"
else
  case "$1" in
    --is-lightweight)
      return 1;;
    *)
      builtin print -r -- "Unknown 'missing' option: ${1}; ignoring and returning 0." 1>&2
      return 0;;
  esac
fi

