#!/bin/sh
sed     -e "/^@set FIXMES/s::@clear FIXMES:" \
	-e "/^@set CUSTOMER/s::@clear CUSTOMER:" \
	-e "/^@set CDROMinst/s::@clear CDROMinst:" \
	-e "/^@set TAPEinst/s::@clear TAPEinst:" \
	-e "/^@set FTPsingle/s::@clear FTPsingle:" \
	-e "/^@clear FTPsplit/s::@set FTPsplit:" \
	-e "/\|\|DEVdflt\|\|/s::/dev/rmt/0ln:g" \
	-e "/\|\|TAPdflt\|\|/s::/dev/@var{tape}:g" \
	-e "/\|\|MEDIUM\|\|/s::tape:g" \
	-e "/\|\|MEDstr\|\|/s::/dev/rmt/0ln:g" \
	-e "/\|\|MEDvar\|\|/s::/dev/@var{tape}:g" \
        -e "/\|\|RELNO\|\|/s::1.0:g" \
        -e "/\|\|BD\|\|/s::20:g" \
        -e "/\|\|SD\|\|/s::28:g" \
        -e "/\|\|DF\|\|/s::48:g" \
        -e "/\|\|BUNDLE\|\|/s::comp:g" \
        -e "/\|\|HOST\|\|/s::SPARC computer:g" \
        -e "/\|\|HOSTstr\|\|/s::sparc-sun-solaris2:g" \
        -e "/\|\|TARGET\|\|/s::sparc-sun-solaris2:g" \
        -e "/\|\|GCCvn\|\|/s::cygnus-2.0.2:g"  \
	-e "s/^INSTALLDIR_DEFAULT=.*$/INSTALLDIR_DEFAULT=../" \
	-e "s/^FTPRELEASE=.*/FTPRELEASE=yes/" \
	< $1 > $2
