#!/bin/sh
# Script to coordinate parsing of S. Chamberlain source-embedded 
# header-file markup language. 

# '-i' option means use *proto-internal* segments, else just *proto*
SFX=p
if [ $1 = "-i" ]; then
	SFX=ip
	shift
fi

out=`echo $2 | cut -d '.' -f 1`

#  passes:
#	1) awk discards lines not intended for header, and marks blocks of
#	   text with comments identifying source file;
#	2) first sed pass interprets Chamberlain markup;
#	3) further sed passes clean up---merging adjacent comments etc.

awk -f $3/awkscan-$SFX $1 |\
sed -f $3/sedscript-p |\
sed -f $3/mergecom-p |\
sed -f $3/startcom-p  |\
sed -f $3/blins-p |\
sed -f $3/movecom-p  >$out.$SFX
