_dnl__						-*-Texinfo-*-
_dnl__ Copyright (c) 1988 1989 1990 1991 Free Software Foundation, Inc.
_dnl__ This file controls overall layout of the GDB manual.
\input texinfo
@setfilename _GDBP__.info
@c $Id$
@c THIS MANUAL REQUIRES TEXINFO-2 macros and info-makers to format properly.
@c
@c NOTE: this manual is marked up for preprocessing with a collection
@c of m4 macros called "pretex.m4".  If you see <_if__> and <_fi__>
@c scattered around the source, you have the full source before
@c preprocessing; if you don't, you have the source configured for
@c _HOST__ architectures (and you can of course get the full source,
@c with all configurations, from wherever you got this).
_if__(0)

THIS IS THE SOURCE PRIOR TO PREPROCESSING.  The full source needs to
be run through m4 before either tex- or info- formatting: for example,
_0__
    m4 pretex.m4 none.m4 m680x0.m4 gdb.texinfo >gdb-680x0.texinfo
_1__
will produce (assuming your path finds either GNU or SysV m4; Berkeley
won't do) a file suitable for formatting.  See the text in "pretex.m4"
for a fuller explanation (and the macro definitions).

_fi__(0)
@tex
\def\$#1${{#1}}  % Kluge: collect RCS revision info without $...$
\xdef\manvers{\$Revision$}  % For use in headers, footers too
@end tex
_include__(gdb.top-m4)
_include__(gdb.sample-m4)
_include__(gdb.invoc-m4)
_include__(gdb.cmds-m4)
_include__(gdb.run-m4)
_include__(gdb.stop-m4)
_include__(gdb.stack-m4)
_include__(gdb.src-m4)
_include__(gdb.data-m4)
_include__(gdb.symb-m4)
_include__(gdb.alter-m4)
_include__(gdb.files-m4)
_include__(gdb.tgts-m4)
_include__(gdb.ctl-m4)
_include__(gdb.canned-m4)
_include__(gdb.emacs-m4)
_include__(gdb.bugs-m4)
_include__(gdb.rdln-m4)
_include__(gdb.rename-m4)
_include__(gdb.install-m4)
_include__(gdb.gpl-m4)

@node Index,  , Copying, Top
@unnumbered Index

@printindex cp

@tex
% I think something like @colophon should be in texinfo.  In the
% meantime:
\long\def\colophon{\hbox to0pt{}\vfill
\centerline{The body of this manual is set in}
\centerline{\fontname\tenrm,}
\centerline{with headings in {\bf\fontname\tenbf}}
\centerline{and examples in {\tt\fontname\tentt}.}
\centerline{{\it\fontname\tenit\/} and}
\centerline{{\sl\fontname\tensl\/}}
\centerline{are used for emphasis.}\vfill}
\page\colophon
% Blame: pesch@cygnus.com, 28mar91.
@end tex

@contents
@bye
