[^:]*: Assembler messages:
[^:]*:6: Error: r0-r12, lr or APSR expected -- `clrm {}'
[^:]*:7: Error: r0-r12, lr or APSR expected -- `clrm {sp}'
[^:]*:8: Error: r0-r12, lr or APSR expected -- `clrm {pc}'
[^:]*:10: Error: VFP single precision register or VPR expected -- `vscclrm {}'
[^:]*:11: Error: VPR expected last -- `vscclrm {s0}'
[^:]*:12: Error: VFP single precision register or VPR expected -- `vscclrm {s1,d1,VPR}'
[^:]*:13: Error: VFP single precision register expected -- `vscclrm {s1-d1,VPR}'
