.*: Assembler messages:
.*:7: Error: swp{b} use is obsoleted for ARMv8 and later
.*:10: Warning: This coprocessor register access is deprecated in ARMv8
.*:11: Warning: This coprocessor register access is deprecated in ARMv8
.*:12: Warning: This coprocessor register access is deprecated in ARMv8
.*:13: Warning: This coprocessor register access is deprecated in ARMv8
.*:14: Warning: This coprocessor register access is deprecated in ARMv8
