#
# Some ARM tests
#
if [istarget arm-*-riscix*] then {
    gas_test "inst.s" "" $stdoptlist "Basic instruction set"

    gas_test "arm3.s" "" $stdoptlist "Arm 3 instructions"

    # These instructions aren't supported, and I'm told some are
    # actually invalid.
    gas_test_error "arm6.s" "" "Arm 6 instructions"

    gas_test "copro.s" "" $stdoptlist "Co processor instructions"

    gas_test "float.s" "" $stdoptlist "Core floating point instructions"
}
