.*: Assembler messages:
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfadd .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfmax .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfmaxnm .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfmin .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfminnm .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfmul .*
[^ :]+:[0-9]+: Error: operand 3 must be the same register as operand 1 -- `bfsub .*
