[^:]*: Assembler messages:
.*: Error: selected processor does not support `fmmla z0.h,z0.b,z0.b'
.*: Error: selected processor does not support `fmmla z0.h,z0.b,z31.b'
.*: Error: selected processor does not support `fmmla z0.h,z31.b,z0.b'
.*: Error: selected processor does not support `fmmla z0.h,z31.b,z31.b'
.*: Error: selected processor does not support `fmmla z31.h,z0.b,z0.b'
.*: Error: selected processor does not support `fmmla z31.h,z0.b,z31.b'
.*: Error: selected processor does not support `fmmla z31.h,z31.b,z0.b'
.*: Error: selected processor does not support `fmmla z31.h,z31.b,z31.b'
