[^:]*: Assembler messages:
.*: Error: selected processor does not support `fmmla z0.s,z0.b,z0.b'
.*: Error: selected processor does not support `fmmla z0.s,z0.b,z31.b'
.*: Error: selected processor does not support `fmmla z0.s,z31.b,z0.b'
.*: Error: selected processor does not support `fmmla z0.s,z31.b,z31.b'
.*: Error: selected processor does not support `fmmla z31.s,z0.b,z0.b'
.*: Error: selected processor does not support `fmmla z31.s,z0.b,z31.b'
.*: Error: selected processor does not support `fmmla z31.s,z31.b,z0.b'
.*: Error: selected processor does not support `fmmla z31.s,z31.b,z31.b'
