[^:]*: Assembler messages:
[^:]*:[0-9]+: Error: selected processor does not support `bti'
[^:]*:[0-9]+: Error: selected processor does not support `bti c'
[^:]*:[0-9]+: Error: selected processor does not support `bti j'
[^:]*:[0-9]+: Error: selected processor does not support `bti jc'
[^:]*:[0-9]+: Error: selected processor does not support `bti C'
[^:]*:[0-9]+: Error: selected processor does not support `bti J'
[^:]*:[0-9]+: Error: selected processor does not support `bti JC'
