[^:]+: Assembler messages:
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `adr w0,#0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `adr x0,#0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `adrp w0,#0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `adrp x0,#0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `blr w0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `blr x0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `ret w0'
[^:]+:[0-9]+: Error: operand 1 must be a Capability register -- `ret x0'
