[^:]*: Assembler messages:
.*: Error: selected processor does not support `fmmla z0.s,z0.h,z0.h'
.*: Error: selected processor does not support `fmmla z0.s,z0.h,z31.h'
.*: Error: selected processor does not support `fmmla z0.s,z31.h,z0.h'
.*: Error: selected processor does not support `fmmla z0.s,z31.h,z31.h'
.*: Error: selected processor does not support `fmmla z31.s,z0.h,z0.h'
.*: Error: selected processor does not support `fmmla z31.s,z0.h,z31.h'
.*: Error: selected processor does not support `fmmla z31.s,z31.h,z0.h'
.*: Error: selected processor does not support `fmmla z31.s,z31.h,z31.h'
