M_MAKEFILE=./tconfig/none ./xconfig/none
srcdir=.
# "no target".
# This can be used to build you a Makefile that only runs administrative
# commands like 'clean', 'gdb.tar.Z', etc.
# Target config file for "no target".  This can be used to build you
# a Makefile that only runs administrative commands like 'clean',
# 'gdb.tar.Z', etc.
#
# Copyright (C) 1990 Free Software Foundation, Inc.

# This file is part of GDB.

# GDB is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.

# GDB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GDB; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
ALLDEPFILES = $(ALLDEPFILES_MAINDIR) $(ALLDEPFILES_SUBDIR)
ALLDEPFILES_MAINDIR=\
altos-xdep.c\
am29k-pinsn.c\
am29k-tdep.c\
arm-convert.s\
arm-pinsn.c\
arm-tdep.c\
arm-xdep.c\
convex-pinsn.c\
convex-tdep.c\
convex-xdep.c\
coredep.c\
exec.c\
gould-pinsn.c\
gould-xdep.c\
hp300ux-xdep.c\
i386-pinsn.c\
i386-tdep.c\
i386-xdep.c\
i960-pinsn.c\
i960-tdep.c\
infptrace.c\
m68k-pinsn.c\
m68k-tdep.c\
m88k-pinsn.c\
m88k-tdep.c\
m88k-xdep.c\
mips-pinsn.c\
mips-tdep.c\
mips-xdep.c\
mipsread.c\
news-xdep.c\
nindy-tdep.c\
ns32k-pinsn.c\
pyr-pinsn.c\
pyr-tdep.c\
pyr-xdep.c\
remote-eb.c\
remote-nindy.c\
remote-vx.c\
solib.c\
sparc-pinsn.c\
sparc-tdep.c\
sparc-xdep.c\
sun3-xdep.c\
sun386-xdep.c\
symm-tdep.c\
symm-xdep.c\
tdesc.c\
umax-xdep.c\
vax-pinsn.c

ALLDEPFILES_SUBDIR=\
nindy-share/Onindy.c\
nindy-share/nindy.c\
nindy-share/ttybreak.c\
nindy-share/ttyflush.c\
vx-share/xdr_ld.c\
vx-share/xdr_ptrace.c\
vx-share/xdr_rdb.c\
vx-share/xdr_regs.c

ALLPARAM=\
tm-29k.h\
tm-3b1.h\
tm-88k.h\
tm-altos.h\
tm-altosgas.h\
tm-arm.h\
tm-bigmips.h\
tm-convex.h\
tm-hp300bsd.h\
tm-hp300hpux.h\
tm-i386v-g.h\
tm-i386v.h\
tm-isi.h\
tm-merlin.h\
tm-mips.h\
tm-news.h\
tm-nindy960.h\
tm-np1.h\
tm-pn.h\
tm-pyr.h\
tm-sparc.h\
tm-sun2.h\
tm-sun2os4.h\
tm-sun3.h\
tm-sun386.h\
tm-sun3os4.h\
tm-sun4os4.h\
tm-symmetry.h\
tm-umax.h\
tm-vax.h\
tm-vx68.h\
tm-vx960.h\
xm-3b1.h\
xm-88k.h\
xm-altos.h\
xm-arm.h\
xm-bigmips.h\
xm-convex.h\
xm-hp300bsd.h\
xm-hp300hpux.h\
xm-i386v.h\
xm-i386v32.h\
xm-isi.h\
xm-merlin.h\
xm-mips.h\
xm-news.h\
xm-news1000.h\
xm-np1.h\
xm-pn.h\
xm-pyr.h\
xm-sparc.h\
xm-sun2.h\
xm-sun3.h\
xm-sun386.h\
xm-sun3os4.h\
xm-sun4os4.h\
xm-symmetry.h\
xm-umax.h\
xm-vax.h

ALLCONFIG=\
./tconfig/3b1\
./tconfig/CVS.adm\
./tconfig/altos\
./tconfig/altosgas\
./tconfig/am29k\
./tconfig/arm\
./tconfig/bigmips\
./tconfig/convex\
./tconfig/hp300bsd\
./tconfig/hp300hpux\
./tconfig/i386v\
./tconfig/i386v-g\
./tconfig/i386v32\
./tconfig/i386v32-g\
./tconfig/i960\
./tconfig/isi\
./tconfig/littlemips\
./tconfig/m88k\
./tconfig/m88k.orig\
./tconfig/merlin\
./tconfig/news\
./tconfig/news1000\
./tconfig/nindy960\
./tconfig/none\
./tconfig/np1\
./tconfig/pn\
./tconfig/pyramid\
./tconfig/sun2os3\
./tconfig/sun2os4\
./tconfig/sun3\
./tconfig/sun386\
./tconfig/sun3os3\
./tconfig/sun3os4\
./tconfig/sun4\
./tconfig/sun4os3\
./tconfig/sun4os4\
./tconfig/symmetry\
./tconfig/umax\
./tconfig/vax\
./tconfig/vxworks68\
./tconfig/vxworks960\
./xconfig/3b1\
./xconfig/CVS.adm\
./xconfig/altos\
./xconfig/altosgas\
./xconfig/arm\
./xconfig/bigmips\
./xconfig/convex\
./xconfig/hp300bsd\
./xconfig/hp300hpux\
./xconfig/i386v\
./xconfig/i386v-g\
./xconfig/i386v32\
./xconfig/i386v32-g\
./xconfig/isi\
./xconfig/littlemips\
./xconfig/m88k\
./xconfig/m88k.orig\
./xconfig/merlin\
./xconfig/news\
./xconfig/news1000\
./xconfig/none\
./xconfig/np1\
./xconfig/pn\
./xconfig/pyramid\
./xconfig/sun2os3\
./xconfig/sun2os4\
./xconfig/sun3\
./xconfig/sun386\
./xconfig/sun3os3\
./xconfig/sun3os4\
./xconfig/sun4\
./xconfig/sun4os3\
./xconfig/sun4os4\
./xconfig/symmetry\
./xconfig/umax\
./xconfig/vax

##Copyright (C) 1989-1991 Free Software Foundation, Inc.

# This file is part of GDB.

# GDB is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.

# GDB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GDB; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

# Place to install binaries. 
bindir=/usr/local/bin

# System V: If you compile gdb with a compiler which uses the coff
# encapsulation feature (this is a function of the compiler used, NOT
# of the m-?.h file selected by config.gdb), you must make sure that
# the GNU nm is the one that is used by munch.

# If you are compiling with GCC, make sure that either 1) You use the
# -traditional flag, or 2) You have the fixed include files where GCC
# can reach them.  Otherwise the ioctl calls in inflow.c and readline.c 
# will be incorrectly compiled.  The "fixincludes" script in the gcc
# distribution will fix your include files up.
#CC=cc
#CC=gcc -traditional
GCC=gcc

VPATH=$(srcdir)

# It is also possible that you will need to add -I/usr/include/sys to the
# CFLAGS section if your system doesn't have fcntl.h in /usr/include (which 
# is where it should be according to Posix).

YACC=bison -y
# YACC=yacc
SHELL=/bin/sh
MAKE=make

# Set this up with gcc if you have gnu ld and the loader will print out
# line numbers for undefinded refs.
#CC-LD=gcc -static
CC-LD=${CC}

# define this to be "gmalloc.o" if you want to use the gnu malloc routine
# (useful for debugging memory allocation problems in gdb).  To use your
# system malloc, uncomment the following two lines.
#GNU_MALLOC =
#MALLOC_CFLAGS = -DNO_MALLOC_CHECK
GNU_MALLOC = gmalloc.o mcheck.o mtrace.o
MALLOC_CFLAGS =

# Where is the "include" directory?  Traditionally ../include or ./include
INCLUDE_DIR =  ${srcdir}/../include
INCLUDE_DEP = $$(INCLUDE_DIR)

# Where is the source dir for the BFD library?  Traditionally ../bfd or ./bfd
# (When we want the binary library built from it, we use ${BFD_DIR}${subdir}.)
BFD_DIR =  ${srcdir}/../bfd
BFD_DEP = $$(BFD_DIR)

# All the includes used for CFLAGS and for lint.
# -I. for config files.
# -I${srcdir} possibly for regex.h also.
INCLUDE_CFLAGS = -I. -I${srcdir} -I$(INCLUDE_DIR) -I${srcdir}/vx-share

# {X,T}M_CFLAGS, if defined, has system-dependent CFLAGS.
# CFLAGS for both GDB and readline.
GLOBAL_CFLAGS = -g ${TM_CFLAGS} ${XM_CFLAGS}
#PROFILE_CFLAGS = -pg

CFLAGS = ${GLOBAL_CFLAGS} ${PROFILE_CFLAGS} ${MALLOC_CFLAGS} ${INCLUDE_CFLAGS}
# None of the things in CFLAGS will do any harm, and on some systems
#  (e.g. SunOS4) it is important to use the M_CFLAGS.
LDFLAGS = $(CFLAGS)

# Where is the "-liberty" library, containing getopt and obstack?
LIBIBERTY =  ${srcdir}/../libiberty${subdir}/libiberty.a

# Flags that describe where you can find the termcap library.
# You may need to make other arrangements for USG.
TERMCAP = -ltermcap

# You must define REGEX and REGEX1 on USG machines.
# If your sysyem is missing alloca(), or, more likely, it's there but
# it doesn't work, define ALLOCA & ALLOCA1

# {X,T}M_CLIBS, if defined, has system-dependent libs
# For example, -lPW for System V to get alloca().
# FIXME STOPGAP FOR BFD LIBRARY: BFD stuff
CLIBS = ${TERMCAP} $(XM_CLIBS) ${TM_CLIBS} ${BFD_DIR}${subdir}/libbfd.a \
	${LIBIBERTY}
CDEPS = ${XM_CDEPS} ${TM_CDEPS} ${BFD_DIR}/libbfd.a \
	${LIBIBERTY}

ADD_FILES = ${REGEX} ${ALLOCA} ${GNU_MALLOC}
ADD_DEPS = ${REGEX1} ${ALLOCA1} ${GNU_MALLOC}

VERSION = 3.95
DIST=gdb-$(VERSION)

LINT=/usr/5bin/lint
LINTFLAGS=

# Source files in the main directory.
# Files which are included via a tconfig/* or xconfig/* file 
# should *not* be specified here; they're in "ALLDEPFILES".
SFILES_MAINDIR = \
	 blockframe.c breakpoint.c command.c core.c \
	 environ.c eval.c expprint.c findvar.c infcmd.c inflow.c infrun.c \
	 main.c printcmd.c \
	 remote.c source.c stack.c symmisc.c symtab.c symfile.c \
	 utils.c valarith.c valops.c valprint.c values.c expread.y \
	 signame.c cplus-dem.c mem-break.c target.c inftarg.c \
	 dbxread.c coffread.c \
	 ieee-float.c 

# Source files in subdirectories (which will be handled separately by
#  'make gdb.tar.Z').
# Files which are included via a tconfig/* or xconfig/* file 
# should *not* be specified here; they're in "ALLDEPFILES".
SFILES_SUBDIR = \
	 ${srcdir}/vx-share/dbgRpcLib.h \
	 ${srcdir}/vx-share/ptrace.h \
	 ${srcdir}/vx-share/reg.h \
	 ${srcdir}/vx-share/vxTypes.h \
	 ${srcdir}/vx-share/vxWorks.h \
	 ${srcdir}/vx-share/wait.h \
	 ${srcdir}/vx-share/xdr_ld.h \
	 ${srcdir}/vx-share/xdr_ptrace.h \
	 ${srcdir}/vx-share/xdr_rdb.h \
	 ${srcdir}/vx-share/xdr_regs.h \
	 ${srcdir}/nindy-share/Makefile \
	 ${srcdir}/nindy-share/VERSION \
	 ${srcdir}/nindy-share/b.out.h \
	 ${srcdir}/nindy-share/block_io.h \
	 ${srcdir}/nindy-share/coff.h \
	 ${srcdir}/nindy-share/demux.h \
	 ${srcdir}/nindy-share/env.h \
	 ${srcdir}/nindy-share/stop.h \
	 ${srcdir}/nindy-share/ttycntl.h

# All source files that go into linking GDB, except config-specified files.
SFILES = $(SFILES_MAINDIR) $(SFILES_SUBDIR)

# All source files that lint should look at
LINTFILES = $(SFILES) expread.tab.c init.c

# Any additional files specified on these lines should also be added to
# the OTHERS = definition below, so they go in the tar files.
SFILES_STAND = $(SFILES) standalone.c
SFILES_KGDB  = $(SFILES) stuff.c kdb-start.c

# Header files that are not named in tconfig/* or xconfig/* go here.
HFILES=	breakpoint.h command.h defs.h environ.h \
	expression.h frame.h gdbcmd.h gdbcore.h \
	getpagesize.h ieee-float.h inferior.h param-no-tm.h param.h \
	signals.h signame.h symfile.h symtab.h \
	target.h tdesc.h terminal.h tm-68k.h tm-i960.h tm-sunos.h \
	value.h

OPCODES = pn-opcode.h np1-opcode.h sparc-opcode.h vax-opcode.h m68k-opcode.h \
	  ns32k-opcode.h convx-opcode.h pyr-opcode.h mips-opcode.h \
	  am29k-opcode.h

REMOTE_EXAMPLES = rem-m68k.shar rem-multi.shar

MALLOCSRC = gmalloc.c mcheck.c mtrace.c mtrace.awk \
	    ansidecl.h stdlib.h gmalloc.h stddef.h

POSSLIBS_MAINDIR = regex.c regex.h alloca.c $(MALLOCSRC)
POSSLIBS = $(POSSLIBS_MAINDIR)

TESTS = testbpt.c testfun.c testrec.c testreg.c testregs.c

# tdesc-lib cannot be named simply tdesc, because if if it were GNU make
# would try to make it from tdesc.c.
# tdesc-lib removed from the list due to Motorola copyrights...gnu@cygnus.com
OTHERS = Makefile.dist depend alldeps.mak Makefile.sdir \
	 createtags munch config.gdb config.status \
	 ChangeLog ChangeLog-3.x \
	 README TODO TAGS WHATS.NEW \
	 gdb.texinfo gdbint.texinfo gdbrc.tex threecol.tex \
	.gdbinit COPYING expread.tab.c stab.def \
	 copying.c Projects Convex.notes copying.awk \
	 saber.suppress standalone.c stuff.c kdb-start.c \
	 hp-include # tests

DEPFILES= ${TDEPFILES} ${XDEPFILES}

SOURCES=$(SFILES) $(ALLDEPFILES)
TAGFILES = $(SOURCES) ${HFILES} ${OPCODES} ${ALLPARAM} ${POSSLIBS} 
TAGFILES_MAINDIR = $(SFILES_MAINDIR) $(ALLDEPFILES_MAINDIR) \
             ${HFILES} ${OPCODES} ${ALLPARAM} ${POSSLIBS_MAINDIR} 
TARFILES = ${TAGFILES_MAINDIR} ${OTHERS} ${REMOTE_EXAMPLES}

OBS = main.o blockframe.o breakpoint.o findvar.o stack.o source.o \
    values.o eval.o valops.o valarith.o valprint.o printcmd.o \
    symtab.o symfile.o symmisc.o infcmd.o infrun.o remote.o \
    command.o utils.o expread.o expprint.o environ.o version.o \
    copying.o $(DEPFILES) signame.o cplus-dem.o mem-break.o target.o \
    inftarg.o ieee-float.o putenv.o \
    dbxread.o coffread.o # mipsread.o

RAPP_OBS = rgdb.o rudp.o rserial.o serial.o udp.o $(XDEPFILES)

TSOBS = core.o inflow.o

NTSOBS = standalone.o

TSSTART = /lib/crt0.o

NTSSTART = kdb-start.o

RL_LIB = readline/libreadline.a
RL_LIB_DEP = $(RL_LIB)

# Prevent Sun make from putting in the machine type.  Setting
# TARGET_ARCH to nothing works for SunOS 3, 4.0, but not for 4.1.
.c.o:
	${CC} -c ${CFLAGS} $<

all: gdb

install: gdb
	cp gdb $(bindir)/gdb.new
	mv $(bindir)/gdb.new $(bindir)/gdb
	$(M_INSTALL)

init.c: $(srcdir)/munch $(MUNCH_DEFINE) $(OBS) $(TSOBS)
	$(srcdir)/munch ${MUNCH_DEFINE} $(OBS) $(TSOBS) > init.c

gdb: $(OBS) $(TSOBS) ${ADD_DEPS} ${RL_LIB_DEP} ${CDEPS} init.o
	${CC-LD} $(LDFLAGS) -o gdb init.o $(OBS) $(TSOBS) $(ADD_FILES) \
	${RL_LIB} $(CLIBS)

saber_gdb: $(SFILES) $(DEPFILES) copying.c version.c
	#setopt load_flags $(CFLAGS) -I$(BFD_DIR)
	#load ./init.c $(SFILES)
	#unload ${srcdir}/expread.y
	#load ${srcdir}/expread.tab.c readline/libreadline.a
	#load copying.c version.c
	#load `echo " "$(DEPFILES) | sed -e 's/\.o/.c/g' -e 's, , ../,g'`
	#load ${LIBIBERTY}/*.c
	#load ${BFD_DIR}/*.c
	#load -ltermcap 
	##void mcheck(a) void (*a)(); { }
	##void mtrace(a) void (*a)(); { }



# This is useful when debugging GDB, because some Unix's don't let you run GDB
# on itself without copying the executable.  So "make gdb1" will make
# gdb and put a copy in gdb1, and you can run it with "gdb gdb1".
# Removing gdb1 before the copy is the right thing if gdb1 is open
# in another process.
gdb1: gdb
	rm -f gdb1
	cp gdb gdb1

# This is a remote stub which runs under unix and starts up an
# inferior process.  This is at least useful for debugging GDB's
# remote support.
rapp: $(RAPP_OBS)
	rm -f rapp_init.c
	${srcdir}/munch ${RAPP_OBS} > rapp_init.c
	${CC-LD} $(LDFLAGS) -o $@ rapp_init.c $(RAPP_OBS)
	
Makefiles= Makefile.sdir $(M_MAKEFILE) \
	${srcdir}/alldeps.mak ${srcdir}/Makefile.dist

MAKE_MAKEFILE= echo "M_MAKEFILE=$(M_MAKEFILE)" | \
	cat - ${Makefiles} ${srcdir}/depend >Makefile

Makefile: $(Makefiles)
	$(MAKE_MAKEFILE)

alldeps.mak: ${srcdir}/tconfig ${srcdir}/xconfig
	rm -f alldeps.mak alldeps.tmp allparam.tmp allconfig.tmp
	for i in `ls -d ${srcdir}/tconfig/*[0-9A-Za-z] \
          ${srcdir}/xconfig/*[0-9A-Za-z] | grep -v RCS` ; do \
	  echo $$i >>allconfig.tmp; \
	  awk <$$i ' \
	    $$1 == "TDEPFILES=" || $$1 == "XDEPFILES=" { \
	      for (i = 2; i <= NF; i++) \
	        print $$i >> "alldeps.tmp" ; \
            } \
	    $$1 == "TM_FILE=" || $$1 == "XM_FILE=" { \
	      print $$2 >> "allparam.tmp" }' ; \
	done
	sort <alldeps.tmp | uniq | \
	  sed -e 's/arm-convert.o/arm-convert.s/' \
	      -e 's!^Onindy.o!nindy-share/Onindy.c!' \
	      -e 's!^nindy.o!nindy-share/nindy.c!' \
	      -e 's!ttybreak.o!nindy-share/ttybreak.c!' \
	      -e 's!ttyflush.o!nindy-share/ttyflush.c!' \
	      -e 's!xdr_ld.o!vx-share/xdr_ld.c!' \
	      -e 's!xdr_ptrace.o!vx-share/xdr_ptrace.c!' \
	      -e 's!xdr_rdb.o!vx-share/xdr_rdb.c!' \
	      -e 's!xdr_regs.o!vx-share/xdr_regs.c!' \
	      -e 's/\.o/.c/' \
	    >alldeps2.tmp
	echo 'ALLDEPFILES = $$(ALLDEPFILES_MAINDIR) $$(ALLDEPFILES_SUBDIR)' \
	    >>alldeps.mak;
	grep -v / alldeps2.tmp | \
	  awk 'BEGIN {printf "ALLDEPFILES_MAINDIR="} \
	    NR == 0 {printf $$0;} \
	    NR != 0 {printf "\\\n" $$0} \
	    END {printf "\n\n"}' >>alldeps.mak;
	grep / alldeps2.tmp | \
	  awk 'BEGIN {printf "ALLDEPFILES_SUBDIR="} \
	    NR == 0 {printf $$0;} \
	    NR != 0 {printf "\\\n" $$0} \
	    END {printf "\n\n"}' >>alldeps.mak;
	sort <allparam.tmp | uniq | awk 'BEGIN {printf "ALLPARAM="} \
	    NR == 0 {printf $$0;} \
	    NR != 0 {printf "\\\n" $$0} \
	    END {printf "\n\n"}' >>alldeps.mak;
	sort <allconfig.tmp | uniq | awk 'BEGIN {printf "ALLCONFIG="} \
	    NR == 0 {printf $$0;} \
	    NR != 0 {printf "\\\n" $$0} \
	    END {printf "\n\n"}' >>alldeps.mak;
	rm -f alldeps.tmp alldeps2.tmp allparam.tmp allconfig.tmp

# The sed script makes everything which depends on {x,t}m.h depend on
# config.status as well, in case someone reconfigures gdb out from
# under an already compiled gdb.
depend: $(SOURCES) Makefile.dist
	@echo Ignore errors about non-existent system-supplied include files
	@echo for systems other than the one you are using.
	@echo "If xm.h and tm.h don't exist, the error messages saying so"
	@echo can safely be ignored.
	@echo Also ignore parse errors in valops.c, and any errors in
	@echo arm-convert.s.
	-$(GCC) -MM $(CFLAGS) -I$(BFD_DIR) \
	    `ls $(SOURCES) | sort -u` >depend.tmp
	<depend.tmp sed -e 's/ [xt]m.h/& config.status/g'  \
	  -e 's; vx-share/; $${srcdir}/vx-share/;g'  \
	  -e 's; nindy-share/; $${srcdir}/nindy-share/;g'  \
	  -e 's; $(INCLUDE_DIR)/; $(INCLUDE_DEP)/;g'  \
	  -e 's; [a-z0-9./]*bfd/; $(BFD_DEP)/;g'  \
	  -e 's; \./; $${srcdir}/;g'  \
	  >depend
	$(MAKE_MAKEFILE)
	rm depend.tmp

config.status:
	@echo "You must configure gdb.  Look at the README file for details."
	@false

# These are not generated by "make depend" because they only are there
# for some machines.
# But these rules don't do what we want; we want to hack the foo.o: tm.h
# dependency to do the right thing.
tm-isi.h tm-sun3.h tm-news.h tm-hp300bsd.h tm-altos.h : tm-68k.h
tm-hp300hpux.h tm-sun2.h tm-3b1.h : tm-68k.h
xm-news1000.h : xm-news.h
xm-i386-sv32.h : xm-i386.h
tm-i386gas.h: tm-i386.h
xm-sun4os4.h : xm-sparc.h
tm-sun4os4.h : tm-sparc.h

kdb : $(NTSSTART) $(OBS) $(NTSOBS) ${ADD_DEPS} ${RL_LIB_DEP}
	rm -f init.c
	$(srcdir)/munch ${MUNCH_DEFINE} $(OBS) $(NTSOBS) > init.c
	$(CC) $(LDFLAGS) -c init.c $(CLIBS) 
	ld -o kdb $(NTSSTART) $(OBS) $(NTSOBS) init.o $(ADD_FILES) \
	${RL_LIB} -lc $(CLIBS)

# Put the proper machine-specific files first.
# createtags will edit the .o in DEPFILES into .c
TAGS: ${TAGFILES}
	$(srcdir)/createtags $(TM_FILE) ${XM_FILE} $(DEPFILES) ${TAGFILES}
tags: TAGS

# FIXME: Get alldeps.mak up to date, config.gdb none, THEN make gdb.tar.Z!
gdb.tar.Z: ${TARFILES}
	rm -f gdb.tar; rm -rf $(DIST)
	cd readline ; make readline.tar
	mkdir $(DIST)
	cd $(DIST) ; for i in ${TARFILES} ; do ln -s ../$$i . ; done
	mkdir $(DIST)/readline
	cd $(DIST)/readline ; tar xf ../../readline/readline.tar
	mkdir $(DIST)/xconfig ${DIST}/tconfig
	cd $(DIST)/tconfig ; \
	  for i in $(ALLCONFIG) ; do ln -s ../../$$i ../$$i ; done
	mkdir $(DIST)/vx-share $(DIST)/nindy-share
	cd $(DIST)/tconfig ; \
	  for i in $(SFILES_SUBDIR) $(ALLDEPFILES_SUBDIR); \
	    do ln -s ../../$$i ../$$i ; done
	tar chf - $(DIST) | compress >gdb.tar.Z
	rm -rf $(DIST)

clean:
	rm -f ${OBS} ${TSOBS} ${NTSOBS} ${ADD_FILES}
	rm -f init.c init.o version.c
	rm -f gdb core gdb.tar gdb.tar.Z make.log
	rm -f gdb[0-9]
	cd readline ; make clean

distclean: clean expread.tab.c TAGS
	rm -f tm.h xm.h config.status
	rm -f y.output yacc.acts yacc.tmp
	rm -f ${TESTS} Makefile

realclean: clean
	rm -f expread.tab.c TAGS
	rm -f tm.h xm.h config.status
	rm -f Makefile

gdb.dvi : gdb.texinfo
	tex gdb.texinfo
	texindex gdb.??
	tex gdb.texinfo

# Make copying.c from COPYING
copying.c : COPYING copying.awk
	awk -f copying.awk < COPYING > copying.c

version.c : Makefile.dist
	echo 'char *version = "$(VERSION)";' >version.c

${srcdir}/expread.tab.c : $(srcdir)/expread.y
	@echo 'Expect 4 shift/reduce conflict.'
	${YACC} $(srcdir)/expread.y
	mv y.tab.c ${srcdir}/expread.tab.c

expread.o : ${srcdir}/expread.tab.c defs.h param.h symtab.h \
            frame.h expression.h
	$(CC) -c ${CFLAGS} `echo ${srcdir}/expread.tab.c | sed 's,^\./,,'`
	mv expread.tab.o expread.o

# dbxread, coffread, mipsread have dependencies on BFD header files.
dbxread.o: ${srcdir}/dbxread.c
	${CC} -c ${CFLAGS} -I$(BFD_DIR) ${srcdir}/dbxread.c

coffread.o: ${srcdir}/coffread.c
	${CC} -c ${CFLAGS} -I$(BFD_DIR) ${srcdir}/coffread.c

mipsread.o: ${srcdir}/mipsread.c
	${CC} -c ${CFLAGS} -I$(BFD_DIR) ${srcdir}/mipsread.c

# Drag in the files that are in another directory.

xdr_ld.o: ${srcdir}/vx-share/xdr_ld.c
	${CC} -c ${CFLAGS} ${srcdir}/vx-share/xdr_ld.c

xdr_ptrace.o: ${srcdir}/vx-share/xdr_ptrace.c
	${CC} -c ${CFLAGS} ${srcdir}/vx-share/xdr_ptrace.c

xdr_rdb.o: ${srcdir}/vx-share/xdr_rdb.c
	${CC} -c ${CFLAGS} ${srcdir}/vx-share/xdr_rdb.c

xdr_regs.o: ${srcdir}/vx-share/xdr_regs.c
	${CC} -c ${CFLAGS} ${srcdir}/vx-share/xdr_regs.c

nindy.o: ${srcdir}/nindy-share/nindy.c
	${CC} -c ${CFLAGS} ${srcdir}/nindy-share/nindy.c

Onindy.o: ${srcdir}/nindy-share/Onindy.c
	${CC} -c ${CFLAGS} ${srcdir}/nindy-share/Onindy.c

ttybreak.o: ${srcdir}/nindy-share/ttybreak.c
	${CC} -c ${CFLAGS} ${srcdir}/nindy-share/ttybreak.c

ttyflush.o: ${srcdir}/nindy-share/ttyflush.c
	${CC} -c ${CFLAGS} ${srcdir}/nindy-share/ttyflush.c

tdesc-lib/libdc.o : force_update
	cd tdesc-lib ; ${MAKE} "SYSV_DEFINE=${SYSV_DEFINE}"

# In LOCAL_INCLUDES, -I${srcdir} is right if srcdir is an absolute path,
# and -I../${srcdir} is right if it is relative (e.g. ".."), so search both.
readline/libreadline.a : force_update
	cd readline ; ${MAKE} "SYSV=${SYSV_DEFINE}"\
		"VPATH=${srcdir}/readline:../${srcdir}/readline"\
		"LOCAL_INCLUDES=-I../ -I${srcdir}/ -I../${srcdir}/"\
		"DEBUG_FLAGS=${GLOBAL_CFLAGS}" "CC=${CC}" libreadline.a

lint: $(LINTFILES)
	$(LINT) $(INCLUDE_CFLAGS) $(LINTFLAGS) $(LINTFILES)

gdb.cxref: $(SFILES)
	cxref -I. $(SFILES) >gdb.cxref

force_update :

# When used with GDB, the demangler should never look for leading
# underscores because GDB strips them off during symbol read-in.  Thus
# -Dnounderscore.  

cplus-dem.o : cplus-dem.c
	${CC} -c ${CFLAGS} -Dnounderscore \
	  `echo ${srcdir}/cplus-dem.c | sed 's,^\./,,'`
altos-xdep.o : altos-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
am29k-pinsn.o : am29k-pinsn.c defs.h target.h am29k-opcode.h 
am29k-tdep.o : am29k-tdep.c defs.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h $(INCLUDE_DIR)/obstack.h frame.h param.h tm.h config.status \
  param-no-tm.h xm.h config.status value.h symtab.h inferior.h breakpoint.h 
arm-pinsn.o : arm-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  arm-opcode.h 
arm-tdep.o : arm-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h arm-opcode.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
arm-xdep.o : arm-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h arm-opcode.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
blockframe.o : blockframe.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  frame.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h value.h \
  target.h 
breakpoint.o : breakpoint.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  frame.h breakpoint.h value.h expression.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h gdbcmd.h command.h inferior.h target.h 
coffread.o : coffread.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  breakpoint.h value.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h symfile.h \
  $(BFD_DIR)/libcoff.h 
command.o : command.c defs.h command.h symtab.h value.h 
convex-pinsn.o : convex-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  symtab.h convx-opcode.h 
convex-tdep.o : convex-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  command.h symtab.h value.h frame.h inferior.h breakpoint.h \
  $(INCLUDE_DIR)/wait.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h \
  gdbcmd.h 
convex-xdep.o : convex-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  command.h symtab.h value.h frame.h inferior.h breakpoint.h \
  $(INCLUDE_DIR)/wait.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h \
  gdbcmd.h 
core.o : core.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h inferior.h \
  breakpoint.h value.h symtab.h command.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h target.h gdbcore.h 
coredep.o : coredep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h $(INCLUDE_DIR)/obstack.h 
cplus-dem.o : cplus-dem.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status 
dbxread.o : dbxread.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  $(INCLUDE_DIR)/a.out.gnu.h $(INCLUDE_DIR)/reloc.h $(INCLUDE_DIR)/stab.gnu.h \
  $(INCLUDE_DIR)/stab.def symtab.h breakpoint.h value.h command.h target.h \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h $(BFD_DIR)/liba.out.h \
  symfile.h 
environ.o : environ.c environ.h defs.h 
eval.o : eval.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h value.h \
  expression.h target.h frame.h 
exec.o : exec.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h inferior.h \
  breakpoint.h value.h symtab.h target.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
expprint.o : expprint.c defs.h symtab.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  expression.h value.h 
findvar.o : findvar.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  frame.h value.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h \
  inferior.h breakpoint.h target.h 
gould-pinsn.o : gould-pinsn.c gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h $(INCLUDE_DIR)/obstack.h defs.h param.h tm.h config.status \
  param-no-tm.h xm.h config.status symtab.h frame.h np1-opcode.h 
gould-xdep.o : gould-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
hp300ux-xdep.o : hp300ux-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  frame.h inferior.h breakpoint.h value.h symtab.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
i386-pinsn.o : i386-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h $(INCLUDE_DIR)/obstack.h 
i386-tdep.o : i386-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
i386-xdep.o : i386-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
i960-pinsn.o : i960-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h 
i960-tdep.o : i960-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  value.h frame.h signame.h ieee-float.h 
ieee-float.o : ieee-float.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  ieee-float.h 
infcmd.o : infcmd.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h frame.h \
  inferior.h breakpoint.h value.h environ.h gdbcmd.h command.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h target.h 
inflow.o : inflow.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h command.h signals.h terminal.h \
  target.h 
infptrace.o : infptrace.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h target.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
infrun.o : infrun.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h frame.h \
  inferior.h breakpoint.h value.h $(INCLUDE_DIR)/wait.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h signame.h command.h terminal.h \
  target.h 
inftarg.o : inftarg.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h target.h $(INCLUDE_DIR)/wait.h \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h ieee-float.h 
m68k-pinsn.o : m68k-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  m68k-opcode.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
m68k-tdep.o : m68k-tdep.c defs.h ieee-float.h 
main.o : main.c defs.h gdbcmd.h command.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  symtab.h inferior.h breakpoint.h value.h frame.h signals.h target.h 
mem-break.o : mem-break.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status 
mips-pinsn.o : mips-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  mips-opcode.h 
mips-tdep.o : mips-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcmd.h command.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
mips-xdep.o : mips-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
mipsread.o : mipsread.c param.h tm.h config.status param-no-tm.h xm.h config.status \
  $(INCLUDE_DIR)/obstack.h defs.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h symfile.h $(INCLUDE_DIR)/intel-coff.h 
news-xdep.o : news-xdep.c 
Onindy.o : ${srcdir}/nindy-share/Onindy.c ${srcdir}/nindy-share/ttycntl.h \
  ${srcdir}/nindy-share/block_io.h $(INCLUDE_DIR)/wait.h ${srcdir}/nindy-share/env.h \
  /usr/include/string.h 
nindy.o : ${srcdir}/nindy-share/nindy.c ${srcdir}/nindy-share/ttycntl.h ${srcdir}/nindy-share/block_io.h \
  $(INCLUDE_DIR)/wait.h ${srcdir}/nindy-share/env.h /usr/include/string.h 
ttybreak.o : ${srcdir}/nindy-share/ttybreak.c ${srcdir}/nindy-share/ttycntl.h 
ttyflush.o : ${srcdir}/nindy-share/ttyflush.c ${srcdir}/nindy-share/ttycntl.h 
nindy-tdep.o : nindy-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  frame.h 
ns32k-pinsn.o : ns32k-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  symtab.h ns32k-opcode.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
printcmd.o : printcmd.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  symtab.h value.h expression.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h gdbcmd.h command.h target.h 
pyr-pinsn.o : pyr-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  pyr-opcode.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
pyr-tdep.o : pyr-tdep.c 
pyr-xdep.o : pyr-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
remote-eb.o : remote-eb.c defs.h tm-29k.h param-no-tm.h xm.h config.status inferior.h \
  breakpoint.h value.h symtab.h frame.h param.h $(INCLUDE_DIR)/wait.h \
  terminal.h target.h 
remote-nindy.o : remote-nindy.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  frame.h inferior.h breakpoint.h value.h symtab.h target.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h command.h ieee-float.h \
  $(INCLUDE_DIR)/wait.h ${srcdir}/nindy-share/ttycntl.h ${srcdir}/nindy-share/demux.h \
  ${srcdir}/nindy-share/env.h ${srcdir}/nindy-share/stop.h 
remote-vx.o : remote-vx.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h $(INCLUDE_DIR)/wait.h target.h \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h command.h symfile.h \
  ${srcdir}/vx-share/xdr_ptrace.h ${srcdir}/vx-share/xdr_regs.h ${srcdir}/vx-share/reg.h \
  ${srcdir}/vx-share/xdr_ld.h ${srcdir}/vx-share/xdr_rdb.h ${srcdir}/vx-share/dbgRpcLib.h 
remote.o : remote.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h target.h $(INCLUDE_DIR)/wait.h \
  terminal.h 
signame.o : signame.c signame.h defs.h param.h tm.h config.status param-no-tm.h xm.h config.status 
solib.o : solib.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h command.h target.h frame.h 
source.o : source.c defs.h symtab.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  command.h gdbcmd.h frame.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h regex.h 
sparc-pinsn.o : sparc-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  symtab.h sparc-opcode.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h /usr/include/string.h target.h 
sparc-tdep.o : sparc-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h signame.h target.h ieee-float.h \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
sparc-xdep.o : sparc-xdep.c defs.h tm-sparc.h param-no-tm.h xm.h config.status inferior.h \
  breakpoint.h value.h symtab.h frame.h param.h target.h gdbcore.h \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h 
stack.o : stack.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h frame.h \
  gdbcmd.h command.h value.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h target.h breakpoint.h 
sun3-xdep.o : sun3-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status inferior.h \
  breakpoint.h value.h symtab.h frame.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
sun386-xdep.o : sun386-xdep.c 
symfile.o : symfile.c defs.h symtab.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h frame.h target.h \
  value.h symfile.h gdbcmd.h command.h breakpoint.h 
symm-tdep.o : symm-tdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
symm-xdep.o : symm-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
symmisc.o : symmisc.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  breakpoint.h value.h command.h 
symtab.o : symtab.c defs.h symtab.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h frame.h target.h \
  value.h symfile.h gdbcmd.h command.h 
target.o : target.c defs.h target.h gdbcmd.h command.h symtab.h inferior.h \
  breakpoint.h value.h frame.h param.h tm.h config.status param-no-tm.h xm.h config.status \
  $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h symfile.h 
tdesc.o : tdesc.c 
umax-xdep.o : umax-xdep.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status frame.h \
  inferior.h breakpoint.h value.h symtab.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h 
utils.o : utils.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status signals.h gdbcmd.h \
  command.h terminal.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h \
  $(INCLUDE_DIR)/obstack.h target.h 
valarith.o : valarith.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status value.h \
  symtab.h expression.h target.h 
valops.o : valops.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h value.h \
  frame.h inferior.h breakpoint.h gdbcore.h $(INCLUDE_DIR)/bfd.h \
  $(INCLUDE_DIR)/ansidecl.h target.h 
valprint.o : valprint.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  value.h gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h gdbcmd.h \
  command.h target.h 
values.o : values.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h value.h \
  gdbcore.h $(INCLUDE_DIR)/bfd.h $(INCLUDE_DIR)/ansidecl.h frame.h command.h \
  gdbcmd.h 
vax-pinsn.o : vax-pinsn.c defs.h param.h tm.h config.status param-no-tm.h xm.h config.status symtab.h \
  vax-opcode.h 
xdr_ld.o : ${srcdir}/vx-share/xdr_ld.c ${srcdir}/vx-share/vxWorks.h ${srcdir}/vx-share/vxTypes.h \
  /usr/include/rpc/rpc.h ${srcdir}/vx-share/xdr_ld.h 
xdr_ptrace.o : ${srcdir}/vx-share/xdr_ptrace.c 
xdr_rdb.o : ${srcdir}/vx-share/xdr_rdb.c ${srcdir}/vx-share/vxWorks.h ${srcdir}/vx-share/vxTypes.h \
  ${srcdir}/vx-share/xdr_rdb.h 
xdr_regs.o : ${srcdir}/vx-share/xdr_regs.c 
