.*Assembler messages:
.*:5: Error: Unrecognized opcode `ldx \$4,\$5\(\$6\)'
.*:6: Error: Opcode not supported.* `absq_s\.qb \$3,\$4'
.*:9: Error: Opcode not supported.* `lbux \$4,\$5\(\$6\)'
.*:10: Error: Opcode not supported.* `absq_s\.qb \$3,\$4'
# ----------------------------------------------------------------------------
.*:18: Error: Opcode not supported.* `lbux \$4,\$5\(\$6\)'
.*:19: Error: Opcode not supported.* `absq_s\.qb \$3,\$4'
# ----------------------------------------------------------------------------
.*:26: Error: Opcode not supported.* `aclr 4,100\(\$4\)'
# ----------------------------------------------------------------------------
.*:29: Warning: The 64-bit microMIPS architecture does not support the `mdmx' extension
.*:30: Error: Unrecognized opcode `add.ob \$f4,\$f6,\$f8'
# ----------------------------------------------------------------------------
.*:34: Warning: The 64-bit microMIPS architecture does not support the `mips3d' extension
.*:35: Error: Unrecognized opcode `addr.ps \$f4,\$f6,\$f8'
# ----------------------------------------------------------------------------
.*:39: Warning: The 64-bit microMIPS architecture does not support the `mt' extension
.*:40: Error: Unrecognized opcode `dmt *'
# ----------------------------------------------------------------------------
.*:44: Warning: The 64-bit microMIPS architecture does not support the `smartmips' extension
.*:45: Error: Unrecognized opcode `maddp \$4,\$5'
# ----------------------------------------------------------------------------
.*:54: Error: Opcode not supported.* `hypcall *'
.*:55: Error: Opcode not supported.* `dmfgc0 \$3,\$29'
# ----------------------------------------------------------------------------
.*:63: Error: Opcode not supported.* `lbue \$4,16\(\$5\)'
