.*: Assembler messages:
.*:21: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:22: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:23: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:24: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:25: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:26: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:35: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
.*:36: Error: Can not represent BFD_RELOC_16_PCREL_S2 relocation in this object file format
