.*: Assembler messages:
.*:2: Error: Invalid register range `lwm \$16-17,0\(\$4\)'
.*:3: Error: Illegal operands `lwm \$17-\$16,0\(\$4\)'
.*:4: Error: Illegal operands `lwm \$16-\$f17,0\(\$4\)'
.*:5: Error: Illegal operands `lwm \$f16-\$17,0\(\$4\)'
.*:6: Error: floating-point expression required `li\.s \$4,foo'
.*:7: Error: cannot create floating-point number
.*:8: Error: floating-point expression required `li\.s \$4,\$4'
.*:9: Error: Illegal operands `li\.s 1.0'
