.*: Assembler messages:
.*:8: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:10: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:12: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:14: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:16: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:18: Warning: Wrong size instruction in a 16-bit branch delay slot
.*:20: Warning: Wrong size instruction in a 16-bit branch delay slot
