SCRIPT_NAME=elf
ELFSIZE=64
SCRIPT_NAME=elfarc
TEMPLATE_NAME=elf
OUTPUT_FORMAT="elf64-littlearc64"

TEXT_START_ADDR=0x00

MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH="arc64:64"
ENTRY=__start
EMBEDDED=yes
