SCRIPT_NAME=elf
ELFSIZE=32
SCRIPT_NAME=elfarc
TEMPLATE_NAME=elf
OUTPUT_FORMAT="elf32-littlearc64"

TEXT_START_ADDR=0x00

MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH="arc64:32"
ENTRY=__start
EMBEDDED=yes
