ARCH="arc64:64"

SCRIPT_NAME=elf
ELFSIZE=64
OUTPUT_FORMAT="elf64-littlearc64"

TEMPLATE_NAME=elf

GENERATE_SHLIB_SCRIPT=yes
GENERATE_PIE_SCRIPT=yes

MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"

TEXT_START_ADDR=0x10000

ENTRY=__start

# To support RELRO security feature.
NO_SMALL_DATA=yes
SEPARATE_GOTPLT=8 #FIXME! what is the true value here?
GENERATE_COMBRELOC_SCRIPT=yes
