source_sh ${srcdir}/emulparams/armelf.sh
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
TEXT_START_ADDR=0x00008000
TARGET2_TYPE=got-rel

GENERATE_SHLIB_SCRIPT=yes
GENERATE_PIE_SCRIPT=yes
unset STACK_ADDR
unset EMBEDDED
