SFRAME_INFO=yes

PARSE_AND_LIST_LONGOPTS_SFRAME='
  {"discard-sframe-sections", no_argument, NULL,
   OPTION_DISCARD_SFRAME_SECTIONS},
'

PARSE_AND_LIST_ARGS_CASES_SFRAME='
    case OPTION_DISCARD_SFRAME_SECTIONS:
      link_info.discard_sframe_sections = true;
      break;
'

PARSE_AND_LIST_LONGOPTS="$PARSE_AND_LIST_LONGOPTS $PARSE_AND_LIST_LONGOPTS_SFRAME"
PARSE_AND_LIST_ARGS_CASES="$PARSE_AND_LIST_ARGS_CASES $PARSE_AND_LIST_ARGS_CASES_SFRAME"
