SFRAME_INFO=yes

PARSE_AND_LIST_LONGOPTS_SFRAME='
  {"no-sframe-info", no_argument, NULL,
   OPTION_NO_LD_SFRAME_INFO},
'

PARSE_AND_LIST_ARGS_CASES_SFRAME='
    case OPTION_NO_LD_SFRAME_INFO:
      link_info.no_ld_sframe_info = true;
      break;
'

PARSE_AND_LIST_LONGOPTS="$PARSE_AND_LIST_LONGOPTS $PARSE_AND_LIST_LONGOPTS_SFRAME"
PARSE_AND_LIST_ARGS_CASES="$PARSE_AND_LIST_ARGS_CASES $PARSE_AND_LIST_ARGS_CASES_SFRAME"
