# Xtensa configuration settings.

## NOTE: This file was automatically generated by the Xtensa Processor
## Generator.  Changes made here will be lost when this file is
## updated or replaced with the settings for a different Xtensa
## processor configuration.  DO NOT EDIT!

MAXPAGESIZE=0x1000
