#!/system/bin/mksh-static-printf
this="$_"
this0="$0"


if [[ "\\$*" == "\\"*@(recheck|autoheader|autoreconf|aclocal|autoconf|automake|config.status)*([0-9.-]) ]]; then
  print -r -- "Not rechecking ($@)" 1>&2
  exit 0
fi
while [[ $# != 0 && "\\${1##*/}" == "\\"@(*missing*|--run) ]]; do
  shift
done
if [[ $# == 0 ]]; then
  print -r -- "Warning: 'missing' called with no program argument." 1>&2
  exit 0
fi

if [[ "\\${1}" != "\\"-* ]]; then
bin="$1"
[[ "$bin" == *([$'\t ']) ]] && bin="$1"
bin="${bin%%-[0-9]*([0-9.])}"

IFS=$' '; print -r -- "$bin $*" 1>&2; 
if [[ "\\$*" == "\\"*--recheck* ]]; then
  exit 0
fi
if [[ "\\$@" == "\\"*@(automake|autoconf|aclocal)* && -e configure ]]; then
  print -r -- "configure already exists; not running $@." 1>&2
  exit 0
fi

shift

case "${bin}" in
  automake)
    set -- --add-missing --copy "$@"
    ;;
esac

else
  case "$1" in
    --is-lightweight)
      exit 1;;
    *)
      print -r -- "Unknown 'missing' option: ${1}; ignoring and exiting 0." 1>&2
      exit 0;;
  esac
fi

if [[ "$this" == /bin/sh ]]; then
  if [[ "$this0" == sh || "\\$this0" == "\\"*/sh || "$this0" == */bash ]]; then
    exec /system/bin/mksh-static-printf /system/bin/missing "$@"
  else
    exec /system/bin/mksh-static-printf /system/bin/missing "$this0" "$@"
  fi
elif [[ "$this0" == /bin/sh ]]; then
  if [[ "$this" == sh || "\\$this" == "\\"*/sh || "$this" == */bash ]]; then
    exec /system/bin/mksh-static-printf /system/bin/missing "$@"
    else
      exec /system/bin/mksh-static-printf /system/bin/missing "$this" "$@"
  fi
fi
command "${bin}" "$@"
exit 0


