m4_include([../bfd/bfd.m4])
m4_include([common.m4])
m4_include([../config/ax_pthread.m4])
m4_include([../gdb/ax_cxx_compile_stdcxx.m4])
m4_include([../gdb/libiberty.m4])
m4_include([../gdb/selftest.m4])
m4_include([../gdb/ptrace.m4])
