.*: Assembler messages:
.*: Error: illegal operands `cv.beqimm t0,-17,foo'
.*: Error: illegal operands `cv.beqimm t2,-32,foo'
.*: Error: illegal operands `cv.beqimm t4,16,foo'
.*: Error: illegal operands `cv.beqimm t3,44,foo'
.*: Error: illegal operands `cv.bneimm t0,-17,foo'
.*: Error: illegal operands `cv.bneimm t2,-32,foo'
.*: Error: illegal operands `cv.bneimm t4,16,foo'
.*: Error: illegal operands `cv.bneimm t3,44,foo'
