.*Assembler messages:
.*Error: extensions must begin with \+/\-/\= in .option arch `m2p0'
.*Error: cannot remove extension `i' in .option arch `\-i'
.*Error: unknown ISA extension `zsubset' in .option arch `\+zsubset2p0'
.*Error: unknown ISA extension `f2p0_d' in .option arch `\+f2p0_d2p0'
.*Error: unknown ISA extension `' in .option arch `\+'
.*Error: invalid ISA extension ends with <number>p in .option arch `\+xvendor2p'
.*Error: .option pop with no .option push
