.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
''' Revision 1.1  2001/03/25 20:32:25  nickc
''' Automate generate on man pages
'''
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH READELF.1 1 "binutils-2.11.90" "23/Mar/101" "GNU"
.UC
.if n .hy 0
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
readelf \- Displays information about ELF files.
.SH "SYNOPSIS"
readelf [ \-a | --all ] 
        [ \-h | --file-header]
        [ \-l | --program-headers | --segments]
        [ \-S | --section-headers | --sections]
        [ \-e | --headers]
        [ \-s | --syms | --symbols]
        [ \-n | --notes]
        [ \-r | --relocs]
        [ \-u | --unwind]
        [ \-d | --dynamic]
        [ \-V | --version-info]
        [ \-D | --use-dynamic]
        [ \-x <number> | --hex-dump=<number>]
        [ \-w[liaprf] | --debug-dump[=info,=line,=abbrev,=pubnames,=ranges,=frames]]
        [      --histogram]
        [ \-v | --version]
        [ \-H | --help]
        \fIelffile\fR...
.SH "DESCRIPTION"
\f(CWreadelf\fR displays information about one or more ELF format object
files.  The options control what particular information to display.
.PP
\fIelffile\fR... are the object files to be examined.  At the
moment, \f(CWreadelf\fR does not support examining archives, nor does it
support examing 64 bit ELF files.
.SH "OPTIONS"
The long and short forms of options, shown here as alternatives, are
equivalent.  At least one option besides \fB\-v\fR or \fB\-H\fR must be
given. 
.Ip "\f(CW-a\fR" 4
.Ip "\f(CW--all\fR" 4
Equivalent to specifiying \fB--file-header\fR,
\fB--program-headers\fR, \fB--sections\fR, \fB--symbols\fR,
\fB--relocs\fR, \fB--dynamic\fR, \fB--notes\fR and
\fB--version-info\fR. 
.Ip "\f(CW-h\fR" 4
.Ip "\f(CW--file-header\fR" 4
Displays the information contained in the \s-1ELF\s0 header at the start of the
file.
.Ip "\f(CW-l\fR" 4
.Ip "\f(CW--program-headers\fR" 4
.Ip "\f(CW--segments\fR" 4
Displays the information contained in the file's segment headers, if it
has any.
.Ip "\f(CW-S\fR" 4
.Ip "\f(CW--sections\fR" 4
.Ip "\f(CW--section-headers\fR" 4
Displays the information contained in the file's section headers, if it
has any.
.Ip "\f(CW-s\fR" 4
.Ip "\f(CW--symbols\fR" 4
.Ip "\f(CW--syms\fR" 4
Displays the entries in symbol table section of the file, if it has one.
.Ip "\f(CW-e\fR" 4
.Ip "\f(CW--headers\fR" 4
Display all the headers in the file.  Equivalent to \fB\-h \-l \-S\fR.
.Ip "\f(CW-n\fR" 4
.Ip "\f(CW--notes\fR" 4
Displays the contents of the \s-1NOTE\s0 segment, if it exists.
.Ip "\f(CW-r\fR" 4
.Ip "\f(CW--relocs\fR" 4
Displays the contents of the file's relocation section, if it has one.
.Ip "\f(CW-u\fR" 4
.Ip "\f(CW--unwind\fR" 4
Displays the contents of the file's unwind section, if it has one.  Only
the unwind sections for \s-1IA64\s0 \s-1ELF\s0 files are currently supported.
.Ip "\f(CW-d\fR" 4
.Ip "\f(CW--dynamic\fR" 4
Displays the contents of the file's dynamic section, if it has one.
.Ip "\f(CW-V\fR" 4
.Ip "\f(CW--version-info\fR" 4
Displays the contents of the version sections in the file, it they
exist.
.Ip "\f(CW-D\fR" 4
.Ip "\f(CW--use-dynamic\fR" 4
When displaying symbols, this option makes \f(CWreadelf\fR use the
symbol table in the file's dynamic section, rather than the one in the
symbols section.
.Ip "\f(CW-x <number>\fR" 4
.Ip "\f(CW--hex-dump=<number>\fR" 4
Displays the contents of the indicated section as a hexadecimal dump.
.Ip "\f(CW-w[liaprf]\fR" 4
.Ip "\f(CW--debug-dump[=line,=info,=abbrev,=pubnames,=ranges,=frames]\fR" 4
Displays the contents of the debug sections in the file, if any are
present.  If one of the optional letters or words follows the switch
then only data found in those specific sections will be dumped.
.Ip "\f(CW--histogram\fR" 4
Display a histogram of bucket list lengths when displaying the contents
of the symbol tables.
.Ip "\f(CW-v\fR" 4
.Ip "\f(CW--version\fR" 4
Display the version number of readelf.
.Ip "\f(CW-H\fR" 4
.Ip "\f(CW--help\fR" 4
Display the command line options understood by \f(CWreadelf\fR.
.SH "SEE ALSO"
\fIobjdump\fR\|(1), and the Info entries for \fIbinutils\fR.
.SH "COPYRIGHT"
Copyright (c) 1991, 92, 93, 94, 95, 96, 97, 98, 99, 2000, 2001 Free Software Foundation, Inc.
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1
or any later version published by the Free Software Foundation;
with no Invariant Sections, with no Front-Cover Texts, and with no
Back-Cover Texts.  A copy of the license is included in the
section entitled \*(L"GNU Free Documentation License\*(R".

.rn }` ''
.IX Title "READELF.1 1"
.IX Name "readelf - Displays information about ELF files."

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\f(CW-a\fR"

.IX Item "\f(CW--all\fR"

.IX Item "\f(CW-h\fR"

.IX Item "\f(CW--file-header\fR"

.IX Item "\f(CW-l\fR"

.IX Item "\f(CW--program-headers\fR"

.IX Item "\f(CW--segments\fR"

.IX Item "\f(CW-S\fR"

.IX Item "\f(CW--sections\fR"

.IX Item "\f(CW--section-headers\fR"

.IX Item "\f(CW-s\fR"

.IX Item "\f(CW--symbols\fR"

.IX Item "\f(CW--syms\fR"

.IX Item "\f(CW-e\fR"

.IX Item "\f(CW--headers\fR"

.IX Item "\f(CW-n\fR"

.IX Item "\f(CW--notes\fR"

.IX Item "\f(CW-r\fR"

.IX Item "\f(CW--relocs\fR"

.IX Item "\f(CW-u\fR"

.IX Item "\f(CW--unwind\fR"

.IX Item "\f(CW-d\fR"

.IX Item "\f(CW--dynamic\fR"

.IX Item "\f(CW-V\fR"

.IX Item "\f(CW--version-info\fR"

.IX Item "\f(CW-D\fR"

.IX Item "\f(CW--use-dynamic\fR"

.IX Item "\f(CW-x <number>\fR"

.IX Item "\f(CW--hex-dump=<number>\fR"

.IX Item "\f(CW-w[liaprf]\fR"

.IX Item "\f(CW--debug-dump[=line,=info,=abbrev,=pubnames,=ranges,=frames]\fR"

.IX Item "\f(CW--histogram\fR"

.IX Item "\f(CW-v\fR"

.IX Item "\f(CW--version\fR"

.IX Item "\f(CW-H\fR"

.IX Item "\f(CW--help\fR"

.IX Header "SEE ALSO"

.IX Header "COPYRIGHT"

