.\" Copyright (c) 1991 Free Software Foundation
.\" See section COPYING for conditions for redistribution
.\" $Id$
.TH strip 1 "5 November 1991" "cygnus support" "GNU Development Tools"
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
strip\(em\&Discard symbols from object files.

.SH SYNOPSIS
.hy 0
.na
.TP
.B strip
.RB "[\|" \-s | +strip-all "\|]" 
.RB "[\|" \-g | \-S | +strip-debug\c
\|]
.RB "[\|" \-x | +discard-all "\|]" 
.RB "[\|" \-X | +discard-locals "\|]"
.RB "[\|" "\-T\ "\c
.I bfdname\c
\&\|]
.I objfiles\c
\&.\|.\|.
.ad b
.hy 1
.SH DESCRIPTION
GNU \c
.B strip\c
\& will discard all symbols from object files
\c
.I objfiles\c
\&, if no options are specified; or only certain symbols,
depending on its command-line options.

\c
.B strip\c
\& will not execute unless at least one object file is listed.

.I WARNING:\c
\& \c
.B strip\c
\& modifies the files named in its argument,
rather than writing modified copies under different names.

.SH OPTIONS
The long and short forms of options, shown here as alternatives, are
equivalent.

.TP
.B \-s
.TP
.B +strip-all 
This is the default case: strip all symbol entries from \c
.I objfiles\c
\&.

.TP
.B \-g
.TP
.B \-S
.TP
.B +strip-debug 
Discard only debugging symbol information from \c
.I objfiles\c
\&.

.TP
.B \-x
.TP
.B +discard-all 
Discard all symbols local to each file in \c
.I objfiles\c
\&.
\c
.I WARNING:\c
\& Note that \c
.B +discard-all\c
\& discards only \c
.I local\c
\&
symbols, in spite of its name.

.TP
.B \-X
.TP
.B +discard-locals 
Discard local symbols starting with `\|\c
.B L\c
\|' from each file in
\c
.I objfiles\c
\&.  (Some compilers produce internally-used symbols that
begin with `\|\c
.B L\c
\|'.)

.TP
.BI "-T " "bfdname"\c
\&
You can specify a particular object-code format \c
.I bfdname\c
\& for
\c
.I objfiles\c
\&.  This may not be necessary; \c
.I strip\c
\& can automatically
recognize many formats.   for information on listing
available formats.
.PP

.SH "SEE ALSO"
.RB "`\|" binutils "\|'" 
entry in 
.B
info\c
\&; 
.I
The GNU Binary Utilities\c
\&, Roland H. Pesch (October 1991).

.SH COPYING
Copyright (c) 1991 Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
