.\" Copyright (c) 1991 Free Software Foundation
.\" See section COPYING for conditions for redistribution
.TH strip 1 "5 November 1991" "cygnus support" "GNU Development Tools"
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
strip\(em\&Discard symbols from object files.

.SH SYNOPSIS
.B strip\c
.RB " [\|" \-v "\|] "\c
.I objfiles\c
\&.\|.\|.

.SH DESCRIPTION
GNU \c
.B strip\c
\& will discard all symbols from object files
\c
.I objfiles\c
\&.  The list of object files may include archives.

\c
.B strip\c
\& will not execute unless at least one object file is listed.

.I WARNING:\c
\& \c
.B strip\c
\& modifies the files named in its argument,
rather than writing modified copies under different names.

.SH OPTIONS
.TP
.B \-v
Verbose operation: list all object files modified.  In the case of
archives, `\|\c
.B strip \-v\c
\&\|' will list all members of the archive.
.PP

.SH "SEE ALSO"
.RB "`\|" binutils "\|'" 
entry in 
.B
info\c
\&; 
.I
The GNU Binary Utilities\c
\&, Roland H. Pesch (October 1991).

.SH COPYING
Copyright (c) 1991 Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
