#
# elf tests
#

# We're testing bits in obj-elf -- don't run on anything else.
if { [istarget "*-elf*"]		
     || [istarget "*-linux*"]
     || [istarget "sparc*-*-solaris*"]
     || [istarget "mips*-*-irix6*"] } then {

    # FIXME: This doesn't work for MIPS targets because of the .reginfo
    # and .mdebug sections.
    setup_xfail mips*-*-*
    run_dump_test "section0" 

    setup_xfail mips*-*-*
    run_dump_test "section1" 
}
