@node RISC-V
@chapter RISC-V
RISC-V Foundation's RISC-V architecture.

@node RISC-V ISA Support
@section ISA Support
The RV32I, RV32E, RV64I, and RV64E bases are supported.

The A, M, Zicsr, and Zifencei extensions are supported.

The F and D extensions are planned but not yet supported.

@node RISC-V Environment Support
@section Environment Support
Only the virtual environment is supported.

@node RISC-V Virtual Environment Syscall ABI
@subsection Virtual Environment Syscall ABI
The syscall ABI, as used by @value{libgloss} in the virtual environment, uses
the interface defined in the following table.

@multitable @columnfractions .2 .3 .5
@headitem Field @tab Assembly/Register @tab Description
@item instruction
@tab @center @code{ecall;}
@tab The assembly instruction to invoke the syscall handler.
@item (in) syscall NR
@tab @center @code{a7}
@tab The system call number to select which function to run.
@item (in) arg 1
@tab @center @code{a0}
@tab The first syscall argument.
@item (in) arg 2
@tab @center @code{a1}
@tab The second syscall argument.
@item (in) arg 3
@tab @center @code{a2}
@tab The third syscall argument.
@item (in) arg 4
@tab @center @code{a3}
@tab The fourth syscall argument.
@item (in) arg 5
@tab @center @code{a4}
@tab The fifth syscall argument.
@item (in) arg 6
@tab @center @code{a5}
@tab The sixth syscall argument.
@item (out) return & error
@tab @center @code{a0}
@tab The return value.
@end multitable
