# Copyright 2012 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib dwarf.exp

# This test can only be run on targets which support DWARF-2 and use gas.
if ![dwarf2_support] {
    return 0  
}

set basename "fission-reread"

standard_testfile .S

# IWBN to use prepare_for_testing here, but we need to set debug-file-directory
# before we load the binary.

if { [build_executable "$testfile.exp" "$testfile" "$srcfile" {nodebug}] } {
    return -1
}

gdb_exit
gdb_start
gdb_reinitialize_dir $srcdir/$subdir
# Set debug-file-directory so we find the dwo file.
gdb_test_no_output "set debug-file-directory $subdir"
gdb_load [standard_output_file $testfile]

gdb_test "break main" "Breakpoint.*at.*"

# If we get this far gdb didn't crash, nor did an error occur.
pass $testfile
