.*: Assembler messages:
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpextrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
.*:[0-9]*: Error:.* `vpinsrq' .*
