_divert__(-1)
_define__(<_AMD29K__>,<1>)
_define__(<_GENERIC__>,<0>)
_define__(<_HOST__>,<AMD 29K>)
_define__(<_MACH_DEP__>,<AMD29K-Dependent>)
_define__(<_AOUT__>,<0>)
_define__(<_BOUT__>,<0>)
_define__(<_COFF__>,<1>)
_define__(<_ELF__>,<0>)
_divert__<>