#!/bin/bash

# Just run the namespace test.  But run it using multiple compilers:
# the regular one, and one which generates more namespace debugging
# info.  Maybe eventually I should run this on one which generates
# stabs info, too?

EXTRADEBUGPATH=/usr/local/testbed/gcc3/bin
TESTS="gdb.cpnamespace.exp gdb.cp/rtti.exp"

echo "Running tests using regular compiler."
runtest ${TESTS} > /dev/null 2>&1
grep -v "^Test Run By" gdb.sum > /tmp/namespaceout
diff -u {carlton_,/tmp/}namespaceout
echo "Running tests using compiler with extra debug info."
PATH=${EXTRADEBUGPATH}:${PATH} runtest ${TESTS} > /dev/null 2>&1
grep -v "^Test Run By" gdb.sum > /tmp/namespacedebugout
diff -u {carlton_,/tmp/}namespacedebugout

echo "Done."
