#!/bin/bash

# Just run the namespace test.  But run it using multiple compilers:
# the regular one, and one which generates more namespace debugging
# info.  Maybe eventually I should run this on one which generates
# stabs info, too?

EXTRACOMPPATH=/usr/local/testbed/gcc3/bin

echo "Running tests using regular compiler."
runtest namespace.exp 2>&1 | grep -v "^Test Run By" > /tmp/namespaceout
diff -u {carlton_,/tmp/}namespaceout
echo "Running tests using compiler with extra debug info."
PATH=${EXTRACOMPPATH}:${PATH} runtest namespace.exp 2>&1 | grep -v "^Test Run By" > /tmp/namespaceout
diff -u {carlton_,/tmp/}namespaceout

echo "Done."
