#!/bin/csh -f
# $1 is the file containing the function ordering
# $2 is the output file

echo '	.SPACE $TEXT$' > /tmp/$$.s
foreach func (`cat $1`)
  echo "	.NSUBSPA $func,QUAD=0,ALIGN=8,ACCESS=44,CODE_ONLY" >> /tmp/$$.s
end

gcc -c /tmp/$$.s -o $2
